/**
 * Indian Food Composition Tables (IFCT) & ICMR-NIN Science-Backed Nutrition Database
 * Comprehensive per-gram macro and micronutrient profiles for authentic Indian ingredients.
 */

export interface IndianIngredient {
  id: string;
  name: string;
  hindiName: string;
  regionalNames?: string[];
  aliases: string[];
  category: 
    | 'Dairy & Alternatives'
    | 'Lentils & Pulses'
    | 'Flours & Grains'
    | 'Vegetables & Greens'
    | 'Tubers & Fasting'
    | 'Nuts & Seeds'
    | 'Oils & Ghee'
    | 'Spices & Seasonings'
    | 'Traditional Prepared Items';
  servingUnit: string;
  defaultServingG: number;
  per100g: {
    calories: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    fiberG: number;
    sodiumMg: number;
    calciumMg: number;
    ironMg: number;
    potassiumMg: number;
    leucineG?: number;
  };
  glycemicIndex: {
    score: number;
    rating: 'Low (<55)' | 'Moderate (56-69)' | 'High (≥70)';
  };
  isVegetarian: boolean;
  isVegan: boolean;
  isFastingSafe?: boolean;
  scientificNotes: string;
  muscleSynthesisTip?: string;
}

export const INDIAN_NUTRITION_DATABASE: IndianIngredient[] = [
  // -------------------------------------------------------------
  // 1. DAIRY & HIGH-PROTEIN BASES
  // -------------------------------------------------------------
  {
    id: 'paneer-full-fat',
    name: 'Paneer (Full Fat / Traditional Malai)',
    hindiName: 'पनीर (मलाई)',
    regionalNames: ['Chhena', 'Panner'],
    aliases: ['paneer', 'malai paneer', 'cottage cheese', 'full fat paneer', 'indian cottage cheese'],
    category: 'Dairy & Alternatives',
    servingUnit: '100g cubes',
    defaultServingG: 100,
    per100g: {
      calories: 296,
      proteinG: 18.3,
      carbsG: 3.4,
      fatG: 23.5,
      fiberG: 0,
      sodiumMg: 22,
      calciumMg: 480,
      ironMg: 0.3,
      potassiumMg: 95,
      leucineG: 1.75,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Rich in micellar casein and bioactive milk calcium. Sustained amino acid release across 5-7 hours.',
    muscleSynthesisTip: 'Pair with vitamin C or raw veggies to balance lipid profile.',
  },
  {
    id: 'paneer-low-fat',
    name: 'Low-Fat Paneer (Skimmed Milk / Diet Paneer)',
    hindiName: 'कम वसा वाला पनीर (डाइट पनीर)',
    regionalNames: ['Low Fat Chhena'],
    aliases: ['low fat paneer', 'diet paneer', 'skimmed paneer', 'light paneer', 'high protein paneer'],
    category: 'Dairy & Alternatives',
    servingUnit: '100g cubes',
    defaultServingG: 150,
    per100g: {
      calories: 145,
      proteinG: 23.5,
      carbsG: 3.2,
      fatG: 4.2,
      fiberG: 0,
      sodiumMg: 35,
      calciumMg: 520,
      ironMg: 0.4,
      potassiumMg: 120,
      leucineG: 2.3,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Highest protein density in Indian vegetarian food. Superior leucine threshold of >2.5g achieved at ~120g serving.',
    muscleSynthesisTip: 'Ideal post-workout or pre-bed snack for lean hypertrophy.',
  },
  {
    id: 'curd-dahi-whole',
    name: 'Curd / Dahi (Plain Whole Milk)',
    hindiName: 'दही (फुल क्रीम)',
    regionalNames: ['Thayir', 'Mosaru', 'Perugu', 'Dahi'],
    aliases: ['curd', 'dahi', 'yogurt', 'plain curd', 'homemade dahi', 'thayir'],
    category: 'Dairy & Alternatives',
    servingUnit: '1 katori (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 61,
      proteinG: 3.5,
      carbsG: 4.7,
      fatG: 3.3,
      fiberG: 0,
      sodiumMg: 46,
      calciumMg: 149,
      ironMg: 0.1,
      potassiumMg: 155,
      leucineG: 0.35,
    },
    glycemicIndex: { score: 28, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Active probiotic cultures (Lactobacillus bulgaricus). Improves gut microflora and protein absorption.',
    muscleSynthesisTip: 'Mix with roasted peanut powder or whey for balanced meal satiety.',
  },
  {
    id: 'curd-greek-hung',
    name: 'Hung Curd / Greek Style Dahi',
    hindiName: 'मस्का / चक्का / गाढ़ा दही',
    regionalNames: ['Chakka', 'Maska', 'Greek Yogurt'],
    aliases: ['hung curd', 'greek yogurt', 'chakka', 'strained dahi', 'thick curd', 'protein dahi'],
    category: 'Dairy & Alternatives',
    servingUnit: '1 katori (120g)',
    defaultServingG: 120,
    per100g: {
      calories: 98,
      proteinG: 10.2,
      carbsG: 3.8,
      fatG: 4.6,
      fiberG: 0,
      sodiumMg: 50,
      calciumMg: 210,
      ironMg: 0.2,
      potassiumMg: 180,
      leucineG: 1.05,
    },
    glycemicIndex: { score: 20, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Whey liquid strained out, leaving concentrated casein with 2.8x standard curd protein concentration.',
    muscleSynthesisTip: 'Excellent high-protein dip or chaat base.',
  },
  {
    id: 'soya-chunks-nutrela',
    name: 'Soya Chunks / Mealmaker (Nutrela)',
    hindiName: 'सोया बड़ी / सोया चंक्स',
    regionalNames: ['Nutrela', 'Soya Vadi', 'Mealmaker'],
    aliases: ['soya chunks', 'nutrela', 'soya badi', 'soya nuggets', 'meal maker', 'soya granules'],
    category: 'Dairy & Alternatives',
    servingUnit: '50g dry (~150g cooked)',
    defaultServingG: 50,
    per100g: {
      calories: 345,
      proteinG: 52.0,
      carbsG: 33.0,
      fatG: 0.5,
      fiberG: 13.0,
      sodiumMg: 18,
      calciumMg: 350,
      ironMg: 14.2,
      potassiumMg: 1700,
      leucineG: 3.9,
    },
    glycemicIndex: { score: 18, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Defatted soybean meal extruded under high temperature. Highest plant protein ratio (52%) with complete amino acid profile.',
    muscleSynthesisTip: 'Boil in salted water and squeeze thoroughly 3 times to remove phytates and oligosaccharides.',
  },
  {
    id: 'tofu-soya-paneer',
    name: 'Tofu (Soya Paneer Firm)',
    hindiName: 'सोया पनीर / टोफू',
    regionalNames: ['Bean Curd'],
    aliases: ['tofu', 'soya paneer', 'firm tofu', 'soy curd'],
    category: 'Dairy & Alternatives',
    servingUnit: '100g cubes',
    defaultServingG: 150,
    per100g: {
      calories: 83,
      proteinG: 10.1,
      carbsG: 1.9,
      fatG: 4.8,
      fiberG: 1.2,
      sodiumMg: 12,
      calciumMg: 350,
      ironMg: 5.4,
      potassiumMg: 121,
      leucineG: 0.88,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Coagulated soy milk. Rich in isoflavones and calcium sulfate.',
    muscleSynthesisTip: 'Pan-sear in a teaspoon of mustard oil with jeera for Indian spiced tofu bhurji.',
  },

  // -------------------------------------------------------------
  // 2. LENTILS, PULSES & DALS (IFCT Standardized)
  // -------------------------------------------------------------
  {
    id: 'moong-dal-yellow-cooked',
    name: 'Yellow Moong Dal (Cooked Tadka)',
    hindiName: 'पीली मूंग दाल (पकी हुई)',
    regionalNames: ['Hesaru Bele', 'Pesara Pappu', 'Muga Dali'],
    aliases: ['moong dal', 'yellow moong', 'cooked moong dal', 'peeli dal', 'moong dal tadka'],
    category: 'Lentils & Pulses',
    servingUnit: '1 katori (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 105,
      proteinG: 7.2,
      carbsG: 16.8,
      fatG: 1.4,
      fiberG: 4.8,
      sodiumMg: 180,
      calciumMg: 36,
      ironMg: 1.9,
      potassiumMg: 280,
      leucineG: 0.58,
    },
    glycemicIndex: { score: 38, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Easiest pulse on gastric digestion. High bioavailability of folate and soluble prebiotic fiber.',
    muscleSynthesisTip: 'Pair with 1 scoop paneer or whey to bridge methionine-cysteine amino acid limitations.',
  },
  {
    id: 'moong-sprouts-raw',
    name: 'Sprouted Green Moong (Raw)',
    hindiName: 'अंकुरित हरा मूंग',
    regionalNames: ['Matki Sprout', 'Moong Sprout'],
    aliases: ['sprouts', 'moong sprouts', 'green moong sprouts', 'ankurit moong', 'germinated moong'],
    category: 'Lentils & Pulses',
    servingUnit: '1 cup (100g)',
    defaultServingG: 100,
    per100g: {
      calories: 90,
      proteinG: 8.5,
      carbsG: 14.2,
      fatG: 0.6,
      fiberG: 5.6,
      sodiumMg: 15,
      calciumMg: 48,
      ironMg: 2.8,
      potassiumMg: 360,
      leucineG: 0.72,
    },
    glycemicIndex: { score: 25, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Germination elevates vitamin C by 600% and halves anti-nutritional phytic acid.',
    muscleSynthesisTip: 'Consume with lemon juice and chaat masala for peak non-heme iron absorption.',
  },
  {
    id: 'chana-dal-cooked',
    name: 'Chana Dal / Bengal Gram (Cooked)',
    hindiName: 'चना दाल (पकी हुई)',
    regionalNames: ['Kadale Bele', 'Senaga Pappu', 'Chana Dali'],
    aliases: ['chana dal', 'bengal gram dal', 'split chickpeas', 'cooked chana dal'],
    category: 'Lentils & Pulses',
    servingUnit: '1 katori (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 128,
      proteinG: 8.1,
      carbsG: 19.5,
      fatG: 2.2,
      fiberG: 6.2,
      sodiumMg: 190,
      calciumMg: 45,
      ironMg: 2.4,
      potassiumMg: 310,
      leucineG: 0.65,
    },
    glycemicIndex: { score: 28, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Lowest glycemic index among all Indian legumes due to high amylose-to-amylopectin ratio.',
    muscleSynthesisTip: 'Great slow-digesting carb source for sustained workout energy.',
  },
  {
    id: 'toor-dal-cooked',
    name: 'Toor / Arhar Dal (Cooked Sambhar/Tadka)',
    hindiName: 'तुअर / अरहर दाल (पकी हुई)',
    regionalNames: ['Togari Bele', 'Kandi Pappu', 'Tuvar Dal'],
    aliases: ['toor dal', 'arhar dal', 'tuvar dal', 'sambhar dal', 'pigeon pea'],
    category: 'Lentils & Pulses',
    servingUnit: '1 katori (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 115,
      proteinG: 7.4,
      carbsG: 18.0,
      fatG: 1.8,
      fiberG: 5.1,
      sodiumMg: 210,
      calciumMg: 38,
      ironMg: 2.1,
      potassiumMg: 290,
      leucineG: 0.60,
    },
    glycemicIndex: { score: 32, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Staple daily protein in Indian households. Rich in potassium and dietary fiber.',
    muscleSynthesisTip: 'Combine with rice at a 1:2 dal-to-rice ratio to complete essential amino acids.',
  },
  {
    id: 'rajma-kidney-beans-cooked',
    name: 'Rajma / Red Kidney Beans (Cooked Gravy)',
    hindiName: 'राजमा (मसाला करी)',
    regionalNames: ['Rajmah'],
    aliases: ['rajma', 'kidney beans', 'rajma masala', 'red kidney beans'],
    category: 'Lentils & Pulses',
    servingUnit: '1 large bowl (200g)',
    defaultServingG: 200,
    per100g: {
      calories: 135,
      proteinG: 8.7,
      carbsG: 22.8,
      fatG: 1.5,
      fiberG: 6.4,
      sodiumMg: 240,
      calciumMg: 52,
      ironMg: 2.9,
      potassiumMg: 405,
      leucineG: 0.72,
    },
    glycemicIndex: { score: 29, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'High resistant starch content fuels colon butyrate production.',
    muscleSynthesisTip: 'Eat with brown rice and low-fat paneer for a complete 30g+ protein meal.',
  },
  {
    id: 'chole-kabuli-chana-cooked',
    name: 'Chole / Chickpeas / Kabuli Chana (Cooked)',
    hindiName: 'काबुली चना / छोले',
    regionalNames: ['Kala Chana', 'Chole'],
    aliases: ['chole', 'chickpeas', 'kabuli chana', 'garbanzo beans', 'chana masala'],
    category: 'Lentils & Pulses',
    servingUnit: '1 bowl (180g)',
    defaultServingG: 180,
    per100g: {
      calories: 148,
      proteinG: 8.9,
      carbsG: 24.2,
      fatG: 2.4,
      fiberG: 7.1,
      sodiumMg: 260,
      calciumMg: 58,
      ironMg: 3.1,
      potassiumMg: 380,
      leucineG: 0.74,
    },
    glycemicIndex: { score: 33, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Exceptional satiety index. Rich in choline for neural transmitter synthesis.',
    muscleSynthesisTip: 'Pre-workout meal 2.5 hours before heavy leg training.',
  },
  {
    id: 'kala-chana-boiled',
    name: 'Kala Chana / Black Chickpeas (Boiled)',
    hindiName: 'काला चना (उबला हुआ)',
    regionalNames: ['Desi Chana'],
    aliases: ['kala chana', 'black chickpeas', 'desi chana', 'boiled kala chana'],
    category: 'Lentils & Pulses',
    servingUnit: '1 bowl (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 152,
      proteinG: 9.6,
      carbsG: 23.5,
      fatG: 2.6,
      fiberG: 8.2,
      sodiumMg: 95,
      calciumMg: 64,
      ironMg: 4.2,
      potassiumMg: 420,
      leucineG: 0.81,
    },
    glycemicIndex: { score: 26, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Superior iron and fiber density compared to white chickpeas.',
    muscleSynthesisTip: 'Traditional Indian wrestling powerhouse fuel.',
  },

  // -------------------------------------------------------------
  // 3. FLOURS, GRAINS & MILLETS
  // -------------------------------------------------------------
  {
    id: 'besan-gram-flour-raw',
    name: 'Besan (Bengal Gram Flour / Chana Atta)',
    hindiName: 'बेसन (चने का आटा)',
    regionalNames: ['Kadalai Maavu', 'Senaga Pindi', 'Besan'],
    aliases: ['besan', 'gram flour', 'chickpea flour', 'chana atta', 'besan chilla flour'],
    category: 'Flours & Grains',
    servingUnit: '1/2 cup (60g)',
    defaultServingG: 60,
    per100g: {
      calories: 387,
      proteinG: 22.4,
      carbsG: 57.8,
      fatG: 6.7,
      fiberG: 10.8,
      sodiumMg: 64,
      calciumMg: 73,
      ironMg: 5.3,
      potassiumMg: 846,
      leucineG: 1.82,
    },
    glycemicIndex: { score: 35, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'High-protein gluten-free flour. Ideal for protein chillas and savory pancakes.',
    muscleSynthesisTip: 'Make Besan-Paneer Chilla for 28g protein breakfast under 350 kcal.',
  },
  {
    id: 'sattu-roasted-chana-flour',
    name: 'Sattu (Roasted Bengal Gram Flour)',
    hindiName: 'सत्तू (भुने चने का आटा)',
    regionalNames: ['Bihari Sattu', 'Chana Sattu'],
    aliases: ['sattu', 'roasted chana powder', 'sattu drink', 'chana sattu', 'bihar protein powder'],
    category: 'Flours & Grains',
    servingUnit: '3 tbsp (40g)',
    defaultServingG: 40,
    per100g: {
      calories: 413,
      proteinG: 25.6,
      carbsG: 62.0,
      fatG: 5.2,
      fiberG: 14.5,
      sodiumMg: 45,
      calciumMg: 95,
      ironMg: 7.2,
      potassiumMg: 920,
      leucineG: 2.1,
    },
    glycemicIndex: { score: 30, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Pre-cooked roasted flour with cooling gastrointestinal properties and high insoluble fiber.',
    muscleSynthesisTip: 'Mix with chilled water, roasted jeera, black salt, and lemon for traditional protein hydration.',
  },
  {
    id: 'wheat-roti-phulka',
    name: 'Whole Wheat Roti / Phulka (Without Ghee)',
    hindiName: 'गेहूं की रोटी / फुल्का (बिना घी)',
    regionalNames: ['Chapatis', 'Roti', 'Rotli'],
    aliases: ['roti', 'chapati', 'phulka', 'whole wheat roti', 'dry roti', 'atta roti'],
    category: 'Flours & Grains',
    servingUnit: '1 medium roti (35g raw / ~40g cooked)',
    defaultServingG: 40,
    per100g: {
      calories: 260,
      proteinG: 9.5,
      carbsG: 52.0,
      fatG: 1.5,
      fiberG: 9.2,
      sodiumMg: 4,
      calciumMg: 38,
      ironMg: 3.8,
      potassiumMg: 280,
      leucineG: 0.65,
    },
    glycemicIndex: { score: 55, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Chakki-ground whole wheat preserves wheat germ and bran micronutrients.',
    muscleSynthesisTip: '1 medium roti delivers ~104 kcal and 3.8g protein.',
  },
  {
    id: 'ragi-finger-millet-flour',
    name: 'Ragi / Nachni / Finger Millet Flour',
    hindiName: 'रागी / नाचनी का आटा',
    regionalNames: ['Kezhvaragu', 'Ragulu', 'Nachni'],
    aliases: ['ragi', 'nachni', 'finger millet', 'ragi flour', 'ragi mudde', 'ragi roti'],
    category: 'Flours & Grains',
    servingUnit: '1/2 cup (50g)',
    defaultServingG: 50,
    per100g: {
      calories: 328,
      proteinG: 7.3,
      carbsG: 72.0,
      fatG: 1.3,
      fiberG: 11.5,
      sodiumMg: 11,
      calciumMg: 344,
      ironMg: 3.9,
      potassiumMg: 408,
      leucineG: 0.62,
    },
    glycemicIndex: { score: 54, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Highest calcium content of any grain (344mg/100g). Rich in polyphenols that blunt insulin spikes.',
    muscleSynthesisTip: 'Superb for bone density and joint protection in heavy lifters.',
  },
  {
    id: 'jowar-sorghum-flour',
    name: 'Jowar / Sorghum Flour (Bhakri)',
    hindiName: 'ज्वार का आटा (भाकरी)',
    regionalNames: ['Cholam', 'Jonna'],
    aliases: ['jowar', 'sorghum', 'jowar roti', 'jowar bhakri', 'jowar flour'],
    category: 'Flours & Grains',
    servingUnit: '1 medium bhakri (60g)',
    defaultServingG: 60,
    per100g: {
      calories: 349,
      proteinG: 10.4,
      carbsG: 72.6,
      fatG: 1.9,
      fiberG: 9.7,
      sodiumMg: 6,
      calciumMg: 25,
      ironMg: 4.1,
      potassiumMg: 363,
      leucineG: 1.25,
    },
    glycemicIndex: { score: 50, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Gluten-free grain with rich resistant starch profile and high leucine for plant grain.',
    muscleSynthesisTip: 'Eat with low-fat paneer bhurji or thick dal.',
  },
  {
    id: 'bajra-pearl-millet-flour',
    name: 'Bajra / Pearl Millet Flour',
    hindiName: 'बाजरे का आटा',
    regionalNames: ['Kambu', 'Sajjalu'],
    aliases: ['bajra', 'pearl millet', 'bajra roti', 'bajra bhakri', 'kambu'],
    category: 'Flours & Grains',
    servingUnit: '1 medium roti (60g)',
    defaultServingG: 60,
    per100g: {
      calories: 361,
      proteinG: 11.6,
      carbsG: 67.5,
      fatG: 5.0,
      fiberG: 11.3,
      sodiumMg: 10,
      calciumMg: 42,
      ironMg: 8.0,
      potassiumMg: 390,
      leucineG: 1.18,
    },
    glycemicIndex: { score: 54, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Highest iron concentration (8mg/100g) among standard millets. Thermogenic winter food.',
    muscleSynthesisTip: 'Enhances hemoglobin and oxygen delivery during high-intensity training.',
  },
  {
    id: 'basmati-rice-cooked',
    name: 'White Basmati Rice (Cooked / Steamed)',
    hindiName: 'बासमती चावल (पका हुआ)',
    regionalNames: ['Chawal', 'Sadam', 'Bhat'],
    aliases: ['rice', 'basmati rice', 'steamed rice', 'cooked rice', 'white rice', 'bhat'],
    category: 'Flours & Grains',
    servingUnit: '1 katori / 1 cup (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 130,
      proteinG: 2.7,
      carbsG: 28.2,
      fatG: 0.3,
      fiberG: 0.4,
      sodiumMg: 1,
      calciumMg: 10,
      ironMg: 0.2,
      potassiumMg: 35,
      leucineG: 0.22,
    },
    glycemicIndex: { score: 58, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Fast glycogen replenishment source without gastrointestinal distress.',
    muscleSynthesisTip: 'Perfect intra-window post-workout carbohydrate.',
  },
  {
    id: 'poha-flattened-rice-cooked',
    name: 'Poha / Flattened Rice (Cooked Maharashtrian Style)',
    hindiName: 'पोहा (पका हुआ)',
    regionalNames: ['Avalakki', 'Atukulu', 'Aval', 'Kanda Poha'],
    aliases: ['poha', 'flattened rice', 'kanda poha', 'beaten rice', 'batata poha'],
    category: 'Flours & Grains',
    servingUnit: '1 plate (160g)',
    defaultServingG: 160,
    per100g: {
      calories: 165,
      proteinG: 3.4,
      carbsG: 27.5,
      fatG: 4.8,
      fiberG: 2.2,
      sodiumMg: 190,
      calciumMg: 28,
      ironMg: 2.6,
      potassiumMg: 110,
      leucineG: 0.28,
    },
    glycemicIndex: { score: 64, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Flattening process infuses iron from processing rollers. Light on stomach.',
    muscleSynthesisTip: 'Boost with boiled sprouts or roasted peanuts for protein balance.',
  },

  // -------------------------------------------------------------
  // 4. TUBERS & FASTING (UPWAS / VRAT)
  // -------------------------------------------------------------
  {
    id: 'sabudana-tapioca-cooked',
    name: 'Cooked Tapioca Pearls (Sabudana / Sago)',
    hindiName: 'साबूदाना (पका हुआ / खिचड़ी बेस)',
    regionalNames: ['Javvarisi', 'Sagubiyyam', 'Sabudana'],
    aliases: ['sabudana', 'sago', 'tapioca pearls', 'sabudana khichdi', 'cooked sabudana', 'soaked sabudana'],
    category: 'Tubers & Fasting',
    servingUnit: '1 katori (140g)',
    defaultServingG: 140,
    per100g: {
      calories: 150,
      proteinG: 0.2,
      carbsG: 36.0,
      fatG: 0.1,
      fiberG: 0.9,
      sodiumMg: 5,
      calciumMg: 10,
      ironMg: 0.4,
      potassiumMg: 12,
      leucineG: 0.02,
    },
    glycemicIndex: { score: 72, rating: 'High (≥70)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Pure, easily digestible starch with zero gluten. Rapidly elevates blood glucose.',
    muscleSynthesisTip: 'Always prepare with roasted crushed peanuts (shengdana) and curd to flatten insulin spike.',
  },
  {
    id: 'potato-boiled-aloo',
    name: 'Boiled Potato (Aloo)',
    hindiName: 'उबला हुआ आलू',
    regionalNames: ['Urulaikizhangu', 'Alu', 'Batata'],
    aliases: ['potato', 'aloo', 'boiled aloo', 'batata', 'boiled potato'],
    category: 'Tubers & Fasting',
    servingUnit: '1 medium (100g)',
    defaultServingG: 100,
    per100g: {
      calories: 87,
      proteinG: 1.9,
      carbsG: 20.1,
      fatG: 0.1,
      fiberG: 1.8,
      sodiumMg: 6,
      calciumMg: 12,
      ironMg: 0.8,
      potassiumMg: 421,
      leucineG: 0.12,
    },
    glycemicIndex: { score: 78, rating: 'High (≥70)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Highest satiety index of any carbohydrate. Chilling boiled potatoes forms resistant starch type 3.',
    muscleSynthesisTip: 'Excellent post-workout glycogen fuel with rich electrolyte potassium.',
  },

  // -------------------------------------------------------------
  // 5. NUTS, SEEDS & HEALTHY FATS
  // -------------------------------------------------------------
  {
    id: 'peanuts-roasted-crushed',
    name: 'Roasted Peanuts / Shengdana Powder',
    hindiName: 'भुनी हुई मूंगफली का कूट (दाण्याचा कूट)',
    regionalNames: ['Kadale Kai', 'Verkadalai', 'Shengdana'],
    aliases: ['peanuts', 'peanut powder', 'roasted peanuts', 'shengdana', 'mungfali', 'peanut koot'],
    category: 'Nuts & Seeds',
    servingUnit: '2 tbsp (30g)',
    defaultServingG: 30,
    per100g: {
      calories: 567,
      proteinG: 25.8,
      carbsG: 16.1,
      fatG: 49.2,
      fiberG: 8.5,
      sodiumMg: 18,
      calciumMg: 92,
      ironMg: 4.6,
      potassiumMg: 705,
      leucineG: 1.65,
    },
    glycemicIndex: { score: 14, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Rich in monounsaturated oleic acid, resveratrol, and plant protein (26%).',
    muscleSynthesisTip: 'The primary protein amplifier in Maharashtrian & Gujarati fasting diets.',
  },
  {
    id: 'almonds-badam-raw',
    name: 'Almonds (Badam - Raw / Soaked)',
    hindiName: 'बादाम (भिगोए हुए)',
    regionalNames: ['Badam'],
    aliases: ['almonds', 'badam', 'soaked badam', 'raw almonds'],
    category: 'Nuts & Seeds',
    servingUnit: '10-12 pieces (15g)',
    defaultServingG: 15,
    per100g: {
      calories: 579,
      proteinG: 21.2,
      carbsG: 21.6,
      fatG: 49.9,
      fiberG: 12.5,
      sodiumMg: 1,
      calciumMg: 269,
      ironMg: 3.7,
      potassiumMg: 733,
      leucineG: 1.48,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Highest alpha-tocopherol vitamin E density of whole food nuts.',
    muscleSynthesisTip: 'Soaking overnight removes tannin skin inhibitors for optimal zinc & iron bioavailability.',
  },
  {
    id: 'desi-cow-ghee',
    name: 'Desi Cow Ghee (Clarified Butter)',
    hindiName: 'शुद्ध देशी गाय का घी',
    regionalNames: ['Tuppa', 'Neyyi', 'Ghee'],
    aliases: ['ghee', 'desi ghee', 'cow ghee', 'clarified butter', 'shuddh ghee'],
    category: 'Oils & Ghee',
    servingUnit: '1 tsp (5g) / 1 tbsp (14g)',
    defaultServingG: 5,
    per100g: {
      calories: 897,
      proteinG: 0,
      carbsG: 0,
      fatG: 99.5,
      fiberG: 0,
      sodiumMg: 0,
      calciumMg: 0,
      ironMg: 0,
      potassiumMg: 0,
      leucineG: 0,
    },
    glycemicIndex: { score: 0, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Rich in short and medium chain fatty acids (butyrate, CLA). Smoke point of 250°C prevents lipid peroxidation.',
    muscleSynthesisTip: 'Limit to 1-2 tsp daily to preserve cardiovascular LDL targets.',
  },
  {
    id: 'mustard-oil-kachi-ghani',
    name: 'Mustard Oil (Sarson Ka Tel - Cold Pressed)',
    hindiName: 'सरसों का तेल (कच्ची घानी)',
    regionalNames: ['Kadugu Ennai', 'Sarson Tel'],
    aliases: ['mustard oil', 'sarson oil', 'sarson ka tel', 'kachi ghani'],
    category: 'Oils & Ghee',
    servingUnit: '1 tsp (5g) / 1 tbsp (14g)',
    defaultServingG: 5,
    per100g: {
      calories: 884,
      proteinG: 0,
      carbsG: 0,
      fatG: 100,
      fiberG: 0,
      sodiumMg: 0,
      calciumMg: 0,
      ironMg: 0,
      potassiumMg: 0,
    },
    glycemicIndex: { score: 0, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Optimal 1:1 ratio of omega-6 to omega-3 alpha-linolenic acid (ALA). Potent allyl isothiocyanate antimicrobial compound.',
    muscleSynthesisTip: 'Healthy plant cooking medium for North/East Indian tadkas.',
  },

  // -------------------------------------------------------------
  // 6. SPICES & SEASONINGS (IFCT Standardized)
  // -------------------------------------------------------------
  {
    id: 'turmeric-haldi-powder',
    name: 'Turmeric Powder (Haldi)',
    hindiName: 'हल्दी पाउडर',
    regionalNames: ['Manjal', 'Pasupu', 'Haldi'],
    aliases: ['turmeric', 'haldi', 'turmeric powder', 'curcumin'],
    category: 'Spices & Seasonings',
    servingUnit: '1/2 tsp (2g)',
    defaultServingG: 2,
    per100g: {
      calories: 349,
      proteinG: 7.8,
      carbsG: 64.9,
      fatG: 9.9,
      fiberG: 21.1,
      sodiumMg: 38,
      calciumMg: 182,
      ironMg: 41.4,
      potassiumMg: 2525,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Curcuminoid bioactives inhibit NF-kB inflammatory cascade and reduce exercise-induced DOMS.',
    muscleSynthesisTip: 'Pair with black pepper (piperine) to increase systemic bioavailability by 2000%.',
  },
  {
    id: 'cumin-seeds-jeera',
    name: 'Cumin Seeds (Jeera)',
    hindiName: 'जीरा',
    regionalNames: ['Jeeragam', 'Jilakara', 'Jeera'],
    aliases: ['cumin', 'jeera', 'cumin seeds', 'zeera'],
    category: 'Spices & Seasonings',
    servingUnit: '1 tsp (3g)',
    defaultServingG: 3,
    per100g: {
      calories: 375,
      proteinG: 17.8,
      carbsG: 44.2,
      fatG: 22.3,
      fiberG: 10.5,
      sodiumMg: 168,
      calciumMg: 931,
      ironMg: 66.4,
      potassiumMg: 1788,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
    scientificNotes: 'Stimulates pancreatic lipase and bile acid secretion for enhanced nutrient assimilation.',
    muscleSynthesisTip: 'Essential tadka foundation across all Indian lentil and veggie preps.',
  },

  // -------------------------------------------------------------
  // 7. VEGETABLES & GREENS
  // -------------------------------------------------------------
  {
    id: 'spinach-palak-raw',
    name: 'Spinach (Palak - Fresh Leaves)',
    hindiName: 'पालक (ताजी पत्तियां)',
    regionalNames: ['Pasalai Keerai', 'Palak'],
    aliases: ['palak', 'spinach', 'fresh spinach', 'palak leaves'],
    category: 'Vegetables & Greens',
    servingUnit: '1 bunch / 1 bowl (100g)',
    defaultServingG: 100,
    per100g: {
      calories: 23,
      proteinG: 2.9,
      carbsG: 3.6,
      fatG: 0.4,
      fiberG: 2.2,
      sodiumMg: 79,
      calciumMg: 99,
      ironMg: 2.7,
      potassiumMg: 558,
      leucineG: 0.22,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Rich in dietary nitrates (NO3-) which convert to nitric oxide, boosting vasodilation and muscle hyperemia.',
    muscleSynthesisTip: 'Combine with paneer (Palak Paneer) for complete muscle building meal.',
  },
  {
    id: 'fenugreek-methi-leaves',
    name: 'Fenugreek Leaves (Methi)',
    hindiName: 'मेथी (ताजा साग)',
    regionalNames: ['Vendhaya Keerai', 'Menthya'],
    aliases: ['methi', 'fenugreek leaves', 'methi leaves', 'fresh methi'],
    category: 'Vegetables & Greens',
    servingUnit: '1 bowl (100g)',
    defaultServingG: 100,
    per100g: {
      calories: 49,
      proteinG: 4.4,
      carbsG: 6.0,
      fatG: 0.9,
      fiberG: 4.5,
      sodiumMg: 67,
      calciumMg: 395,
      ironMg: 1.9,
      potassiumMg: 510,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Contains 4-hydroxyisoleucine which stimulates glucose-dependent insulin secretion.',
    muscleSynthesisTip: 'Add to besan chilla or thepla batter for improved glucose tolerance.',
  },
  {
    id: 'cauliflower-gobi',
    name: 'Cauliflower (Phool Gobi)',
    hindiName: 'फूल गोभी',
    regionalNames: ['Gobi'],
    aliases: ['gobi', 'cauliflower', 'phool gobi', 'gobhi'],
    category: 'Vegetables & Greens',
    servingUnit: '1 bowl (120g)',
    defaultServingG: 120,
    per100g: {
      calories: 25,
      proteinG: 1.9,
      carbsG: 4.9,
      fatG: 0.3,
      fiberG: 2.0,
      sodiumMg: 30,
      calciumMg: 22,
      ironMg: 0.4,
      potassiumMg: 299,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Cruciferous indole-3-carbinol supports healthy estrogen detoxification pathways.',
    muscleSynthesisTip: 'High volume, low caloric density staple for cutting phases.',
  },
  {
    id: 'bhindi-okra-cooked',
    name: 'Bhindi / Okra / Lady Finger (Sautéed)',
    hindiName: 'भिंडी (मसाला भुनी हुई)',
    regionalNames: ['Vendakkai', 'Benda Kaya', 'Bhindi'],
    aliases: ['bhindi', 'okra', 'ladyfinger', 'bhindi masala', 'stir fry okra'],
    category: 'Vegetables & Greens',
    servingUnit: '1 katori (120g)',
    defaultServingG: 120,
    per100g: {
      calories: 33,
      proteinG: 1.9,
      carbsG: 7.0,
      fatG: 0.2,
      fiberG: 3.2,
      sodiumMg: 8,
      calciumMg: 82,
      ironMg: 0.6,
      potassiumMg: 299,
    },
    glycemicIndex: { score: 20, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Mucilage fibers bind bile acids and lower systemic circulating cholesterol.',
    muscleSynthesisTip: 'Great high-fiber vegetable side to accompany protein sources.',
  },

  // -------------------------------------------------------------
  // 8. TRADITIONAL PREPARED ITEMS & CHUTNEYS
  // -------------------------------------------------------------
  {
    id: 'peanut-curd-chilly-chutney',
    name: 'Peanut Curd Chutney (Fasting / Upwas Style)',
    hindiName: 'मूंगफली-दही चटनी (उपवास स्पेशल)',
    regionalNames: ['Shengdana Dahi Chutney', 'Verkadalai Thogayal'],
    aliases: ['peanut chutney', 'peanut curd chutney', 'dahi shengdana chutney', 'fasting chutney', 'upwas chutney'],
    category: 'Traditional Prepared Items',
    servingUnit: '3 tablespoons (45g)',
    defaultServingG: 45,
    per100g: {
      calories: 220,
      proteinG: 8.5,
      carbsG: 8.0,
      fatG: 17.5,
      fiberG: 2.8,
      sodiumMg: 240,
      calciumMg: 85,
      ironMg: 1.4,
      potassiumMg: 290,
      leucineG: 0.78,
    },
    glycemicIndex: { score: 20, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Combines peanut proteins with curd probiotics. Healthy fat matrix slows gastric emptying.',
    muscleSynthesisTip: 'Standard accompaniment for Sabudana Khichdi or Rajgira Puri.',
  },
  {
    id: 'coconut-chutney-south-indian',
    name: 'South Indian Fresh Coconut Chutney (Tadka)',
    hindiName: 'नारियल की चटनी (तड़का वाली)',
    regionalNames: ['Thengai Chutney', 'Kobbari Pachadi'],
    aliases: ['coconut chutney', 'nariyal chutney', 'white coconut chutney', 'idli chutney'],
    category: 'Traditional Prepared Items',
    servingUnit: '2 tbsp (30g)',
    defaultServingG: 30,
    per100g: {
      calories: 215,
      proteinG: 3.2,
      carbsG: 7.5,
      fatG: 20.1,
      fiberG: 4.8,
      sodiumMg: 310,
      calciumMg: 20,
      ironMg: 1.2,
      potassiumMg: 210,
    },
    glycemicIndex: { score: 35, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Medium chain triglycerides (Lauric acid) provide rapid ketone and ATP substrate.',
    muscleSynthesisTip: 'Pair with steamed idli or besan chilla for healthy electrolyte balance.',
  },

  // -------------------------------------------------------------
  // 9. REGIONAL INDIAN SPECIALTIES & CLASSIC RECIPES
  // -------------------------------------------------------------
  {
    id: 'misal-pav-kolhapuri',
    name: 'Misal Pav (Spiced Sprouted Moth Bean Curry with Pav & Farsan)',
    hindiName: 'मिसळ पाव (कोल्हापुरी तर्री/रस्सा)',
    regionalNames: ['Kolhapuri Misal', 'Puneri Misal', 'Nashik Misal'],
    aliases: ['misal pav', 'misal', 'kolhapuri misal', 'sprouted matki misal', 'kat misal'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 bowl misal (250g) + 2 pav',
    defaultServingG: 300,
    per100g: {
      calories: 165,
      proteinG: 6.8,
      carbsG: 22.4,
      fatG: 5.8,
      fiberG: 3.9,
      sodiumMg: 380,
      calciumMg: 45,
      ironMg: 2.1,
      potassiumMg: 240,
      leucineG: 0.52,
    },
    glycemicIndex: { score: 48, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Sprouted moth beans (Matki) dramatically reduce phytic acid and double non-heme iron bioavailability.',
    muscleSynthesisTip: 'Pair with 100g low-fat paneer or boiled egg whites to elevate leucine to ~2.8g.',
  },
  {
    id: 'pav-bhaji-mumbai',
    name: 'Mumbai Butter Pav Bhaji',
    hindiName: 'मुंबई पाव भाजी',
    regionalNames: ['Pav Bhaji', 'Chowpatty Pav Bhaji'],
    aliases: ['pav bhaji', 'mumbai pav bhaji', 'butter pav bhaji', 'bhaji pav'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 plate (200g bhaji + 2 butter pav)',
    defaultServingG: 280,
    per100g: {
      calories: 155,
      proteinG: 4.2,
      carbsG: 21.0,
      fatG: 6.2,
      fiberG: 3.4,
      sodiumMg: 420,
      calciumMg: 38,
      ironMg: 1.6,
      potassiumMg: 285,
    },
    glycemicIndex: { score: 55, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Loaded with lycopene from cooked tomatoes and beta-carotene from carrots/capsicum.',
    muscleSynthesisTip: 'Use whole wheat pav and incorporate boiled soya granules or grated paneer into the bhaji.',
  },
  {
    id: 'vada-pav-mumbai',
    name: 'Mumbai Vada Pav with Dry Garlic Chutney',
    hindiName: 'मुंबई वड़ा पाव (लहसुन चटनी के साथ)',
    regionalNames: ['Batata Vada Pav', 'Bombay Burger'],
    aliases: ['vada pav', 'wada pav', 'batata vada pav', 'mumbai burger', 'vada pao'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 piece (140g)',
    defaultServingG: 140,
    per100g: {
      calories: 220,
      proteinG: 5.2,
      carbsG: 34.5,
      fatG: 7.2,
      fiberG: 2.8,
      sodiumMg: 390,
      calciumMg: 28,
      ironMg: 1.4,
      potassiumMg: 210,
    },
    glycemicIndex: { score: 62, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Gram flour (besan) batter provides slow-digesting resistant starch, while turmeric and mustard temper oil oxidation.',
    muscleSynthesisTip: 'Air-fry or bake the potato vada to reduce fat from 10g to under 3g per serving.',
  },
  {
    id: 'kanda-poha-maharashtrian',
    name: 'Kanda Batata Poha with Roasted Peanuts & Sev',
    hindiName: 'कांदा पोहा (मूंगफली एवं कढ़ी पत्ता तड़का)',
    regionalNames: ['Avalakki', 'Atukulu', 'Poha', 'Chuda'],
    aliases: ['poha', 'kanda poha', 'batata poha', 'flattened rice', 'onion poha', 'aval'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 plate (180g)',
    defaultServingG: 180,
    per100g: {
      calories: 148,
      proteinG: 3.8,
      carbsG: 26.2,
      fatG: 3.4,
      fiberG: 2.2,
      sodiumMg: 210,
      calciumMg: 35,
      ironMg: 2.8,
      potassiumMg: 145,
    },
    glycemicIndex: { score: 58, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Flattened parboiled rice is high in natural non-heme iron and easily digested pre-workout carbohydrates.',
    muscleSynthesisTip: 'Top with sprouted boiled moong, 50g paneer cubes, or boiled egg whites.',
  },
  {
    id: 'chole-bhature-punjabi',
    name: 'Punjabi Chole Bhature with Pickled Onions',
    hindiName: 'पंजाबी छोले भटूरे',
    regionalNames: ['Amritsari Chole Bhature', 'Chana Bhatura'],
    aliases: ['chole bhature', 'chana bhatura', 'amritsari chole', 'bhatura'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 plate (200g chole + 2 bhature)',
    defaultServingG: 320,
    per100g: {
      calories: 235,
      proteinG: 7.2,
      carbsG: 32.5,
      fatG: 8.9,
      fiberG: 4.5,
      sodiumMg: 410,
      calciumMg: 52,
      ironMg: 2.6,
      potassiumMg: 280,
      leucineG: 0.58,
    },
    glycemicIndex: { score: 59, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Chickpeas provide high lysine, prebiotic oligosaccharides, and soluble pectin fiber.',
    muscleSynthesisTip: 'Pair with baked or non-fried tandoori kulcha for high protein without oil surplus.',
  },
  {
    id: 'dal-makhani-classic',
    name: 'Authentic Dal Makhani (Black Lentils & Kidney Beans in Butter & Cream)',
    hindiName: 'दाल मखनी (शाही मक्खन दाल)',
    regionalNames: ['Maa Ki Dal', 'Bukhara Dal'],
    aliases: ['dal makhani', 'daal makhani', 'black dal', 'maa ki dal', 'punjabi dal makhani'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 bowl (200g)',
    defaultServingG: 200,
    per100g: {
      calories: 142,
      proteinG: 5.6,
      carbsG: 14.8,
      fatG: 6.9,
      fiberG: 4.2,
      sodiumMg: 320,
      calciumMg: 75,
      ironMg: 2.2,
      potassiumMg: 310,
      leucineG: 0.44,
    },
    glycemicIndex: { score: 38, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Whole black urad dal and rajma provide exceptionally high soluble viscous fiber with low postprandial insulin spike.',
    muscleSynthesisTip: 'Pair with jeera rice or whole wheat roti for complete complementary amino acid profile.',
  },
  {
    id: 'butter-chicken-murgh-makhani',
    name: 'Murgh Makhani / Butter Chicken',
    hindiName: 'मुर्ग मखनी / बटर चिकन',
    regionalNames: ['Chicken Makhani'],
    aliases: ['butter chicken', 'murgh makhani', 'chicken makhani', 'tandoori butter chicken'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 bowl (220g)',
    defaultServingG: 220,
    per100g: {
      calories: 185,
      proteinG: 14.8,
      carbsG: 5.2,
      fatG: 11.8,
      fiberG: 1.1,
      sodiumMg: 360,
      calciumMg: 42,
      ironMg: 1.4,
      potassiumMg: 290,
      leucineG: 1.25,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Tandoori-grilled chicken thighs/breast cooked in spiced tomato-cashew gravy rich in complete EAAs.',
    muscleSynthesisTip: 'Ask for tandoori breast cut with light cashew puree rather than heavy heavy cream.',
  },
  {
    id: 'palak-paneer-delight',
    name: 'Palak Paneer (Spinach Cottage Cheese Curry)',
    hindiName: 'पालक पनीर',
    regionalNames: ['Saag Paneer'],
    aliases: ['palak paneer', 'saag paneer', 'spinach paneer', 'palak panner'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 bowl (220g)',
    defaultServingG: 220,
    per100g: {
      calories: 135,
      proteinG: 8.8,
      carbsG: 4.2,
      fatG: 9.4,
      fiberG: 2.6,
      sodiumMg: 280,
      calciumMg: 240,
      ironMg: 2.1,
      potassiumMg: 340,
      leucineG: 0.82,
    },
    glycemicIndex: { score: 15, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Superb combination of spinach folate/nitrates and dairy calcium/casein.',
    muscleSynthesisTip: 'Uses low-fat paneer for 14g protein per 100g at only ~95 kcal.',
  },
  {
    id: 'masala-dosa-south-indian',
    name: 'Crispy Masala Dosa with Potato Masala & Sambar',
    hindiName: 'मसाला डोसा (सांभर एवं आलू मसाला के साथ)',
    regionalNames: ['Mysore Masala Dosa', 'Benne Dosa'],
    aliases: ['masala dosa', 'dosa', 'plain dosa', 'mysore masala dosa', 'crispy dosa', 'dosai'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 large dosa (160g) + 1 bowl sambar',
    defaultServingG: 220,
    per100g: {
      calories: 158,
      proteinG: 4.1,
      carbsG: 26.8,
      fatG: 4.0,
      fiberG: 2.4,
      sodiumMg: 290,
      calciumMg: 32,
      ironMg: 1.5,
      potassiumMg: 195,
    },
    glycemicIndex: { score: 65, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Naturally fermented rice and urad dal batter produces lactic acid bacteria and enhances B-vitamin synthesis.',
    muscleSynthesisTip: 'Order Podi Dosa with Egg or pair with 1.5 katori of thick protein-rich toor dal sambar.',
  },
  {
    id: 'idli-sambar-combo',
    name: 'Steamed Rice & Urad Dal Idli with Sambar',
    hindiName: 'इडली सांभर (भाप से पकी इडली)',
    regionalNames: ['Kanchipuram Idli', 'Thatte Idli'],
    aliases: ['idli', 'idli sambar', 'steamed idli', 'rava idli', 'idly'],
    category: 'Traditional Prepared Items',
    servingUnit: '2 large idlis (120g) + 150g sambar',
    defaultServingG: 270,
    per100g: {
      calories: 95,
      proteinG: 3.6,
      carbsG: 18.2,
      fatG: 0.8,
      fiberG: 1.9,
      sodiumMg: 210,
      calciumMg: 24,
      ironMg: 1.1,
      potassiumMg: 160,
    },
    glycemicIndex: { score: 60, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: '100% oil-free steamed breakfast. Fermentation creates light peptide chains for rapid gastric clearance.',
    muscleSynthesisTip: 'Have 3 idlis with extra thick lentil sambar and 2 boiled egg whites or 50g paneer.',
  },
  {
    id: 'hyderabadi-biryani',
    name: 'Hyderabadi Dum Biryani (Chicken / Mutton / Veg)',
    hindiName: 'हैदराबादी दम बिरयानी',
    regionalNames: ['Kolkata Biryani', 'Lucknowi Biryani', 'Malabar Biryani'],
    aliases: ['biryani', 'chicken biryani', 'veg biryani', 'dum biryani', 'mutton biryani', 'hyderabadi biryani'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 plate (300g) with cucumber raita',
    defaultServingG: 300,
    per100g: {
      calories: 175,
      proteinG: 9.6,
      carbsG: 21.5,
      fatG: 5.8,
      fiberG: 1.8,
      sodiumMg: 340,
      calciumMg: 30,
      ironMg: 1.4,
      potassiumMg: 220,
      leucineG: 0.82,
    },
    glycemicIndex: { score: 55, rating: 'Moderate (56-69)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Aged basmati rice cooked with whole spices (cinnamon, cardamom, clove, star anise) that exert insulin-sensitizing effects.',
    muscleSynthesisTip: 'Prioritize the chicken breast/thigh pieces and pair with protein-rich hung curd raita.',
  },
  {
    id: 'pani-puri-golgappa',
    name: 'Pani Puri / Golgappa / Puchka (with Mint-Tamarind Water & Spiced Ragda)',
    hindiName: 'पानी पूरी / गोलगप्पे / पुचका',
    regionalNames: ['Golgappa', 'Puchka', 'Batasha', 'Gupchup'],
    aliases: ['pani puri', 'golgappa', 'puchka', 'panipuri', 'gol gappe', 'pani ke batashe'],
    category: 'Traditional Prepared Items',
    servingUnit: '6 pieces with water & ragda (150g)',
    defaultServingG: 150,
    per100g: {
      calories: 125,
      proteinG: 2.8,
      carbsG: 24.2,
      fatG: 2.1,
      fiberG: 2.2,
      sodiumMg: 450,
      calciumMg: 20,
      ironMg: 1.8,
      potassiumMg: 170,
    },
    glycemicIndex: { score: 58, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Mint, coriander, hing (asafoetida), and black salt stimulate gastric enzyme secretion and soothe bloating.',
    muscleSynthesisTip: 'Ask for sprouted moong and black chana filling instead of deep-fried boondi.',
  },
  {
    id: 'samosa-punjabi',
    name: 'Crispy Potato & Pea Samosa with Mint & Saunth Chutney',
    hindiName: 'समोसा (आलू-मटर मसाला)',
    regionalNames: ['Singara', 'Samosa'],
    aliases: ['samosa', 'punjabi samosa', 'singara', 'aloo samosa'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 piece (90g)',
    defaultServingG: 90,
    per100g: {
      calories: 260,
      proteinG: 4.8,
      carbsG: 31.0,
      fatG: 13.5,
      fiberG: 2.6,
      sodiumMg: 380,
      calciumMg: 22,
      ironMg: 1.5,
      potassiumMg: 210,
    },
    glycemicIndex: { score: 68, rating: 'Moderate (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    scientificNotes: 'Carom seeds (ajwain) in the crust pastry activate thymol to counteract lipid stagnation.',
    muscleSynthesisTip: 'Consume air-fried or baked variant, or pair with a high-protein whey shake.',
  },

  // -------------------------------------------------------------
  // 10. GLOBAL, CONTINENTAL & ATHLETE NUTRITION STAPLES
  // -------------------------------------------------------------
  {
    id: 'grilled-salmon-asparagus',
    name: 'Pan-Seared Atlantic Salmon with Steamed Asparagus & Quinoa',
    hindiName: 'ग्रिल्ड सैल्मन मछली एवं शतावरी',
    regionalNames: ['Grilled Salmon Plate'],
    aliases: ['grilled salmon', 'salmon and asparagus', 'seared salmon', 'salmon quinoa bowl'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 plate (160g salmon + 100g asparagus + 100g quinoa)',
    defaultServingG: 360,
    per100g: {
      calories: 145,
      proteinG: 14.2,
      carbsG: 7.2,
      fatG: 6.8,
      fiberG: 1.8,
      sodiumMg: 75,
      calciumMg: 28,
      ironMg: 1.6,
      potassiumMg: 380,
      leucineG: 1.28,
    },
    glycemicIndex: { score: 25, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Unrivaled EPA and DHA Omega-3 fatty acids reduce muscle inflammation, improve cell membrane fluidity, and optimize recovery.',
    muscleSynthesisTip: 'Gold standard for muscle protein synthesis and cardiac longevity.',
  },
  {
    id: 'chipotle-chicken-burrito-bowl',
    name: 'Macro Burrito Bowl (Grilled Chicken, Brown Rice, Black Beans, Guacamole & Salsa)',
    hindiName: 'मेक्सिकन बरीटो बाउल (चिकन, बीन्स व राइस)',
    regionalNames: ['Mexican Bowl', 'Fajita Bowl'],
    aliases: ['burrito bowl', 'chipotle bowl', 'chicken burrito bowl', 'mexican rice bowl'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 large bowl (380g)',
    defaultServingG: 380,
    per100g: {
      calories: 138,
      proteinG: 11.5,
      carbsG: 14.2,
      fatG: 4.1,
      fiberG: 3.2,
      sodiumMg: 290,
      calciumMg: 35,
      ironMg: 1.8,
      potassiumMg: 310,
      leucineG: 0.95,
    },
    glycemicIndex: { score: 42, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Combines chicken EAAs, black bean soluble fiber, and avocado monounsaturated oleic acid.',
    muscleSynthesisTip: 'Optimal high-energy clean muscle building meal.',
  },
  {
    id: 'chicken-caesar-salad',
    name: 'Grilled Chicken Caesar Salad (Romaine, Shaved Parmesan & Light Dressing)',
    hindiName: 'चिकन सीज़र सलाद',
    regionalNames: ['Caesar Salad'],
    aliases: ['chicken caesar salad', 'caesar salad', 'grilled chicken salad'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 large bowl (250g)',
    defaultServingG: 250,
    per100g: {
      calories: 125,
      proteinG: 13.8,
      carbsG: 3.2,
      fatG: 6.4,
      fiberG: 1.4,
      sodiumMg: 280,
      calciumMg: 85,
      ironMg: 1.2,
      potassiumMg: 260,
      leucineG: 1.15,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'High volume, high protein, and extremely low carbohydrate profile for fat loss cutting phases.',
    muscleSynthesisTip: 'Use Greek yogurt-based Caesar dressing to save 120 kcal while adding 4g extra protein.',
  },
  {
    id: 'overnight-protein-oats',
    name: 'High-Protein Overnight Oats with Whey Isolate, Chia Seeds & Blueberries',
    hindiName: 'हाई प्रोटीन ओट्स (व्हे और चिया सीड्स)',
    regionalNames: ['Protein Oatmeal', 'Proats'],
    aliases: ['protein oats', 'overnight oats', 'proats', 'whey oats', 'chia oats'],
    category: 'Traditional Prepared Items',
    servingUnit: '1 jar (250g)',
    defaultServingG: 250,
    per100g: {
      calories: 135,
      proteinG: 12.4,
      carbsG: 16.5,
      fatG: 2.6,
      fiberG: 3.8,
      sodiumMg: 65,
      calciumMg: 140,
      ironMg: 1.8,
      potassiumMg: 210,
      leucineG: 1.35,
    },
    glycemicIndex: { score: 45, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    scientificNotes: 'Beta-glucan oat fiber slows starch breakdown while whey isolate rapidly floods systemic circulation with BCAAs.',
    muscleSynthesisTip: 'Superior pre-workout or post-workout meal with ≥3g leucine.',
  },
  {
    id: 'whey-protein-isolate-shake',
    name: 'Whey Protein Isolate Shake (1 Scoop in Water)',
    hindiName: 'व्हे प्रोटीन शेक (पानी में)',
    regionalNames: ['Protein Shake'],
    aliases: ['protein shake', 'whey protein', 'whey shake', 'isolate shake', 'whey isolate'],
    category: 'Dairy & Alternatives',
    servingUnit: '1 scoop (30g powder in 250ml water)',
    defaultServingG: 280,
    per100g: {
      calories: 42,
      proteinG: 8.8,
      carbsG: 0.4,
      fatG: 0.3,
      fiberG: 0,
      sodiumMg: 45,
      calciumMg: 50,
      ironMg: 0.2,
      potassiumMg: 55,
      leucineG: 1.05,
    },
    glycemicIndex: { score: 10, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    scientificNotes: 'Fastest known gastrointestinal absorption rate (~10g/hour) with 95%+ bioavailability (Biological Value = 104).',
    muscleSynthesisTip: 'Drink within 45 minutes of resistance training to ignite maximal ribosome biogenesis and MPS.',
  },
];

export interface CookedDishRecipe {
  id: string;
  dishName: string;
  hindiOrRegionalName: string;
  regionOrCuisine: 'Maharashtra' | 'North India / Punjab' | 'South India' | 'Gujarat & Rajasthan' | 'East India & Bengal' | 'Central / Hyderabad' | 'Coastal & Goa' | 'Worldwide / Continental' | 'Athlete & Fitness Staple';
  category: 'Breakfast' | 'Lunch / Dinner' | 'Snack / Appetizer' | 'Beverage / Digestive' | 'Vrat / Fasting';
  defaultServingDescription: string;
  defaultServingGrams: number;
  perServingMacros: {
    calories: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    fiberG: number;
    sodiumMg?: number;
    calciumMg?: number;
    potassiumMg?: number;
    ironMg?: number;
    leucineG?: number;
  };
  keyIngredients: Array<{
    name: string;
    weightG: number;
    isPrimaryProtein?: boolean;
    scientificRole?: string;
  }>;
  cookingMethod: string;
  oilFatAbsorptionRatePct: number;
  glycemicIndex: { score: number; rating: 'Low (<55)' | 'Medium (56-69)' | 'High (70+)' };
  isVegetarian: boolean;
  isVegan: boolean;
  isFastingSafe: boolean;
  dietaryHacksForFatLossOrMuscle: string;
  aliases: string[];
}

export const WORLDWIDE_AND_INDIAN_RECIPES_DATABASE: CookedDishRecipe[] = [
  // MAHARASHTRA
  {
    id: 'sabudana-khichdi-authentic',
    dishName: 'Sabudana Khichdi',
    hindiOrRegionalName: 'साबुदाणा खिचडी (साबूदाना)',
    regionOrCuisine: 'Maharashtra',
    category: 'Vrat / Fasting',
    defaultServingDescription: '1 medium bowl (180g cooked)',
    defaultServingGrams: 180,
    perServingMacros: {
      calories: 385,
      proteinG: 6.2,
      carbsG: 64.0,
      fatG: 12.5,
      fiberG: 2.8,
      sodiumMg: 240,
      calciumMg: 35,
      potassiumMg: 195,
      ironMg: 1.4,
    },
    keyIngredients: [
      { name: 'Soaked Tapioca Pearls (Sabudana)', weightG: 100 },
      { name: 'Roasted Crushed Peanuts (Shengdana Kut)', weightG: 30, isPrimaryProtein: true },
      { name: 'Boiled Potato Cubes', weightG: 35 },
      { name: 'Pure Desi Ghee / Groundnut Oil', weightG: 10 },
      { name: 'Green Chillies & Cumin (Jeera)', weightG: 5 },
    ],
    cookingMethod: 'Tempered in ghee with cumin seeds and slit green chillies, tossed with peanut powder until pearls turn translucent.',
    oilFatAbsorptionRatePct: 95,
    glycemicIndex: { score: 72, rating: 'High (70+)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
    dietaryHacksForFatLossOrMuscle: 'Pair with 150g low-fat hung curd (Greek style) to increase protein to 20g and lower glycemic response.',
    aliases: ['sabudana khichdi', 'sabudana', 'sago khichdi', 'vrat ki khichdi', 'tapioca pearl khichdi', 'maharashtrian sabudana'],
  },
  {
    id: 'kanda-poha-authentic',
    dishName: 'Kanda Batata Poha',
    hindiOrRegionalName: 'कांदे पोहे (कांदा बटाटा पोहा)',
    regionOrCuisine: 'Maharashtra',
    category: 'Breakfast',
    defaultServingDescription: '1 plate (200g)',
    defaultServingGrams: 200,
    perServingMacros: {
      calories: 295,
      proteinG: 5.8,
      carbsG: 48.2,
      fatG: 9.4,
      fiberG: 3.5,
      sodiumMg: 310,
      calciumMg: 42,
      potassiumMg: 210,
      ironMg: 3.8,
    },
    keyIngredients: [
      { name: 'Flattened Rice (Poha - rinsed)', weightG: 110 },
      { name: 'Sliced Onions (Kanda)', weightG: 40 },
      { name: 'Diced Boiled Potato (Batata)', weightG: 30 },
      { name: 'Roasted Peanuts', weightG: 15, isPrimaryProtein: true },
      { name: 'Mustard Seeds, Turmeric, Curry Leaves, Lemon', weightG: 5 },
    ],
    cookingMethod: 'Steam softened flattened rice tempered with mustard, turmeric, green chillies, curry leaves, and crunchy peanuts.',
    oilFatAbsorptionRatePct: 88,
    glycemicIndex: { score: 64, rating: 'Medium (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Top with 50g boiled moong sprouts or 80g roasted paneer cubes to boost total meal protein to 16g+.',
    aliases: ['kanda poha', 'batata poha', 'poha', 'flattened rice', 'pohe', 'maharashtrian poha', 'kande pohe'],
  },
  {
    id: 'misal-pav-authentic',
    dishName: 'Kolhapuri Misal Pav',
    hindiOrRegionalName: 'मिसळ पाव (कोल्हापुरी / पुणेरी मिसळ)',
    regionOrCuisine: 'Maharashtra',
    category: 'Breakfast',
    defaultServingDescription: '1 bowl misal curry + 2 ladipavs (280g total)',
    defaultServingGrams: 280,
    perServingMacros: {
      calories: 490,
      proteinG: 14.5,
      carbsG: 72.0,
      fatG: 16.0,
      fiberG: 8.5,
      sodiumMg: 680,
      calciumMg: 85,
      potassiumMg: 420,
      ironMg: 4.6,
    },
    keyIngredients: [
      { name: 'Sprouted Moth Beans (Matki Usal)', weightG: 120, isPrimaryProtein: true },
      { name: 'Spicy Kat / Rassa (Onion-Coconut-Kanda Lasun Gravy)', weightG: 80 },
      { name: 'Farsan / Sev Topping', weightG: 30 },
      { name: 'Ladi Pav (2 buns)', weightG: 50 },
    ],
    cookingMethod: 'Sprouted matki cooked with roasted onion-coconut paste and fiery Kolhapuri masala, topped with spicy tari rassa and farsan.',
    oilFatAbsorptionRatePct: 85,
    glycemicIndex: { score: 68, rating: 'Medium (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Substitute half the farsan with boiled sprouts and replace white pav with 2 whole wheat rotis or bhakri.',
    aliases: ['misal pav', 'kolhapuri misal', 'puneri misal', 'matki misal', 'misal', 'usal pav'],
  },
  {
    id: 'pitla-bhakri-authentic',
    dishName: 'Pithla Bhakri with Thecha',
    hindiOrRegionalName: 'झुणका / पिठलं भाकरी आणि ठेचा',
    regionOrCuisine: 'Maharashtra',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl pithla (150g) + 1 jowar bhakri (80g)',
    defaultServingGrams: 230,
    perServingMacros: {
      calories: 365,
      proteinG: 13.8,
      carbsG: 58.0,
      fatG: 8.5,
      fiberG: 9.2,
      sodiumMg: 380,
      calciumMg: 65,
      potassiumMg: 390,
      ironMg: 4.2,
    },
    keyIngredients: [
      { name: 'Besan (Bengal Gram Flour)', weightG: 45, isPrimaryProtein: true },
      { name: 'Jowar / Bajra Flour (Bhakri)', weightG: 60 },
      { name: 'Onions, Garlic, Green Chillies, Mustard, Coriander', weightG: 20 },
      { name: 'Groundnut Oil / Ghee', weightG: 8 },
    ],
    cookingMethod: 'Gram flour whisked with spiced water and tempered with crushed garlic, green chillies, and cumin, served with unleavened sorghum flatbread.',
    oilFatAbsorptionRatePct: 90,
    glycemicIndex: { score: 48, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Exceptional slow-digesting complex carb and plant protein profile with high satiety and prebiotic fiber.',
    aliases: ['pithla bhakri', 'pitla bhakri', 'zhunka bhakri', 'zunka bhakar', 'besan pithla', 'jowar bhakri'],
  },
  {
    id: 'varan-bhaat-toop',
    dishName: 'Varan Bhaat with Desi Ghee & Lemon',
    hindiOrRegionalName: 'वरण भात आणि साजूक तूप लिंबू',
    regionOrCuisine: 'Maharashtra',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl toor dal varan (150g) + 1 cup steamed rice (150g) + 1 tsp ghee',
    defaultServingGrams: 305,
    perServingMacros: {
      calories: 380,
      proteinG: 11.2,
      carbsG: 66.0,
      fatG: 7.5,
      fiberG: 5.4,
      sodiumMg: 280,
      calciumMg: 38,
      potassiumMg: 340,
      ironMg: 2.8,
    },
    keyIngredients: [
      { name: 'Cooked Toor / Arhar Dal', weightG: 150, isPrimaryProtein: true },
      { name: 'Steamed Indrayani / Sona Masoori Rice', weightG: 150 },
      { name: 'Pure Cow Desi Ghee (Sajuk Toop)', weightG: 5 },
      { name: 'Turmeric, Salt, Fresh Lemon Juice', weightG: 5 },
    ],
    cookingMethod: 'Pressure cooked toor dal seasoned minimally with turmeric and salt, served over piping hot steamed rice with a drizzle of pure cow ghee.',
    oilFatAbsorptionRatePct: 100,
    glycemicIndex: { score: 58, rating: 'Medium (56-69)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Complete amino acid complementary profile (lysine from dal + methionine from rice). Pair with 100g roasted paneer for high protein.',
    aliases: ['varan bhaat', 'varan bhat', 'dal chawal maharashtrian', 'toor dal rice', 'varan toop bhaat'],
  },

  // NORTH INDIA & PUNJAB
  {
    id: 'paneer-butter-masala-authentic',
    dishName: 'Paneer Butter Masala',
    hindiOrRegionalName: 'पनीर बटर मसाला',
    regionOrCuisine: 'North India / Punjab',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 portion (220g)',
    defaultServingGrams: 220,
    perServingMacros: {
      calories: 420,
      proteinG: 17.5,
      carbsG: 14.0,
      fatG: 32.5,
      fiberG: 3.2,
      sodiumMg: 520,
      calciumMg: 380,
      potassiumMg: 310,
      ironMg: 1.8,
      leucineG: 1.6,
    },
    keyIngredients: [
      { name: 'Fresh Malai Paneer Cubes', weightG: 120, isPrimaryProtein: true },
      { name: 'Tomato Cashew Makhani Gravy', weightG: 80 },
      { name: 'Butter & Fresh Cream', weightG: 15 },
      { name: 'Kasuri Methi & Garam Masala', weightG: 5 },
    ],
    cookingMethod: 'Soft paneer simmered in silky puree of slow-cooked tomatoes, soaked cashews, butter, and fragrant fenugreek leaves.',
    oilFatAbsorptionRatePct: 90,
    glycemicIndex: { score: 32, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'For fat loss, substitute cream with low-fat hung curd (chakka) and use 1% low-fat paneer to cut calories by 180 kcal while maintaining 24g protein.',
    aliases: ['paneer butter masala', 'paneer makhani', 'butter paneer', 'shahi paneer', 'paneer gravy'],
  },
  {
    id: 'dal-makhani-slowcooked',
    dishName: 'Dal Makhani (Slow-Cooked Punjabi)',
    hindiOrRegionalName: 'दाल मखनी (उड़द राजमा)',
    regionOrCuisine: 'North India / Punjab',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl (200g)',
    defaultServingGrams: 200,
    perServingMacros: {
      calories: 310,
      proteinG: 12.8,
      carbsG: 32.0,
      fatG: 14.5,
      fiberG: 7.8,
      sodiumMg: 460,
      calciumMg: 140,
      potassiumMg: 490,
      ironMg: 3.9,
    },
    keyIngredients: [
      { name: 'Whole Black Urad Dal & Kidney Beans (Rajma)', weightG: 140, isPrimaryProtein: true },
      { name: 'Butter, Cream & Desi Ghee', weightG: 15 },
      { name: 'Tomato Puree, Ginger, Garlic, Kashmiri Mirch', weightG: 45 },
    ],
    cookingMethod: 'Slow simmered for 8+ hours on low flame with tomato puree, white butter, and gentle spices until unctuous.',
    oilFatAbsorptionRatePct: 90,
    glycemicIndex: { score: 42, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'High soluble prebiotic fiber content. Ask for home-style (tadka without heavy cream) to reduce fat by 60%.',
    aliases: ['dal makhani', 'daal makhni', 'makhani dal', 'maa ki dal', 'punjabi dal makhani'],
  },
  {
    id: 'rajma-chawal-punjabi',
    dishName: 'Punjabi Rajma Chawal',
    hindiOrRegionalName: 'राजमा चावल',
    regionOrCuisine: 'North India / Punjab',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl rajma (180g) + 1 cup basmati rice (150g)',
    defaultServingGrams: 330,
    perServingMacros: {
      calories: 435,
      proteinG: 15.6,
      carbsG: 76.0,
      fatG: 7.2,
      fiberG: 9.8,
      sodiumMg: 490,
      calciumMg: 78,
      potassiumMg: 620,
      ironMg: 4.8,
    },
    keyIngredients: [
      { name: 'Boiled Red Kidney Beans (Rajma)', weightG: 120, isPrimaryProtein: true },
      { name: 'Onion-Tomato-Ginger-Garlic Masala Gravy', weightG: 60 },
      { name: 'Steamed Long-Grain Basmati Rice', weightG: 150 },
    ],
    cookingMethod: 'Chitra rajma pressure cooked until melt-in-mouth soft, simmered in thick spiced onion-tomato bhuna masala.',
    oilFatAbsorptionRatePct: 85,
    glycemicIndex: { score: 54, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Rich in potassium and resistant starch. Excellent post-workout recovery meal for glycogen and muscle protein synthesis.',
    aliases: ['rajma chawal', 'rajma', 'punjabi rajma', 'kidney beans rice', 'rajma curry'],
  },
  {
    id: 'chole-bhature-punjabi',
    dishName: 'Amritsari Chole Bhature',
    hindiOrRegionalName: 'अमृतसरी छोले भटूरे',
    regionOrCuisine: 'North India / Punjab',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl chole (180g) + 2 bhature (120g)',
    defaultServingGrams: 300,
    perServingMacros: {
      calories: 680,
      proteinG: 18.2,
      carbsG: 88.0,
      fatG: 28.5,
      fiberG: 11.2,
      sodiumMg: 740,
      calciumMg: 110,
      potassiumMg: 580,
      ironMg: 5.6,
    },
    keyIngredients: [
      { name: 'Kabuli Chickpeas (Chole)', weightG: 130, isPrimaryProtein: true },
      { name: 'Amritsari Anardana Chole Masala Gravy', weightG: 50 },
      { name: 'Fried Leavened Maida Bhature (2 pcs)', weightG: 120 },
    ],
    cookingMethod: 'Dark spiced chickpeas simmered with dried pomegranate seeds and tea leaf infusion, served with crispy puffed fried flatbread.',
    oilFatAbsorptionRatePct: 92,
    glycemicIndex: { score: 68, rating: 'Medium (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Switch bhature for 2 whole wheat tandoori rotis or kulcha to cut 240 kcal and 18g fat.',
    aliases: ['chole bhature', 'chana bhatura', 'amritsari chole', 'chickpea curry with fried bread'],
  },
  {
    id: 'butter-chicken-murgh-makhani',
    dishName: 'Murgh Makhani / Butter Chicken',
    hindiOrRegionalName: 'मुर्ग मखनी / बटर चिकन',
    regionOrCuisine: 'North India / Punjab',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 portion with chicken breast/thigh (220g)',
    defaultServingGrams: 220,
    perServingMacros: {
      calories: 460,
      proteinG: 34.0,
      carbsG: 10.5,
      fatG: 31.0,
      fiberG: 2.1,
      sodiumMg: 580,
      calciumMg: 65,
      potassiumMg: 440,
      ironMg: 2.2,
      leucineG: 2.9,
    },
    keyIngredients: [
      { name: 'Tandoori Grilled Boneless Chicken Breast', weightG: 140, isPrimaryProtein: true },
      { name: 'Rich Makhani Tomato Cashew Sauce', weightG: 65 },
      { name: 'Butter, Cream, Kasuri Methi', weightG: 15 },
    ],
    cookingMethod: 'Tandoor-charred chicken pieces folded into spiced velvety tomato-cream reduction.',
    oilFatAbsorptionRatePct: 88,
    glycemicIndex: { score: 25, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Pure chicken breast provides an impressive 34g anabolic protein. Request light butter/cream for high-protein cutting.',
    aliases: ['butter chicken', 'murgh makhani', 'chicken makhani', 'butter murgh'],
  },

  // SOUTH INDIA
  {
    id: 'masala-dosa-mysore',
    dishName: 'Mysore Masala Dosa with Chutney & Sambar',
    hindiOrRegionalName: 'मैसूर मसाला डोसा',
    regionOrCuisine: 'South India',
    category: 'Breakfast',
    defaultServingDescription: '1 large crispy dosa (150g) + potato palya (80g) + sambar/chutney (100g)',
    defaultServingGrams: 330,
    perServingMacros: {
      calories: 395,
      proteinG: 9.4,
      carbsG: 64.0,
      fatG: 11.8,
      fiberG: 5.2,
      sodiumMg: 540,
      calciumMg: 45,
      potassiumMg: 310,
      ironMg: 2.4,
    },
    keyIngredients: [
      { name: 'Fermented Rice & Urad Dal Batter Dosa', weightG: 140 },
      { name: 'Spiced Potato Onion Mash (Aloo Palya)', weightG: 80 },
      { name: 'Lentil Vegetable Sambar', weightG: 80, isPrimaryProtein: true },
      { name: 'Coconut Chutney', weightG: 30 },
    ],
    cookingMethod: 'Crisped on cast-iron tawa with sesame oil/ghee, smeared with red garlic-chilli chutney and stuffed with seasoned potato.',
    oilFatAbsorptionRatePct: 85,
    glycemicIndex: { score: 62, rating: 'Medium (56-69)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Consume double bowl of toor-dal rich sambar to elevate protein to 16g+.',
    aliases: ['masala dosa', 'mysore masala dosa', 'dosa', 'dosai', 'aloo dosa', 'crispy dosa'],
  },
  {
    id: 'idli-sambar-authentic',
    dishName: 'Steamed Idli Sambar (3 Idlis + Sambar)',
    hindiOrRegionalName: 'इडली सांभर',
    regionOrCuisine: 'South India',
    category: 'Breakfast',
    defaultServingDescription: '3 steamed idlis (150g) + 1 bowl vegetable sambar (150g)',
    defaultServingGrams: 300,
    perServingMacros: {
      calories: 275,
      proteinG: 9.8,
      carbsG: 52.0,
      fatG: 2.8,
      fiberG: 6.2,
      sodiumMg: 420,
      calciumMg: 52,
      potassiumMg: 340,
      ironMg: 2.6,
    },
    keyIngredients: [
      { name: 'Fermented Steamed Idli (Parboiled Rice + Urad Dal)', weightG: 150 },
      { name: 'Toor Dal & Drumstick Vegetable Sambar', weightG: 150, isPrimaryProtein: true },
    ],
    cookingMethod: 'Steam-cooked fermented probiotic cakes served swimming in piping hot tamarind-lentil vegetable broth.',
    oilFatAbsorptionRatePct: 30,
    glycemicIndex: { score: 55, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Virtually zero added oil (under 3g fat). Add 1 boiled egg or 50g paneer for a complete 22g protein breakfast.',
    aliases: ['idli sambar', 'idli', 'steamed idli', 'idly', 'idli sambhar', 'south indian idli'],
  },
  {
    id: 'hyderabadi-chicken-dum-biryani',
    dishName: 'Hyderabadi Chicken Dum Biryani',
    hindiOrRegionalName: 'हैदराबादी चिकन दम बिरयानी',
    regionOrCuisine: 'Central / Hyderabad',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 full portion (350g cooked)',
    defaultServingGrams: 350,
    perServingMacros: {
      calories: 560,
      proteinG: 36.5,
      carbsG: 65.0,
      fatG: 17.5,
      fiberG: 3.8,
      sodiumMg: 690,
      calciumMg: 55,
      potassiumMg: 510,
      ironMg: 3.4,
      leucineG: 3.1,
    },
    keyIngredients: [
      { name: 'Marinated Bone-in / Boneless Chicken Pieces', weightG: 160, isPrimaryProtein: true },
      { name: 'Aromatic Aged Basmati Rice (Layered with Saffron)', weightG: 170 },
      { name: 'Fried Onions (Birista), Mint, Ghee, Shahi Masala', weightG: 20 },
    ],
    cookingMethod: 'Raw marinated chicken sealed under handi with partially cooked long-grain rice and slow-steamed on dum with charcoal heat.',
    oilFatAbsorptionRatePct: 90,
    glycemicIndex: { score: 58, rating: 'Medium (56-69)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Pairs 36.5g complete bioavailable protein with easily digestible carbohydrates for pre/post-workout athletic fueling.',
    aliases: ['chicken biryani', 'hyderabadi biryani', 'dum biryani', 'chicken dum biryani', 'biryani'],
  },

  // WORLDWIDE / CONTINENTAL & ATHLETE STAPLES
  {
    id: 'grilled-salmon-quinoa-bowl',
    dishName: 'Grilled Atlantic Salmon & Quinoa Bowl',
    hindiOrRegionalName: 'ग्रिल्ड साल्मन और क्विनोआ बाउल',
    regionOrCuisine: 'Worldwide / Continental',
    category: 'Lunch / Dinner',
    defaultServingDescription: '1 bowl (320g)',
    defaultServingGrams: 320,
    perServingMacros: {
      calories: 485,
      proteinG: 38.0,
      carbsG: 34.0,
      fatG: 21.0,
      fiberG: 5.5,
      sodiumMg: 380,
      calciumMg: 45,
      potassiumMg: 720,
      ironMg: 3.2,
      leucineG: 3.4,
    },
    keyIngredients: [
      { name: 'Wild-Caught Atlantic Salmon Fillet', weightG: 150, isPrimaryProtein: true },
      { name: 'Cooked Tricolor Quinoa', weightG: 100 },
      { name: 'Steamed Asparagus & Baby Spinach', weightG: 60 },
      { name: 'Extra Virgin Olive Oil & Lemon', weightG: 10 },
    ],
    cookingMethod: 'Pan-seared on high heat with sea salt, cracked black pepper, and lemon zest, rested over fluffy cooked quinoa.',
    oilFatAbsorptionRatePct: 80,
    glycemicIndex: { score: 35, rating: 'Low (<55)' },
    isVegetarian: false,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Supreme source of anti-inflammatory Omega-3 fatty acids (EPA/DHA) and high biological value complete protein.',
    aliases: ['grilled salmon', 'salmon bowl', 'salmon with quinoa', 'salmon fillet'],
  },
  {
    id: 'whey-isolate-overnight-oats',
    dishName: 'Whey Isolate Overnight Protein Oats',
    hindiOrRegionalName: 'हाई-प्रोटीन ओवरनाइट ओट्स',
    regionOrCuisine: 'Athlete & Fitness Staple',
    category: 'Breakfast',
    defaultServingDescription: '1 jar (300g)',
    defaultServingGrams: 300,
    perServingMacros: {
      calories: 395,
      proteinG: 36.0,
      carbsG: 46.0,
      fatG: 6.5,
      fiberG: 7.5,
      sodiumMg: 160,
      calciumMg: 320,
      potassiumMg: 440,
      ironMg: 3.1,
      leucineG: 3.8,
    },
    keyIngredients: [
      { name: 'Rolled Oats (Old Fashioned)', weightG: 50 },
      { name: '100% Whey Protein Isolate (Chocolate/Vanilla)', weightG: 30, isPrimaryProtein: true },
      { name: 'Unsweetened Almond Milk / Skim Milk', weightG: 180 },
      { name: 'Chia Seeds & Fresh Blueberries', weightG: 40 },
    ],
    cookingMethod: 'No-cook cold steep overnight in refrigerator for gradual oat starch gelatinization and sustained amino acid delivery.',
    oilFatAbsorptionRatePct: 10,
    glycemicIndex: { score: 45, rating: 'Low (<55)' },
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: false,
    dietaryHacksForFatLossOrMuscle: 'Top-tier bodybuilder breakfast with 3.8g Leucine to trigger maximal muscle protein synthesis.',
    aliases: ['protein oats', 'overnight oats', 'whey oats', 'proats', 'protein oatmeal'],
  },
];

/**
 * Search helper for worldwide & regional Indian recipes
 */
export function searchWorldwideAndIndianRecipes(
  query: string,
  regionFilter?: string
): CookedDishRecipe[] {
  const normalized = query.trim().toLowerCase();
  return WORLDWIDE_AND_INDIAN_RECIPES_DATABASE.filter((dish) => {
    if (regionFilter && regionFilter !== 'All' && dish.regionOrCuisine !== regionFilter) {
      return false;
    }
    if (!normalized) return true;
    return (
      dish.dishName.toLowerCase().includes(normalized) ||
      dish.hindiOrRegionalName.toLowerCase().includes(normalized) ||
      dish.aliases.some((a) => a.toLowerCase().includes(normalized)) ||
      dish.keyIngredients.some((i) => i.name.toLowerCase().includes(normalized))
    );
  });
}

/**
 * Find best matching cooked recipe
 */
export function findBestMatchingRecipe(dishNameOrQuery: string): CookedDishRecipe | undefined {
  const q = dishNameOrQuery.trim().toLowerCase();
  if (!q) return undefined;

  const exact = WORLDWIDE_AND_INDIAN_RECIPES_DATABASE.find(
    (dish) =>
      dish.id === q ||
      dish.dishName.toLowerCase() === q ||
      dish.aliases.some((a) => a.toLowerCase() === q)
  );
  if (exact) return exact;

  return WORLDWIDE_AND_INDIAN_RECIPES_DATABASE.find(
    (dish) =>
      dish.dishName.toLowerCase().includes(q) ||
      dish.aliases.some((a) => a.toLowerCase().includes(q) || q.includes(a.toLowerCase()))
  );
}

/**
 * Search helper for Indian ingredients
 */
export function searchIndianIngredients(
  query: string, 
  categoryFilter?: string
): IndianIngredient[] {
  const normalizedQuery = query.trim().toLowerCase();
  
  return INDIAN_NUTRITION_DATABASE.filter((item) => {
    if (categoryFilter && categoryFilter !== 'All' && item.category !== categoryFilter) {
      return false;
    }
    if (!normalizedQuery) return true;

    return (
      item.name.toLowerCase().includes(normalizedQuery) ||
      item.hindiName.toLowerCase().includes(normalizedQuery) ||
      item.aliases.some((alias) => alias.toLowerCase().includes(normalizedQuery)) ||
      (item.regionalNames && item.regionalNames.some((r) => r.toLowerCase().includes(normalizedQuery))) ||
      item.category.toLowerCase().includes(normalizedQuery)
    );
  });
}

/**
 * Find exact or closest match by query string
 */
export function findBestMatchingIndianIngredient(nameOrQuery: string): IndianIngredient | undefined {
  const q = nameOrQuery.trim().toLowerCase();
  if (!q) return undefined;

  // 1. Exact alias match
  const exact = INDIAN_NUTRITION_DATABASE.find(
    (item) => 
      item.id === q ||
      item.name.toLowerCase() === q || 
      item.aliases.some((a) => a.toLowerCase() === q)
  );
  if (exact) return exact;

  // 2. Partial word match
  return INDIAN_NUTRITION_DATABASE.find(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      item.aliases.some((a) => a.toLowerCase().includes(q) || q.includes(a.toLowerCase()))
  );
}

/**
 * Calculate precise macronutrients for any gram weight
 */
export function calculateIngredientMacros(ingredient: IndianIngredient, grams: number) {
  const factor = grams / 100;
  return {
    grams,
    calories: Math.round(ingredient.per100g.calories * factor),
    proteinG: Number((ingredient.per100g.proteinG * factor).toFixed(1)),
    carbsG: Number((ingredient.per100g.carbsG * factor).toFixed(1)),
    fatG: Number((ingredient.per100g.fatG * factor).toFixed(1)),
    fiberG: Number((ingredient.per100g.fiberG * factor).toFixed(1)),
    sodiumMg: Math.round((ingredient.per100g.sodiumMg || 0) * factor),
    calciumMg: Math.round((ingredient.per100g.calciumMg || 0) * factor),
    ironMg: Number(((ingredient.per100g.ironMg || 0) * factor).toFixed(1)),
    potassiumMg: Math.round((ingredient.per100g.potassiumMg || 0) * factor),
    leucineG: ingredient.per100g.leucineG 
      ? Number((ingredient.per100g.leucineG * factor).toFixed(2)) 
      : undefined,
  };
}
