import { WorkoutProgram, UserProfile, MealLog, BodyMetric, WorkoutCompletionLog } from '../types';

export const SAMPLE_WORKOUT_PROGRAMS: WorkoutProgram[] = [
  {
    id: 'upper-lower-4day',
    title: '4-Day Science-Based Upper / Lower Split',
    description: 'Optimal training frequency (2x/week per muscle group) for maximum muscle protein synthesis and fat loss with progressive overload tracking.',
    splitType: 'Upper/Lower',
    daysPerWeek: 4,
    scientificPhilosophy: 'Research demonstrates hitting each muscle group twice weekly maximizes MPS (Brad Schoenfeld et al.) with higher volume recovery than traditional bro-splits.',
    days: [
      {
        id: 'upper-1',
        dayName: 'Upper Body A (Power & Chest/Lat Emphasis)',
        dayOfWeek: 'Monday',
        focus: 'Chest, Upper Back, Lats, Shoulders, Arms',
        durationMin: 55,
        exercises: [
          {
            id: 'ex-incline-db-bench',
            name: 'Incline Dumbbell Bench Press (30° Angle)',
            targetMuscle: 'Upper Chest (Clavicular Head)',
            secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
            equipment: 'Dumbbells, Incline Bench',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8,
            restSeconds: 120,
            scienceTip: 'A 30-degree incline provides peak EMG activation of the clavicular pec without excessive anterior delt dominance.',
            emgFocus: '+34% Clavicular Head activation vs flat bench',
            injuryAlternative: {
              originalExercise: 'Incline Dumbbell Bench Press',
              substitute: 'Low-to-High Cable Crossover or Neutral Grip DB Press',
              reason: 'Removes shoulder impingement torque while keeping upper chest tension.',
            },
          },
          {
            id: 'ex-chest-supported-row',
            name: 'Chest-Supported Neutral T-Bar Row',
            targetMuscle: 'Upper Back (Rhomboids, Mid-Traps)',
            secondaryMuscles: ['Biceps', 'Rear Delts'],
            equipment: 'T-Bar Machine or Incline Bench + Dumbbells',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Chest support eliminates spinal loading, isolating the rhomboids and mid-trapezius for safe progressive overload.',
            emgFocus: '90% Upper back recruitment with zero lumbar shear',
          },
          {
            id: 'ex-lat-pulldown',
            name: 'Half-Kneeling Lat Pulldown or Single-Arm Pulldown',
            targetMuscle: 'Lats (Iliac & Thoracic Fibers)',
            secondaryMuscles: ['Biceps', 'Brachialis'],
            equipment: 'Cable Machine',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Drive elbows down towards the hip pockets rather than pulling flared back to align with lat fiber orientation.',
            emgFocus: 'Maximum Lat lengthening in the eccentric phase',
          },
          {
            id: 'ex-cable-lateral-raise',
            name: 'Cross-Body Cable Lateral Raise (Wrist Height)',
            targetMuscle: 'Side Deltoids (Lateral Head)',
            secondaryMuscles: ['Trapezius'],
            equipment: 'Cable Machine',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Cables provide constant resistance in the stretched position where dumbbells have near-zero resistance.',
            emgFocus: 'Constant resistance profile throughout entire 120° ROM',
          },
          {
            id: 'ex-overhead-cable-triceps',
            name: 'Overhead Cable Triceps Extension',
            targetMuscle: 'Triceps (Long Head)',
            secondaryMuscles: [],
            equipment: 'Cable Machine + Rope',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Placing the shoulder in flexion stretches the long head, inducing stretch-mediated hypertrophy.',
            emgFocus: '1.5x greater long head hypertrophy vs pushdowns (Maeo et al. 2023)',
          },
        ],
      },
      {
        id: 'lower-1',
        dayName: 'Lower Body A (Quad & Glute Focus)',
        dayOfWeek: 'Tuesday',
        focus: 'Quadriceps, Glutes, Hamstrings, Calves',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-bulgarian-split-squat',
            name: 'Bulgarian Split Squat (Deficit)',
            targetMuscle: 'Quadriceps & Gluteus Maximus',
            secondaryMuscles: ['Adductors', 'Hamstrings'],
            equipment: 'Dumbbells + Bench',
            sets: 3,
            reps: '8-10 reps / leg',
            rpeTarget: 8.5,
            restSeconds: 120,
            scienceTip: 'Elevating front foot on a 2-inch plate allows deeper hip flexion and full stretch under load.',
            emgFocus: 'Superior unilateral stabilizer recruitment vs bilateral back squat',
            injuryAlternative: {
              originalExercise: 'Barbell Back Squat',
              substitute: 'Leg Press with High/Wide Foot Placement or Hack Squat',
              reason: 'Completely unloads the lumbar spine for lower back safety.',
            },
          },
          {
            id: 'ex-romanian-deadlift',
            name: 'Dumbbell / Trap Bar Romanian Deadlift',
            targetMuscle: 'Hamstrings (Semitendinosus/Biceps Femoris) & Glutes',
            secondaryMuscles: ['Erector Spinae', 'Lats'],
            equipment: 'Dumbbells or Barbell',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 120,
            scienceTip: 'Focus on pushing the hips backward like touching a wall behind you until a deep hamstring stretch is reached.',
            emgFocus: 'Maximum hamstring elongation under tension',
          },
          {
            id: 'ex-seated-leg-curl',
            name: 'Seated Leg Curl',
            targetMuscle: 'Hamstrings (All 4 heads)',
            secondaryMuscles: ['Calves'],
            equipment: 'Seated Leg Curl Machine',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'Seated leg curls stretch hamstrings at the hip, yielding ~1.8x greater muscle growth than lying leg curls.',
            emgFocus: 'Stretch-mediated hypertrophy (Schoenfeld & Maeo 2021)',
          },
          {
            id: 'ex-standing-calf-raise',
            name: 'Single-Leg Standing Calf Raise (3s Pause at Bottom)',
            targetMuscle: 'Gastrocnemius & Soleus',
            secondaryMuscles: [],
            equipment: 'Dumbbell + Step',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Pausing 3 seconds at the bottom dissipates Achilles tendon elastic recoil, forcing active muscle recruitment.',
            emgFocus: 'Eliminates stretch-shortening cycle bounce',
          },
        ],
      },
      {
        id: 'upper-2',
        dayName: 'Upper Body B (Hypertrophy & Shoulders/Arms)',
        dayOfWeek: 'Thursday',
        focus: 'Chest, Mid/Upper Back, Deltoids, Biceps',
        durationMin: 55,
        exercises: [
          {
            id: 'ex-flat-cable-flye',
            name: 'Seated Converging Machine / Cable Chest Press',
            targetMuscle: 'Mid & Sternal Pectoralis',
            secondaryMuscles: ['Triceps', 'Anterior Delt'],
            equipment: 'Machine / Cable',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Converging path matches the natural horizontal adduction path of the pectoral fibers.',
            emgFocus: 'Peak contraction at full horizontal adduction',
          },
          {
            id: 'ex-seated-cable-row',
            name: 'Wide-Grip Cable Row (Elbows at 45°)',
            targetMuscle: 'Rear Delts, Rhomboids, Traps',
            secondaryMuscles: ['Biceps'],
            equipment: 'Cable Row Machine',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Keep elbows flared at 45 degrees to target upper back rather than lats.',
            emgFocus: 'Maximum rhomboid retraction and rear delt engagement',
          },
          {
            id: 'ex-incline-db-curl',
            name: 'Incline Dumbbell Biceps Curl',
            targetMuscle: 'Biceps Brachii (Long Head)',
            secondaryMuscles: ['Brachialis', 'Forearms'],
            equipment: 'Incline Bench + Dumbbells',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'Shoulder extension at the bottom stretches the long head across both shoulder and elbow joints.',
            emgFocus: 'Peak stretch at the glenohumeral joint',
          },
          {
            id: 'ex-face-pull',
            name: 'Cable Face Pull with External Rotation',
            targetMuscle: 'Rear Delts, Infraspinatus, Rotator Cuff',
            secondaryMuscles: ['Traps'],
            equipment: 'Cable + Rope',
            sets: 3,
            reps: '15-20 reps',
            rpeTarget: 8,
            restSeconds: 60,
            scienceTip: 'Critical for structural shoulder balance, counteracting bench press volume and rounded posture.',
            emgFocus: 'Rotator cuff health & posterior chain posture',
          },
        ],
      },
      {
        id: 'lower-2',
        dayName: 'Lower Body B (Posterior Chain & Quad Strength)',
        dayOfWeek: 'Friday',
        focus: 'Glutes, Hamstrings, Quads, Core',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-hack-squat',
            name: 'Leg Press or Hack Squat (Deep Knee Flexion)',
            targetMuscle: 'Quadriceps (Vastus Lateralis/Medialis)',
            secondaryMuscles: ['Glutes'],
            equipment: 'Hack Squat / Leg Press Machine',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8.5,
            restSeconds: 120,
            scienceTip: 'Drive knees forward over toes in deep flexion for maximum vastus medialis & lateralis stretch.',
            emgFocus: 'Full knee flexion with zero spinal shear',
          },
          {
            id: 'ex-hip-thrust',
            name: 'Barbell or Dumbbell Hip Thrust (1s Squeeze at Top)',
            targetMuscle: 'Gluteus Maximus',
            secondaryMuscles: ['Hamstrings', 'Adductors'],
            equipment: 'Barbell / Dumbbell + Bench',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Glute max reaches peak contraction at full hip extension under direct vertical resistance.',
            emgFocus: '2x higher glute EMG activation than standard back squats (Contreras et al.)',
          },
          {
            id: 'ex-leg-extension',
            name: 'Leg Extension (Controlled 3s Negative)',
            targetMuscle: 'Rectus Femoris (Quad)',
            secondaryMuscles: [],
            equipment: 'Leg Extension Machine',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'The only quad exercise that trains the rectus femoris in isolation since squats keep it bi-articularly shortened.',
            emgFocus: 'Isolated Rectus Femoris hypertrophy',
          },
        ],
      },
    ],
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_default',
  name: 'Alex Mercer',
  age: 28,
  sex: 'male',
  heightCm: 178,
  weightKg: 78,
  targetWeightKg: 72,
  targetDate: '2026-11-20',
  bodyFatPct: 18.5,
  goal: 'lose_fat',
  dietType: 'flexible',
  experienceLevel: 'intermediate',
  trainingDaysPerWeek: 4,
  selectedDays: ['Mon', 'Tue', 'Thu', 'Fri'],
  sessionDurationMin: 55,
  preferredTime: 'morning',
  musclePriority: 'chest',
  injuries: ['Mild right shoulder impingement'],
  injuryNotes: 'Avoid flared elbows on pressing movements.',
  allergies: 'None',
  cuisinePreference: 'High-Protein Global & Mediterranean',
  
  bmr: 1750,
  tdee: 2712,
  dailyCalories: 2150,
  dailyProtein: 165,
  dailyCarbs: 220,
  dailyFat: 65,
  hydrationLiters: 3.5,
  weeklyRateKg: -0.5,
  isOnboarded: true,
};

export const INITIAL_SAMPLE_MEAL_LOGS: MealLog[] = [
  {
    id: 'log-1',
    date: '2026-08-19',
    time: '08:30',
    mealType: 'Breakfast',
    photoUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    isEstimated: false,
    mealTitle: 'Greek Yogurt Protein Bowl with Berries & Almonds',
    calories: 420,
    proteinG: 38,
    carbsG: 42,
    fatG: 12,
    fiberG: 8,
    items: [
      { name: '0% Non-Fat Greek Yogurt', portionDescription: '250g bowl', weightG: 250, calories: 150, proteinG: 26, carbsG: 9, fatG: 0 },
      { name: 'Whey Protein Isolate (Vanilla)', portionDescription: '1/2 scoop (15g)', weightG: 15, calories: 60, proteinG: 12, carbsG: 1, fatG: 0.5 },
      { name: 'Mixed Blueberries & Raspberries', portionDescription: '1 cup (120g)', weightG: 120, calories: 75, proteinG: 1, carbsG: 18, fatG: 0.5 },
      { name: 'Rolled Oats & Chia Seeds', portionDescription: '20g', weightG: 20, calories: 75, proteinG: 3, carbsG: 12, fatG: 2 },
      { name: 'Crushed Almonds', portionDescription: '10g (approx 8 nuts)', weightG: 10, calories: 60, proteinG: 2, carbsG: 2, fatG: 5 },
    ],
    userNotes: 'Optimal pre-workout breakfast with fast-acting leucine for MPS.',
  },
  {
    id: 'log-2',
    date: '2026-08-19',
    time: '13:15',
    mealType: 'Lunch',
    photoUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80',
    isEstimated: false,
    mealTitle: 'Grilled Lemon Herb Chicken Bowl with Quinoa & Greens',
    calories: 640,
    proteinG: 52,
    carbsG: 65,
    fatG: 18,
    fiberG: 9,
    items: [
      { name: 'Skinless Chicken Breast (Grilled)', portionDescription: '180g cooked', weightG: 180, calories: 290, proteinG: 48, carbsG: 0, fatG: 6 },
      { name: 'Cooked Tricolor Quinoa', portionDescription: '150g', weightG: 150, calories: 180, proteinG: 6, carbsG: 32, fatG: 3 },
      { name: 'Roasted Broccoli & Bell Peppers', portionDescription: '150g', weightG: 150, calories: 55, proteinG: 3, carbsG: 10, fatG: 1 },
      { name: 'Extra Virgin Olive Oil Dressing', portionDescription: '1 tbsp (10ml)', weightG: 10, calories: 85, proteinG: 0, carbsG: 0, fatG: 10 },
    ],
    userNotes: 'High satiety index score meal hitting 52g protein.',
  },
];

export const INITIAL_SAMPLE_BODY_METRICS: BodyMetric[] = [
  { id: 'bm-1', date: '2026-07-01', weightKg: 81.2, bodyFatPct: 20.4, waistCm: 89 },
  { id: 'bm-2', date: '2026-07-08', weightKg: 80.6, bodyFatPct: 19.9, waistCm: 88.5 },
  { id: 'bm-3', date: '2026-07-15', weightKg: 80.1, bodyFatPct: 19.5, waistCm: 87.8 },
  { id: 'bm-4', date: '2026-07-22', weightKg: 79.5, bodyFatPct: 19.1, waistCm: 87.2 },
  { id: 'bm-5', date: '2026-07-29', weightKg: 79.0, bodyFatPct: 18.8, waistCm: 86.5 },
  { id: 'bm-6', date: '2026-08-05', weightKg: 78.6, bodyFatPct: 18.6, waistCm: 86.0 },
  { id: 'bm-7', date: '2026-08-12', weightKg: 78.2, bodyFatPct: 18.5, waistCm: 85.5 },
  { id: 'bm-8', date: '2026-08-19', weightKg: 78.0, bodyFatPct: 18.3, waistCm: 85.0 },
];

export const INITIAL_SAMPLE_WORKOUT_LOGS: WorkoutCompletionLog[] = [
  { id: 'w-1', date: '2026-08-06', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 52, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.2 },
  { id: 'w-2', date: '2026-08-07', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 58, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
  { id: 'w-3', date: '2026-08-08', dayId: 'rest-1', dayName: 'Active Recovery & Zone 2 Walk', durationMin: 35, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-4', date: '2026-08-09', dayId: 'upper-2', dayName: 'Upper Body B (Hypertrophy & Shoulders)', durationMin: 50, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.0 },
  { id: 'w-5', date: '2026-08-10', dayId: 'lower-2', dayName: 'Lower Body B (Deadlift & Posterior Chain)', durationMin: 55, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.4 },
  { id: 'w-6', date: '2026-08-11', dayId: 'rest-2', dayName: 'Mobility & Foam Rolling Routine', durationMin: 25, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-7', date: '2026-08-12', dayId: 'rest-3', dayName: 'CNS Recovery & Hydration', durationMin: 20, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-8', date: '2026-08-13', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 54, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.3 },
  { id: 'w-9', date: '2026-08-14', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 60, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.6 },
  { id: 'w-10', date: '2026-08-15', dayId: 'rest-4', dayName: 'Active Recovery & Stretching', durationMin: 30, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-11', date: '2026-08-16', dayId: 'upper-2', dayName: 'Upper Body B (Hypertrophy & Shoulders)', durationMin: 48, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.1 },
  { id: 'w-12', date: '2026-08-17', dayId: 'lower-2', dayName: 'Lower Body B (Deadlift & Posterior Chain)', durationMin: 56, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
  { id: 'w-13', date: '2026-08-18', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 53, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.4 },
  { id: 'w-14', date: '2026-08-19', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 58, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
];
