import { WorkoutProgram, UserProfile, MealLog, BodyMetric, WorkoutCompletionLog } from '../types';

export const SAMPLE_WORKOUT_PROGRAMS: WorkoutProgram[] = [
  {
    id: 'upper-lower-4day',
    title: '4-Day Science-Based Upper / Lower Split',
    description: 'Optimal training frequency (2x/week per muscle group) for maximum muscle protein synthesis and fat loss with progressive overload tracking.',
    splitType: 'Upper/Lower',
    daysPerWeek: 4,
    scientificPhilosophy: 'Research demonstrates hitting each muscle group twice weekly maximizes MPS (Brad Schoenfeld et al.) with higher volume recovery than traditional bro-splits.',
    days: [
      {
        id: 'upper-1',
        dayName: 'Upper Body A (Power & Chest/Lat Emphasis)',
        dayOfWeek: 'Monday',
        focus: 'Chest, Upper Back, Lats, Shoulders, Arms',
        durationMin: 55,
        exercises: [
          {
            id: 'ex-incline-db-bench',
            name: 'Incline Dumbbell Bench Press (30° Angle)',
            targetMuscle: 'Upper Chest (Clavicular Head)',
            secondaryMuscles: ['Triceps', 'Anterior Deltoid'],
            equipment: 'Dumbbells, Incline Bench',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8,
            restSeconds: 120,
            scienceTip: 'A 30-degree incline provides peak EMG activation of the clavicular pec without excessive anterior delt dominance.',
            emgFocus: '+34% Clavicular Head activation vs flat bench',
            injuryAlternative: {
              originalExercise: 'Incline Dumbbell Bench Press',
              substitute: 'Low-to-High Cable Crossover or Neutral Grip DB Press',
              reason: 'Removes shoulder impingement torque while keeping upper chest tension.',
            },
          },
          {
            id: 'ex-chest-supported-row',
            name: 'Chest-Supported Neutral T-Bar Row',
            targetMuscle: 'Upper Back (Rhomboids, Mid-Traps)',
            secondaryMuscles: ['Biceps', 'Rear Delts'],
            equipment: 'T-Bar Machine or Incline Bench + Dumbbells',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Chest support eliminates spinal loading, isolating the rhomboids and mid-trapezius for safe progressive overload.',
            emgFocus: '90% Upper back recruitment with zero lumbar shear',
          },
          {
            id: 'ex-lat-pulldown',
            name: 'Half-Kneeling Lat Pulldown or Single-Arm Pulldown',
            targetMuscle: 'Lats (Iliac & Thoracic Fibers)',
            secondaryMuscles: ['Biceps', 'Brachialis'],
            equipment: 'Cable Machine',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Drive elbows down towards the hip pockets rather than pulling flared back to align with lat fiber orientation.',
            emgFocus: 'Maximum Lat lengthening in the eccentric phase',
          },
          {
            id: 'ex-cable-lateral-raise',
            name: 'Cross-Body Cable Lateral Raise (Wrist Height)',
            targetMuscle: 'Side Deltoids (Lateral Head)',
            secondaryMuscles: ['Trapezius'],
            equipment: 'Cable Machine',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Cables provide constant resistance in the stretched position where dumbbells have near-zero resistance.',
            emgFocus: 'Constant resistance profile throughout entire 120° ROM',
          },
          {
            id: 'ex-overhead-cable-triceps',
            name: 'Overhead Cable Triceps Extension',
            targetMuscle: 'Triceps (Long Head)',
            secondaryMuscles: [],
            equipment: 'Cable Machine + Rope',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Placing the shoulder in flexion stretches the long head, inducing stretch-mediated hypertrophy.',
            emgFocus: '1.5x greater long head hypertrophy vs pushdowns (Maeo et al. 2023)',
          },
        ],
      },
      {
        id: 'lower-1',
        dayName: 'Lower Body A (Quad & Glute Focus)',
        dayOfWeek: 'Tuesday',
        focus: 'Quadriceps, Glutes, Hamstrings, Calves',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-bulgarian-split-squat',
            name: 'Bulgarian Split Squat (Deficit)',
            targetMuscle: 'Quadriceps & Gluteus Maximus',
            secondaryMuscles: ['Adductors', 'Hamstrings'],
            equipment: 'Dumbbells + Bench',
            sets: 3,
            reps: '8-10 reps / leg',
            rpeTarget: 8.5,
            restSeconds: 120,
            scienceTip: 'Elevating front foot on a 2-inch plate allows deeper hip flexion and full stretch under load.',
            emgFocus: 'Superior unilateral stabilizer recruitment vs bilateral back squat',
            injuryAlternative: {
              originalExercise: 'Barbell Back Squat',
              substitute: 'Leg Press with High/Wide Foot Placement or Hack Squat',
              reason: 'Completely unloads the lumbar spine for lower back safety.',
            },
          },
          {
            id: 'ex-romanian-deadlift',
            name: 'Dumbbell / Trap Bar Romanian Deadlift',
            targetMuscle: 'Hamstrings (Semitendinosus/Biceps Femoris) & Glutes',
            secondaryMuscles: ['Erector Spinae', 'Lats'],
            equipment: 'Dumbbells or Barbell',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 120,
            scienceTip: 'Focus on pushing the hips backward like touching a wall behind you until a deep hamstring stretch is reached.',
            emgFocus: 'Maximum hamstring elongation under tension',
          },
          {
            id: 'ex-seated-leg-curl',
            name: 'Seated Leg Curl',
            targetMuscle: 'Hamstrings (All 4 heads)',
            secondaryMuscles: ['Calves'],
            equipment: 'Seated Leg Curl Machine',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'Seated leg curls stretch hamstrings at the hip, yielding ~1.8x greater muscle growth than lying leg curls.',
            emgFocus: 'Stretch-mediated hypertrophy (Schoenfeld & Maeo 2021)',
          },
          {
            id: 'ex-standing-calf-raise',
            name: 'Single-Leg Standing Calf Raise (3s Pause at Bottom)',
            targetMuscle: 'Gastrocnemius & Soleus',
            secondaryMuscles: [],
            equipment: 'Dumbbell + Step',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Pausing 3 seconds at the bottom dissipates Achilles tendon elastic recoil, forcing active muscle recruitment.',
            emgFocus: 'Eliminates stretch-shortening cycle bounce',
          },
        ],
      },
      {
        id: 'upper-2',
        dayName: 'Upper Body B (Hypertrophy & Shoulders/Arms)',
        dayOfWeek: 'Thursday',
        focus: 'Chest, Mid/Upper Back, Deltoids, Biceps',
        durationMin: 55,
        exercises: [
          {
            id: 'ex-flat-cable-flye',
            name: 'Seated Converging Machine / Cable Chest Press',
            targetMuscle: 'Mid & Sternal Pectoralis',
            secondaryMuscles: ['Triceps', 'Anterior Delt'],
            equipment: 'Machine / Cable',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Converging path matches the natural horizontal adduction path of the pectoral fibers.',
            emgFocus: 'Peak contraction at full horizontal adduction',
          },
          {
            id: 'ex-seated-cable-row',
            name: 'Wide-Grip Cable Row (Elbows at 45°)',
            targetMuscle: 'Rear Delts, Rhomboids, Traps',
            secondaryMuscles: ['Biceps'],
            equipment: 'Cable Row Machine',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Keep elbows flared at 45 degrees to target upper back rather than lats.',
            emgFocus: 'Maximum rhomboid retraction and rear delt engagement',
          },
          {
            id: 'ex-incline-db-curl',
            name: 'Incline Dumbbell Biceps Curl',
            targetMuscle: 'Biceps Brachii (Long Head)',
            secondaryMuscles: ['Brachialis', 'Forearms'],
            equipment: 'Incline Bench + Dumbbells',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'Shoulder extension at the bottom stretches the long head across both shoulder and elbow joints.',
            emgFocus: 'Peak stretch at the glenohumeral joint',
          },
          {
            id: 'ex-face-pull',
            name: 'Cable Face Pull with External Rotation',
            targetMuscle: 'Rear Delts, Infraspinatus, Rotator Cuff',
            secondaryMuscles: ['Traps'],
            equipment: 'Cable + Rope',
            sets: 3,
            reps: '15-20 reps',
            rpeTarget: 8,
            restSeconds: 60,
            scienceTip: 'Critical for structural shoulder balance, counteracting bench press volume and rounded posture.',
            emgFocus: 'Rotator cuff health & posterior chain posture',
          },
        ],
      },
      {
        id: 'lower-2',
        dayName: 'Lower Body B (Posterior Chain & Quad Strength)',
        dayOfWeek: 'Friday',
        focus: 'Glutes, Hamstrings, Quads, Core',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-hack-squat',
            name: 'Leg Press or Hack Squat (Deep Knee Flexion)',
            targetMuscle: 'Quadriceps (Vastus Lateralis/Medialis)',
            secondaryMuscles: ['Glutes'],
            equipment: 'Hack Squat / Leg Press Machine',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8.5,
            restSeconds: 120,
            scienceTip: 'Drive knees forward over toes in deep flexion for maximum vastus medialis & lateralis stretch.',
            emgFocus: 'Full knee flexion with zero spinal shear',
          },
          {
            id: 'ex-hip-thrust',
            name: 'Barbell or Dumbbell Hip Thrust (1s Squeeze at Top)',
            targetMuscle: 'Gluteus Maximus',
            secondaryMuscles: ['Hamstrings', 'Adductors'],
            equipment: 'Barbell / Dumbbell + Bench',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Glute max reaches peak contraction at full hip extension under direct vertical resistance.',
            emgFocus: '2x higher glute EMG activation than standard back squats (Contreras et al.)',
          },
          {
            id: 'ex-leg-extension',
            name: 'Leg Extension (Controlled 3s Negative)',
            hindiTerminology: 'लेग एक्सटेंशन (जांघ का व्यायाम)',
            targetMuscle: 'Rectus Femoris (Quad)',
            secondaryMuscles: [],
            equipment: 'Leg Extension Machine',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'The only quad exercise that trains the rectus femoris in isolation since squats keep it bi-articularly shortened.',
            emgFocus: 'Isolated Rectus Femoris hypertrophy',
            muscle_engagement_rank: 94,
            hypertrophyScore: 9.4,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Isolated Quad Overload',
          },
        ],
      },
    ],
  },
  {
    id: 'dumbbell-split-4day',
    title: '4-Day Dumbbell & Adjustable Bench Hypertrophy Program',
    description: 'Designed specifically for home gym setups with dumbbells and an adjustable bench, maximizing progressive tension across all major muscle groups.',
    splitType: 'Upper/Lower',
    daysPerWeek: 4,
    scientificPhilosophy: 'Utilizes dumbbell mechanical drops, full joint articulation paths, and unilateral stabilization to match barbell hypertrophy outcomes (Schoenfeld et al.).',
    days: [
      {
        id: 'db-upper-1',
        dayName: 'Upper Body A (Dumbbell Chest & Back Focus)',
        dayOfWeek: 'Monday',
        focus: 'Chest, Upper Back, Lats, Shoulders, Arms',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-incline-db-press',
            name: 'Incline Dumbbell Bench Press (30° Angle)',
            hindiTerminology: 'ऊपरी सीने का डंबल प्रेस (Incline Chest)',
            targetMuscle: 'Upper Chest (Clavicular Head)',
            secondaryMuscles: ['Anterior Deltoids', 'Triceps'],
            equipment: 'Dumbbells, Incline Bench',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8,
            restSeconds: 120,
            scienceTip: 'A 30-degree incline provides peak EMG activation of the clavicular pec without anterior delt dominance.',
            emgFocus: '+34% Clavicular Head activation vs flat bench',
            muscle_engagement_rank: 98,
            hypertrophyScore: 9.8,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Maximum Hypertrophy & EMG',
          },
          {
            id: 'ex-db-single-arm-row',
            name: 'Single-Arm Dumbbell Row (Hand Supported on Bench)',
            hindiTerminology: 'डंबल रोविंग (पीठ की चौड़ाई और लैट्स)',
            targetMuscle: 'Lats (Iliac & Thoracic Fibers)',
            secondaryMuscles: ['Rhomboids', 'Biceps', 'Rear Delts'],
            equipment: 'Dumbbell, Flat Bench',
            sets: 3,
            reps: '10-12 reps/arm',
            rpeTarget: 8,
            restSeconds: 90,
            scienceTip: 'Pull dumbbell toward hip pocket rather than armpit to optimize lat fiber recruitment and reduce bicep dominance.',
            emgFocus: 'Peak lat elongation in stretch phase',
            muscle_engagement_rank: 96,
            hypertrophyScore: 9.6,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Unilateral Lat Overload',
          },
          {
            id: 'ex-seated-db-shoulder-press',
            name: 'Seated Dumbbell Shoulder Press (75° Incline)',
            hindiTerminology: 'डंबल शोल्डर प्रेस (कंधों का व्यायाम)',
            targetMuscle: 'Anterior Deltoids & Lateral Deltoids',
            secondaryMuscles: ['Triceps', 'Upper Chest'],
            equipment: 'Dumbbells, Adjustable Bench',
            sets: 3,
            reps: '8-10 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'A slight 75° bench incline reduces excessive lumbar hyperextension while keeping full tension on the shoulders.',
            emgFocus: 'High anterior & lateral delt recruitment',
            muscle_engagement_rank: 94,
            hypertrophyScore: 9.4,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Heavy Overhead Tension',
          },
          {
            id: 'ex-db-lateral-raise',
            name: 'Standing Dumbbell Lateral Raise (Slight Forward Lean)',
            hindiTerminology: 'डंबल साइड रेज (Side Delts / चौड़े कंधे)',
            targetMuscle: 'Lateral Deltoids',
            secondaryMuscles: ['Trapezius'],
            equipment: 'Dumbbells',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Lean torso forward 10-15° and raise dumbbells in the scapular plane (30° forward) to avoid shoulder impingement.',
            emgFocus: 'Maximum lateral head deltoid isolation',
            muscle_engagement_rank: 95,
            hypertrophyScore: 9.5,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • 3D Shoulder Cap Builder',
          },
          {
            id: 'ex-incline-db-curl',
            name: 'Incline Dumbbell Biceps Curl (Shoulder Hyperextension)',
            hindiTerminology: 'इनक्लाइन डंबल बाइसेप्स कर्ल (डोले का पीक)',
            targetMuscle: 'Biceps Brachii (Long Head Peak)',
            secondaryMuscles: ['Brachialis', 'Forearms'],
            equipment: 'Dumbbells, Incline Bench',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 9,
            restSeconds: 75,
            scienceTip: 'Shoulder hyperextension on an incline bench places the long head in maximum stretch, triggering stretch-mediated hypertrophy.',
            emgFocus: 'Deep passive stretch on biceps long head',
            muscle_engagement_rank: 96,
            hypertrophyScore: 9.6,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Peak Bicep Stretch',
          },
        ],
      },
      {
        id: 'db-lower-1',
        dayName: 'Lower Body A (Dumbbell Quad & Posterior Chain)',
        dayOfWeek: 'Tuesday',
        focus: 'Quads, Hamstrings, Glutes, Calves',
        durationMin: 50,
        exercises: [
          {
            id: 'ex-bulgarian-split-squat',
            name: 'Bulgarian Split Squat (Dumbbells in Hands)',
            hindiTerminology: 'बल्गेरियन स्प्लिट स्क्वाट (एक पैर का स्क्वाट)',
            targetMuscle: 'Quadriceps & Gluteus Maximus',
            secondaryMuscles: ['Adductors', 'Hamstrings'],
            equipment: 'Dumbbells, Bench',
            sets: 3,
            reps: '8-10 reps/leg',
            rpeTarget: 8.5,
            restSeconds: 120,
            scienceTip: 'Lean torso 15° forward for increased glute recruitment or stay upright for maximum quad loading.',
            emgFocus: 'Extreme unilateral hypertrophy and stabilizer activation',
            muscle_engagement_rank: 98,
            hypertrophyScore: 9.8,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Unilateral Leg King',
          },
          {
            id: 'ex-romanian-deadlift',
            name: 'Dumbbell Romanian Deadlift (Hips Pushed to Back Wall)',
            hindiTerminology: 'डंबल रोमानियन डेडलिफ्ट (हैमस्ट्रिंग स्ट्रेच)',
            targetMuscle: 'Hamstrings & Gluteus Maximus',
            secondaryMuscles: ['Erector Spinae', 'Forearms'],
            equipment: 'Dumbbells',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8,
            restSeconds: 100,
            scienceTip: 'Keep dumbbells sliding along shins and push hips backward until deep hamstring tension is achieved.',
            emgFocus: 'Maximum lengthened hamstring overload',
            muscle_engagement_rank: 97,
            hypertrophyScore: 9.7,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Posterior Chain King',
          },
          {
            id: 'ex-goblet-squat',
            name: 'Dumbbell Goblet Squat (Heels Elevated on Plates)',
            hindiTerminology: 'डंबल गोब्लेट स्क्वाट (जांघों का व्यायाम)',
            targetMuscle: 'Quadriceps (Vastus Medialis & Lateralis)',
            secondaryMuscles: ['Glutes', 'Core'],
            equipment: 'Dumbbell, 2 Plates for Heels',
            sets: 3,
            reps: '12-15 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Elevating heels allows upright torso mechanics and deep knee flexion for supreme quad stretch.',
            emgFocus: 'Full knee flexion with zero lumbar stress',
            muscle_engagement_rank: 93,
            hypertrophyScore: 9.3,
            hypertrophyRank: 'A-Tier',
            effectivenessBadge: 'A-Tier • Deep Quad Burn',
          },
          {
            id: 'ex-db-seated-calf-raise',
            name: 'Dumbbell Seated Calf Raise (Dumbbells on Knees)',
            hindiTerminology: 'पिंडली का व्यायाम (Soleus / Calf Raise)',
            targetMuscle: 'Soleus (Deep Calf Muscle)',
            secondaryMuscles: ['Gastrocnemius'],
            equipment: 'Dumbbells, Bench, Block for Toes',
            sets: 4,
            reps: '12-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Bent knee angle slackens gastrocnemius, isolating the soleus muscle for dense lower leg hypertrophy.',
            emgFocus: 'Direct soleus isolation and ankle resilience',
            muscle_engagement_rank: 91,
            hypertrophyScore: 9.1,
            hypertrophyRank: 'A-Tier',
            effectivenessBadge: 'A-Tier • Soleus Hypertrophy',
          },
        ],
      },
    ],
  },
  {
    id: 'bodyweight-calisthenics-4day',
    title: '4-Day Pure Bodyweight & Calisthenics Program (Zero Equipment)',
    description: '100% Calisthenics & Bodyweight Hypertrophy. Strictly zero dumbbells, barbells, or weights. Built using mechanical leverage progression and high-tension bodyweight movements.',
    splitType: 'Upper/Lower',
    daysPerWeek: 4,
    scientificPhilosophy: 'Calisthenics muscle growth is mathematically identical to weight training when sets are taken within 1-3 reps of failure (RPE 8-9.5) using progressive leverage variations.',
    days: [
      {
        id: 'bw-upper-1',
        dayName: 'Bodyweight Upper A (Chest, Back, Shoulders & Arms)',
        dayOfWeek: 'Monday',
        focus: 'Chest, Upper Back, Anterior/Lateral Delts, Triceps, Biceps',
        durationMin: 45,
        exercises: [
          {
            id: 'ex-archer-pushup',
            name: 'Archer Push-Up (Wide Unilateral Chest & Triceps)',
            hindiTerminology: 'आर्चर पुश-अप (एक तरफा सीने और बांह का व्यायाम)',
            targetMuscle: 'Pectoralis Major & Triceps Lockout',
            secondaryMuscles: ['Anterior Deltoid', 'Core Stabilizers'],
            equipment: 'Floor / Mat',
            sets: 3,
            reps: '8-12 reps/side',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Slide body toward one working hand while extending the other arm straight to place ~75% bodyweight overload on single pectoral.',
            emgFocus: 'High unilateral mechanical tension without external weights',
            muscle_engagement_rank: 96,
            hypertrophyScore: 9.6,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Elite Bodyweight Chest Overload',
          },
          {
            id: 'ex-towel-door-row',
            name: 'Doorframe Towel Inverted Row (Lats & Mid-Back Thickness)',
            hindiTerminology: 'दरवाजे और तौलिए से रोविंग (पीठ की चौड़ाई और लैट्स)',
            targetMuscle: 'Lats, Rhomboids & Middle Trapezius',
            secondaryMuscles: ['Biceps', 'Rear Deltoids', 'Forearms'],
            equipment: 'Towel + Sturdy Doorframe or Table Underneath',
            sets: 3,
            reps: '10-15 reps',
            rpeTarget: 8.5,
            restSeconds: 75,
            scienceTip: 'Loop a strong towel around door handles or use doorframe edge. The lower your feet walk forward, the higher the horizontal pulling load.',
            emgFocus: 'Upper back and lat shortening with bodyweight leverage',
            muscle_engagement_rank: 94,
            hypertrophyScore: 9.4,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • No-Equipment Back Builder',
          },
          {
            id: 'ex-feet-elevated-vertical-pike-pushup',
            name: 'Feet-Elevated Pike Pushup (Vertical Overhead Pressing)',
            hindiTerminology: 'पाइक पुश-अप (कंधों का वर्टिकल प्रेस)',
            targetMuscle: 'Anterior & Lateral Deltoids',
            secondaryMuscles: ['Upper Chest', 'Triceps', 'Serratus Anterior'],
            equipment: 'Floor / Chair or Bed Edge for Feet',
            sets: 3,
            reps: '8-12 reps',
            rpeTarget: 8.5,
            restSeconds: 90,
            scienceTip: 'Elevating feet on a chair creates a direct vertical pushing angle matching a heavy overhead military dumbbell press.',
            emgFocus: 'Vertical shoulder press loading via calisthenics leverage',
            muscle_engagement_rank: 95,
            hypertrophyScore: 9.5,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Pure Bodyweight Overhead Press',
          },
          {
            id: 'ex-floor-back-widow',
            name: 'Floor Back Widows (Scapular Retraction & Lower Traps)',
            hindiTerminology: 'फ्लोर बैक विडोस (पीठ और कंधों की मजबूती)',
            targetMuscle: 'Rhomboids, Lower & Middle Trapezius, Posterior Delts',
            secondaryMuscles: ['Erector Spinae'],
            equipment: 'Floor / Mat',
            sets: 3,
            reps: '12-15 reps with 2s hold',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Lie on back, bend knees, drive elbows hard into floor to lift upper torso 4 inches off ground. Holds peak scapular retraction.',
            emgFocus: 'Deep upper back contraction with zero equipment',
            muscle_engagement_rank: 92,
            hypertrophyScore: 9.2,
            hypertrophyRank: 'A-Tier',
            effectivenessBadge: 'A-Tier • Zero Equipment Scapular Strength',
          },
          {
            id: 'ex-diamond-pushup',
            name: 'Diamond Push-Up (Triceps Medial/Lateral & Inner Chest)',
            hindiTerminology: 'डायमंड पुश-अप (ट्राइसेप्स और सीना)',
            targetMuscle: 'Triceps Brachii (Medial & Lateral Heads)',
            secondaryMuscles: ['Pectoralis Major', 'Anterior Deltoid'],
            equipment: 'Floor / Mat',
            sets: 3,
            reps: '10-15 reps',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'Thumbs and index fingers touching under sternum shifts peak mechanical moment arm directly onto triceps extension.',
            emgFocus: 'Maximum triceps activation among all push-up variations',
            muscle_engagement_rank: 95,
            hypertrophyScore: 9.5,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Bodyweight Triceps King',
          },
        ],
      },
      {
        id: 'bw-lower-1',
        dayName: 'Bodyweight Lower A (Quads, Hamstrings & Glutes)',
        dayOfWeek: 'Tuesday',
        focus: 'Quadriceps, Hamstrings, Glutes, Calves, Core',
        durationMin: 45,
        exercises: [
          {
            id: 'ex-bw-bulgarian-split-squat',
            name: '1.5-Rep Bodyweight Bulgarian Split Squat',
            hindiTerminology: 'बल्गेरियन स्प्लिट स्क्वाट (बिना वजन - 1.5 रेप)',
            targetMuscle: 'Quadriceps & Gluteus Maximus',
            secondaryMuscles: ['Adductors', 'Hamstrings'],
            equipment: 'Chair / Sofa / Bed Edge',
            sets: 3,
            reps: '10-12 reps/leg (1 full + 1 half bottom pulse = 1 rep)',
            rpeTarget: 9,
            restSeconds: 90,
            scienceTip: 'Performing a 1.5 rep (descend, rise halfway, descend back, rise to top) doubles time under tension in the lengthened hypertrophy position.',
            emgFocus: 'Extreme time-under-tension in deep hip/knee flexion',
            muscle_engagement_rank: 98,
            hypertrophyScore: 9.8,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Unilateral Bodyweight Leg Overload',
          },
          {
            id: 'ex-nordic-hamstring-curl',
            name: 'Floor-Assisted Nordic Hamstring Curl (Eccentric Overload)',
            hindiTerminology: 'नॉर्डिक हैमस्ट्रिंग कर्ल (जांघ के पीछे का हिस्सा)',
            targetMuscle: 'Hamstrings (Biceps Femoris & Semitendinosus)',
            secondaryMuscles: ['Glutes', 'Calves'],
            equipment: 'Floor Mat + Foot Anchor / Sofa Base / Partner',
            sets: 3,
            reps: '6-8 reps (Slow 4s descent with hand catch)',
            rpeTarget: 9,
            restSeconds: 100,
            scienceTip: 'Hook heels under a heavy sofa or bed. Lower body with a straight torso for 4 seconds, then lightly push off floor to reset.',
            emgFocus: 'Highest hamstring eccentric EMG recorded in sports science',
            muscle_engagement_rank: 99,
            hypertrophyScore: 9.9,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • #1 Hamstring Builder',
          },
          {
            id: 'ex-sissy-squat-bw',
            name: 'Bodyweight Sissy Squat (Supported Knee-Travel Quad Stretch)',
            hindiTerminology: 'सिसी स्क्वाट (जांघों का डीप स्ट्रेच)',
            targetMuscle: 'Quadriceps (Rectus Femoris & Vastus Muscles)',
            secondaryMuscles: ['Core', 'Ankles'],
            equipment: 'Wall / Doorframe for Balance Support',
            sets: 3,
            reps: '10-12 reps',
            rpeTarget: 8.5,
            restSeconds: 75,
            scienceTip: 'Holding a doorframe, rise onto toes and push knees forward while leaning torso back. Creates extreme stretch on rectus femoris.',
            emgFocus: 'Pure quad isolation without weights or machines',
            muscle_engagement_rank: 94,
            hypertrophyScore: 9.4,
            hypertrophyRank: 'S-Tier',
            effectivenessBadge: 'S-Tier • Intense Quad Hypertrophy',
          },
          {
            id: 'ex-single-leg-calf-raise-wall',
            name: 'Single-Leg Deficit Wall Calf Raise (3s Bottom Pause)',
            hindiTerminology: 'सिंगल लेग पिंडली का रेज (Calf Raise)',
            targetMuscle: 'Gastrocnemius & Soleus',
            secondaryMuscles: ['Foot Plantar Flexors'],
            equipment: 'Stair Step / Door Threshold + Wall for Balance',
            sets: 4,
            reps: '12-15 reps/leg',
            rpeTarget: 9,
            restSeconds: 60,
            scienceTip: 'A full 3-second dead-stop pause at deepest deficit eliminates Achilles tendon elastic bounce, forcing pure calf muscular work.',
            emgFocus: 'Deep eccentric stretch and full contraction',
            muscle_engagement_rank: 92,
            hypertrophyScore: 9.2,
            hypertrophyRank: 'A-Tier',
            effectivenessBadge: 'A-Tier • Calves Isolation',
          },
          {
            id: 'ex-copenhagen-adductor-plank',
            name: 'Copenhagen Adductor & Oblique Plank (Inner Thigh & Core)',
            hindiTerminology: 'कोपेनहेगन प्लैंक (अंदरूनी जांघ और साइड एब्स)',
            targetMuscle: 'Adductor Longus/Magnus & Side Obliques',
            secondaryMuscles: ['Gluteus Medius', 'Transverse Abdominis'],
            equipment: 'Chair / Sofa / Bed Edge',
            sets: 3,
            reps: '20-30s hold/side',
            rpeTarget: 8.5,
            restSeconds: 60,
            scienceTip: 'Place top foot on chair edge and elevate hips off floor. Squeezing top inner thigh prevents groin injuries and stabilizes pelvis.',
            emgFocus: 'Maximal adductor muscle recruitment',
            muscle_engagement_rank: 93,
            hypertrophyScore: 9.3,
            hypertrophyRank: 'A-Tier',
            effectivenessBadge: 'A-Tier • Adductor & Core Power',
          },
        ],
      },
    ],
  },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_default',
  name: '',
  email: '',
  age: 26,
  sex: 'male',
  heightCm: 175,
  weightKg: 78,
  targetWeightKg: 70,
  targetDate: '2026-11-20',
  bodyFatPct: 19.0,
  goal: 'lose_fat',
  dietType: 'flexible',
  experienceLevel: 'intermediate',
  trainingDaysPerWeek: 4,
  selectedDays: ['Mon', 'Tue', 'Thu', 'Fri'],
  sessionDurationMin: 55,
  preferredTime: 'morning',
  musclePriority: 'chest',
  injuries: [],
  injuryNotes: '',
  allergies: 'None',
  cuisinePreference: 'High-Protein Global & Mediterranean',
  
  bmr: 1750,
  tdee: 2712,
  dailyCalories: 2150,
  dailyProtein: 165,
  dailyCarbs: 220,
  dailyFat: 65,
  hydrationLiters: 3.5,
  weeklyRateKg: -0.5,
  isOnboarded: false,
};

export const INITIAL_SAMPLE_MEAL_LOGS: MealLog[] = [
  {
    id: 'log-1',
    date: '2026-08-19',
    time: '08:30',
    mealType: 'Breakfast',
    photoUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
    isEstimated: false,
    mealTitle: 'Greek Yogurt Protein Bowl with Berries & Almonds',
    calories: 420,
    proteinG: 38,
    carbsG: 42,
    fatG: 12,
    fiberG: 8,
    items: [
      { name: '0% Non-Fat Greek Yogurt', portionDescription: '250g bowl', weightG: 250, calories: 150, proteinG: 26, carbsG: 9, fatG: 0 },
      { name: 'Whey Protein Isolate (Vanilla)', portionDescription: '1/2 scoop (15g)', weightG: 15, calories: 60, proteinG: 12, carbsG: 1, fatG: 0.5 },
      { name: 'Mixed Blueberries & Raspberries', portionDescription: '1 cup (120g)', weightG: 120, calories: 75, proteinG: 1, carbsG: 18, fatG: 0.5 },
      { name: 'Rolled Oats & Chia Seeds', portionDescription: '20g', weightG: 20, calories: 75, proteinG: 3, carbsG: 12, fatG: 2 },
      { name: 'Crushed Almonds', portionDescription: '10g (approx 8 nuts)', weightG: 10, calories: 60, proteinG: 2, carbsG: 2, fatG: 5 },
    ],
    userNotes: 'Optimal pre-workout breakfast with fast-acting leucine for MPS.',
  },
  {
    id: 'log-2',
    date: '2026-08-19',
    time: '13:15',
    mealType: 'Lunch',
    photoUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&auto=format&fit=crop&q=80',
    isEstimated: false,
    mealTitle: 'Grilled Lemon Herb Chicken Bowl with Quinoa & Greens',
    calories: 640,
    proteinG: 52,
    carbsG: 65,
    fatG: 18,
    fiberG: 9,
    items: [
      { name: 'Skinless Chicken Breast (Grilled)', portionDescription: '180g cooked', weightG: 180, calories: 290, proteinG: 48, carbsG: 0, fatG: 6 },
      { name: 'Cooked Tricolor Quinoa', portionDescription: '150g', weightG: 150, calories: 180, proteinG: 6, carbsG: 32, fatG: 3 },
      { name: 'Roasted Broccoli & Bell Peppers', portionDescription: '150g', weightG: 150, calories: 55, proteinG: 3, carbsG: 10, fatG: 1 },
      { name: 'Extra Virgin Olive Oil Dressing', portionDescription: '1 tbsp (10ml)', weightG: 10, calories: 85, proteinG: 0, carbsG: 0, fatG: 10 },
    ],
    userNotes: 'High satiety index score meal hitting 52g protein.',
  },
];

export const INITIAL_SAMPLE_BODY_METRICS: BodyMetric[] = [
  { id: 'bm-1', date: '2026-07-01', weightKg: 81.2, bodyFatPct: 20.4, waistCm: 89 },
  { id: 'bm-2', date: '2026-07-08', weightKg: 80.6, bodyFatPct: 19.9, waistCm: 88.5 },
  { id: 'bm-3', date: '2026-07-15', weightKg: 80.1, bodyFatPct: 19.5, waistCm: 87.8 },
  { id: 'bm-4', date: '2026-07-22', weightKg: 79.5, bodyFatPct: 19.1, waistCm: 87.2 },
  { id: 'bm-5', date: '2026-07-29', weightKg: 79.0, bodyFatPct: 18.8, waistCm: 86.5 },
  { id: 'bm-6', date: '2026-08-05', weightKg: 78.6, bodyFatPct: 18.6, waistCm: 86.0 },
  { id: 'bm-7', date: '2026-08-12', weightKg: 78.2, bodyFatPct: 18.5, waistCm: 85.5 },
  { id: 'bm-8', date: '2026-08-19', weightKg: 78.0, bodyFatPct: 18.3, waistCm: 85.0 },
];

export const INITIAL_SAMPLE_WORKOUT_LOGS: WorkoutCompletionLog[] = [
  { id: 'w-1', date: '2026-08-06', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 52, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.2 },
  { id: 'w-2', date: '2026-08-07', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 58, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
  { id: 'w-3', date: '2026-08-08', dayId: 'rest-1', dayName: 'Active Recovery & Zone 2 Walk', durationMin: 35, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-4', date: '2026-08-09', dayId: 'upper-2', dayName: 'Upper Body B (Hypertrophy & Shoulders)', durationMin: 50, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.0 },
  { id: 'w-5', date: '2026-08-10', dayId: 'lower-2', dayName: 'Lower Body B (Deadlift & Posterior Chain)', durationMin: 55, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.4 },
  { id: 'w-6', date: '2026-08-11', dayId: 'rest-2', dayName: 'Mobility & Foam Rolling Routine', durationMin: 25, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-7', date: '2026-08-12', dayId: 'rest-3', dayName: 'CNS Recovery & Hydration', durationMin: 20, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-8', date: '2026-08-13', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 54, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.3 },
  { id: 'w-9', date: '2026-08-14', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 60, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.6 },
  { id: 'w-10', date: '2026-08-15', dayId: 'rest-4', dayName: 'Active Recovery & Stretching', durationMin: 30, exercisesCompleted: 1, totalExercises: 1, isRestDay: true },
  { id: 'w-11', date: '2026-08-16', dayId: 'upper-2', dayName: 'Upper Body B (Hypertrophy & Shoulders)', durationMin: 48, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.1 },
  { id: 'w-12', date: '2026-08-17', dayId: 'lower-2', dayName: 'Lower Body B (Deadlift & Posterior Chain)', durationMin: 56, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
  { id: 'w-13', date: '2026-08-18', dayId: 'upper-1', dayName: 'Upper Body A (Power & Chest)', durationMin: 53, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.4 },
  { id: 'w-14', date: '2026-08-19', dayId: 'lower-1', dayName: 'Lower Body A (Squat & Quad Focus)', durationMin: 58, exercisesCompleted: 5, totalExercises: 5, rpeAverage: 8.5 },
];
