import fs from 'fs';
import path from 'path';

interface RawRow {
  id: string;
  name: string;
  hindiName?: string;
  marathiName?: string;
  aliases: string[];
  category: string;
  source: 'IFCT' | 'USDA' | 'composite';
  cookingMethod?: string;
  per100g: {
    kcal: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    fiberG: number;
    sugarsG: number | null;
    sodiumMg: number | null;
    potassiumMg: number | null;
    calciumMg: number | null;
    ironMg: number | null;
    magnesiumMg: number | null;
    zincMg: number | null;
    vitaminA_ug: number | null;
    vitaminC_mg: number | null;
    vitaminD_ug: number | null;
    vitaminB12_ug: number | null;
    folate_ug: number | null;
  };
  glycemicIndex?: string | number;
  isVegetarian?: boolean;
  isVegan?: boolean;
  isFastingSafe?: boolean;
}

const batch2Rows: RawRow[] = [
  // 1. More Dals & Legumes
  {
    id: 'dal-palak',
    name: 'Dal Palak (Yellow Lentils with Spinach)',
    hindiName: 'दाल पालक',
    aliases: ['dal palak', 'palak dal', 'spinach dal'],
    category: 'Dals & Legumes',
    source: 'IFCT',
    cookingMethod: 'toor and moong dal simmered with fresh shredded spinach, tempered with garlic and cumin',
    per100g: {
      kcal: 98,
      proteinG: 6.2,
      carbsG: 13.5,
      fatG: 2.2,
      fiberG: 4.1,
      sugarsG: 1.2,
      sodiumMg: 190,
      potassiumMg: 310,
      calciumMg: 68,
      ironMg: 2.6,
      magnesiumMg: 42,
      zincMg: 1.1,
      vitaminA_ug: 180,
      vitaminC_mg: 12.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 65,
    },
    glycemicIndex: 28,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'chana-dal-fry',
    name: 'Chana Dal Fry (Split Bengal Gram)',
    hindiName: 'चना दाल फ्राई',
    aliases: ['chana dal', 'chana dal fry', 'bengal gram dal'],
    category: 'Dals & Legumes',
    source: 'IFCT',
    cookingMethod: 'split chickpea lentils boiled firm and tempered with onions, ginger, tomatoes and garam masala',
    per100g: {
      kcal: 128,
      proteinG: 7.8,
      carbsG: 18.2,
      fatG: 2.8,
      fiberG: 5.8,
      sugarsG: 1.4,
      sodiumMg: 210,
      potassiumMg: 290,
      calciumMg: 48,
      ironMg: 2.8,
      magnesiumMg: 48,
      zincMg: 1.4,
      vitaminA_ug: 15,
      vitaminC_mg: 3.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 72,
    },
    glycemicIndex: 25,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'masoor-dal-tadka',
    name: 'Masoor Dal Tadka (Red Lentil Curry)',
    hindiName: 'मसूर दाल तड़का',
    aliases: ['masoor dal', 'red lentil dal', 'masoor dal tadka', 'split red lentils'],
    category: 'Dals & Legumes',
    source: 'IFCT',
    cookingMethod: 'split red lentils cooked soft and tempered with cumin, tomatoes, green chillies & ghee',
    per100g: {
      kcal: 112,
      proteinG: 7.2,
      carbsG: 16.5,
      fatG: 2.0,
      fiberG: 4.6,
      sugarsG: 1.1,
      sodiumMg: 180,
      potassiumMg: 270,
      calciumMg: 32,
      ironMg: 2.4,
      magnesiumMg: 38,
      zincMg: 1.2,
      vitaminA_ug: 12,
      vitaminC_mg: 2.8,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 85,
    },
    glycemicIndex: 26,
    isVegetarian: true,
    isVegan: false,
  },

  // 2. Parathas & Flatbreads
  {
    id: 'methi-paratha',
    name: 'Methi Paratha (Fresh Fenugreek Wheat Flatbread)',
    hindiName: 'मेथी पराठा',
    marathiName: 'मेथीचे पराठे',
    aliases: ['methi paratha', 'fenugreek paratha', 'methi thepla style paratha'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'whole wheat flour kneaded with chopped fresh methi leaves and spices, tawa toasted with oil',
    per100g: {
      kcal: 265,
      proteinG: 7.8,
      carbsG: 44.0,
      fatG: 6.5,
      fiberG: 6.8,
      sugarsG: 1.5,
      sodiumMg: 240,
      potassiumMg: 280,
      calciumMg: 75,
      ironMg: 3.2,
      magnesiumMg: 65,
      zincMg: 1.4,
      vitaminA_ug: 95,
      vitaminC_mg: 8.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 48,
    },
    glycemicIndex: 45,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'palak-paratha',
    name: 'Palak Paratha (Spinach Whole Wheat Flatbread)',
    hindiName: 'पालक पराठा',
    aliases: ['palak paratha', 'spinach paratha'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'pureed spinach dough pan toasted on tawa with light oil',
    per100g: {
      kcal: 255,
      proteinG: 7.5,
      carbsG: 43.0,
      fatG: 5.8,
      fiberG: 6.2,
      sugarsG: 1.4,
      sodiumMg: 220,
      potassiumMg: 290,
      calciumMg: 85,
      ironMg: 3.0,
      magnesiumMg: 62,
      zincMg: 1.3,
      vitaminA_ug: 240,
      vitaminC_mg: 9.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 60,
    },
    glycemicIndex: 46,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'gobi-paratha',
    name: 'Gobi Paratha (Cauliflower Stuffed Flatbread)',
    hindiName: 'गोभी पराठा',
    aliases: ['gobi paratha', 'cauliflower paratha', 'gobhi paratha'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'grated spiced cauliflower stuffed into whole wheat dough, roasted with ghee on tawa',
    per100g: {
      kcal: 240,
      proteinG: 6.8,
      carbsG: 39.0,
      fatG: 6.4,
      fiberG: 5.2,
      sugarsG: 2.2,
      sodiumMg: 260,
      potassiumMg: 250,
      calciumMg: 45,
      ironMg: 2.2,
      magnesiumMg: 48,
      zincMg: 1.2,
      vitaminA_ug: 15,
      vitaminC_mg: 16.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0,
      folate_ug: 42,
    },
    glycemicIndex: 50,
    isVegetarian: true,
    isVegan: false,
  },

  // 3. More Sabzis & Curries
  {
    id: 'baingan-bharta',
    name: 'Dhaba Baingan Bharta (Roasted Eggplant Mash)',
    hindiName: 'बैंगन का भर्ता',
    aliases: ['baingan bharta', 'baingan bhurji', 'roasted eggplant mash', 'vange bharit'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'charcoal-roasted large eggplant mashed and sautéed with chopped onions, tomatoes, garlic & mustard oil',
    per100g: {
      kcal: 75,
      proteinG: 1.8,
      carbsG: 8.5,
      fatG: 3.8,
      fiberG: 3.4,
      sugarsG: 3.8,
      sodiumMg: 190,
      potassiumMg: 260,
      calciumMg: 28,
      ironMg: 1.1,
      magnesiumMg: 22,
      zincMg: 0.4,
      vitaminA_ug: 35,
      vitaminC_mg: 8.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 30,
    },
    glycemicIndex: 20,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'jeera-aloo',
    name: 'Jeera Aloo (Cumin Roasted Potatoes)',
    hindiName: 'जीरा आलू',
    aliases: ['jeera aloo', 'cumin potatoes', 'zeera aloo'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'diced boiled potatoes tossed with crackled cumin seeds, turmeric, amchur & green chillies',
    per100g: {
      kcal: 115,
      proteinG: 2.0,
      carbsG: 18.0,
      fatG: 3.9,
      fiberG: 2.4,
      sugarsG: 1.2,
      sodiumMg: 180,
      potassiumMg: 360,
      calciumMg: 22,
      ironMg: 1.4,
      magnesiumMg: 26,
      zincMg: 0.5,
      vitaminA_ug: 12,
      vitaminC_mg: 12.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 24,
    },
    glycemicIndex: 55,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'aloo-gobhi',
    name: 'Aloo Gobhi (Potato & Cauliflower Curry)',
    hindiName: 'आलू गोभी',
    aliases: ['aloo gobhi', 'aloo gobi', 'alu gobi', 'potato cauliflower'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'cauliflower florets and potatoes cooked dry with ginger, coriander, turmeric & cumin',
    per100g: {
      kcal: 88,
      proteinG: 2.4,
      carbsG: 12.5,
      fatG: 3.2,
      fiberG: 2.8,
      sugarsG: 2.4,
      sodiumMg: 190,
      potassiumMg: 290,
      calciumMg: 32,
      ironMg: 1.2,
      magnesiumMg: 24,
      zincMg: 0.6,
      vitaminA_ug: 20,
      vitaminC_mg: 28.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 38,
    },
    glycemicIndex: 42,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'bhindi-masala-fry',
    name: 'Bhindi Masala Fry (Crispy Okra / Ladyfinger)',
    hindiName: 'भिंडी मसाला',
    marathiName: 'भेंडीची भाजी',
    aliases: ['bhindi', 'bhindi fry', 'bhindi masala', 'okra fry', 'lady finger fry'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'sliced okra pan-roasted with amchur, onions, fennel and coriander powder in mustard oil',
    per100g: {
      kcal: 85,
      proteinG: 2.2,
      carbsG: 9.2,
      fatG: 4.4,
      fiberG: 3.8,
      sugarsG: 2.5,
      sodiumMg: 180,
      potassiumMg: 270,
      calciumMg: 75,
      ironMg: 1.2,
      magnesiumMg: 45,
      zincMg: 0.6,
      vitaminA_ug: 42,
      vitaminC_mg: 16.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 55,
    },
    glycemicIndex: 20,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'paneer-bhurji',
    name: 'Spiced Paneer Bhurji (Scrambled Cottage Cheese)',
    hindiName: 'पनीर भुर्जी',
    aliases: ['paneer bhurji', 'scrambled paneer', 'bhurji paneer'],
    category: 'Dairy & High-Protein',
    source: 'IFCT',
    cookingMethod: 'crumbled fresh paneer sautéed with onions, tomatoes, ginger, green chillies & turmeric in ghee',
    per100g: {
      kcal: 220,
      proteinG: 13.5,
      carbsG: 5.2,
      fatG: 16.2,
      fiberG: 1.2,
      sugarsG: 2.8,
      sodiumMg: 290,
      potassiumMg: 160,
      calciumMg: 310,
      ironMg: 1.1,
      magnesiumMg: 28,
      zincMg: 1.4,
      vitaminA_ug: 120,
      vitaminC_mg: 6.5,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 0.6,
      folate_ug: 18,
    },
    glycemicIndex: 15,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'tofu-firm-panseared',
    name: 'Pan-Seared Firm Tofu Cubes',
    hindiName: 'टोफू (सोया पनीर)',
    aliases: ['tofu', 'firm tofu', 'pan seared tofu', 'soya paneer'],
    category: 'Plant Protein',
    source: 'USDA',
    cookingMethod: 'pressed firm organic tofu pan seared with light oil',
    per100g: {
      kcal: 144,
      proteinG: 15.5,
      carbsG: 2.8,
      fatG: 8.0,
      fiberG: 2.3,
      sugarsG: 0.5,
      sodiumMg: 14,
      potassiumMg: 237,
      calciumMg: 350,
      ironMg: 2.8,
      magnesiumMg: 58,
      zincMg: 1.6,
      vitaminA_ug: 0,
      vitaminC_mg: 0.2,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 29,
    },
    glycemicIndex: 15,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'egg-whites-boiled',
    name: 'Hard Boiled Egg Whites (Pure Albumin)',
    hindiName: 'उबले अंडे की सफेदी',
    aliases: ['egg whites', 'boiled egg white', 'egg white', 'egg whites boiled'],
    category: 'Eggs & Complete Protein',
    source: 'USDA',
    cookingMethod: 'hard boiled and yolks completely removed',
    per100g: {
      kcal: 52,
      proteinG: 10.9,
      carbsG: 0.7,
      fatG: 0.2,
      fiberG: 0.0,
      sugarsG: 0.7,
      sodiumMg: 166,
      potassiumMg: 163,
      calciumMg: 7,
      ironMg: 0.1,
      magnesiumMg: 11,
      zincMg: 0.03,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0.1,
      folate_ug: 4,
    },
    glycemicIndex: 0,
    isVegetarian: false,
    isVegan: false,
  },

  // 4. More Fruits
  {
    id: 'mango-alphonso-fresh',
    name: 'Fresh Ripe Mango Slices (Alphonso / Kesar)',
    hindiName: 'पका हुआ आम',
    marathiName: 'हापूस आंबा',
    aliases: ['mango', 'ripe mango', 'alphonso mango', 'aam'],
    category: 'Fresh Fruits',
    source: 'IFCT',
    cookingMethod: 'fresh raw peeled fruit',
    per100g: {
      kcal: 65,
      proteinG: 0.8,
      carbsG: 15.0,
      fatG: 0.4,
      fiberG: 1.8,
      sugarsG: 13.5,
      sodiumMg: 2,
      potassiumMg: 168,
      calciumMg: 14,
      ironMg: 0.3,
      magnesiumMg: 12,
      zincMg: 0.1,
      vitaminA_ug: 180,
      vitaminC_mg: 36.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 43,
    },
    glycemicIndex: 51,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'guava-amrood',
    name: 'Fresh Guava with Seeds (Amrood / Peru)',
    hindiName: 'अमरूद',
    marathiName: 'पेरू',
    aliases: ['guava', 'amrood', 'peru fruit'],
    category: 'Fresh Fruits',
    source: 'IFCT',
    cookingMethod: 'raw whole fresh fruit',
    per100g: {
      kcal: 68,
      proteinG: 2.6,
      carbsG: 12.0,
      fatG: 1.0,
      fiberG: 5.4,
      sugarsG: 8.9,
      sodiumMg: 4,
      potassiumMg: 417,
      calciumMg: 20,
      ironMg: 0.3,
      magnesiumMg: 22,
      zincMg: 0.2,
      vitaminA_ug: 31,
      vitaminC_mg: 228.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 49,
    },
    glycemicIndex: 24,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'papaya-ripe',
    name: 'Fresh Ripe Papaya Cubes (Papita)',
    hindiName: 'पपीता',
    marathiName: 'पपई',
    aliases: ['papaya', 'papita', 'ripe papaya'],
    category: 'Fresh Fruits',
    source: 'IFCT',
    cookingMethod: 'fresh raw peeled cubes',
    per100g: {
      kcal: 43,
      proteinG: 0.5,
      carbsG: 10.8,
      fatG: 0.3,
      fiberG: 1.7,
      sugarsG: 7.8,
      sodiumMg: 8,
      potassiumMg: 182,
      calciumMg: 20,
      ironMg: 0.2,
      magnesiumMg: 21,
      zincMg: 0.1,
      vitaminA_ug: 47,
      vitaminC_mg: 60.9,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 38,
    },
    glycemicIndex: 38,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'pomegranate-arils',
    name: 'Fresh Pomegranate Arils (Anar ke Daane)',
    hindiName: 'अनार',
    marathiName: 'डाळिंब',
    aliases: ['pomegranate', 'anar', 'pomegranate arils', 'dalimb'],
    category: 'Fresh Fruits',
    source: 'IFCT',
    cookingMethod: 'fresh raw seed kernels',
    per100g: {
      kcal: 83,
      proteinG: 1.7,
      carbsG: 18.7,
      fatG: 1.2,
      fiberG: 4.0,
      sugarsG: 13.7,
      sodiumMg: 3,
      potassiumMg: 236,
      calciumMg: 10,
      ironMg: 0.4,
      magnesiumMg: 12,
      zincMg: 0.4,
      vitaminA_ug: 0,
      vitaminC_mg: 10.2,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 38,
    },
    glycemicIndex: 35,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'watermelon-tarbooj',
    name: 'Fresh Red Watermelon Slices (Tarbooj / Kalingad)',
    hindiName: 'तरबूज',
    marathiName: 'कलिंगड',
    aliases: ['watermelon', 'tarbooj', 'kalingad', 'fresh watermelon'],
    category: 'Fresh Fruits',
    source: 'IFCT',
    cookingMethod: 'fresh raw sliced melon',
    per100g: {
      kcal: 30,
      proteinG: 0.6,
      carbsG: 6.5,
      fatG: 0.2,
      fiberG: 0.4,
      sugarsG: 6.2,
      sodiumMg: 1,
      potassiumMg: 112,
      calciumMg: 7,
      ironMg: 0.2,
      magnesiumMg: 10,
      zincMg: 0.1,
      vitaminA_ug: 28,
      vitaminC_mg: 8.1,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 3,
    },
    glycemicIndex: 50,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },

  // 5. More Nuts & Fasting Items
  {
    id: 'cashews-kaju-raw',
    name: 'Raw Cashew Kernels (Kaju)',
    hindiName: 'काजू',
    aliases: ['cashews', 'cashew', 'kaju', 'raw cashews'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'raw unsalted kernels',
    per100g: {
      kcal: 553,
      proteinG: 18.2,
      carbsG: 30.2,
      fatG: 43.8,
      fiberG: 3.3,
      sugarsG: 5.9,
      sodiumMg: 12,
      potassiumMg: 660,
      calciumMg: 37,
      ironMg: 6.7,
      magnesiumMg: 292,
      zincMg: 5.8,
      vitaminA_ug: 0,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 25,
    },
    glycemicIndex: 25,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'pistachios-pista-raw',
    name: 'Raw Shelled Pistachios (Pista)',
    hindiName: 'पिस्ता',
    aliases: ['pistachios', 'pistachio', 'pista', 'raw pistachios'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'shelled raw kernels',
    per100g: {
      kcal: 560,
      proteinG: 20.2,
      carbsG: 27.2,
      fatG: 45.3,
      fiberG: 10.6,
      sugarsG: 7.7,
      sodiumMg: 1,
      potassiumMg: 1025,
      calciumMg: 105,
      ironMg: 3.9,
      magnesiumMg: 121,
      zincMg: 2.2,
      vitaminA_ug: 21,
      vitaminC_mg: 5.6,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 51,
    },
    glycemicIndex: 15,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'flaxseeds-alsi',
    name: 'Brown Flaxseeds (Alsi / Jawas)',
    hindiName: 'अलसी के बीज',
    marathiName: 'जवस',
    aliases: ['flaxseeds', 'flax seed', 'alsi', 'jawas', 'linseed'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'whole raw cleaned seeds',
    per100g: {
      kcal: 534,
      proteinG: 18.3,
      carbsG: 28.9,
      fatG: 42.2,
      fiberG: 27.3,
      sugarsG: 1.6,
      sodiumMg: 30,
      potassiumMg: 813,
      calciumMg: 255,
      ironMg: 5.7,
      magnesiumMg: 392,
      zincMg: 4.3,
      vitaminA_ug: 0,
      vitaminC_mg: 0.6,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 87,
    },
    glycemicIndex: 0,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'rajgira-atta-paratha',
    name: 'Rajgira Paratha (Amaranth Flour Vrat Flatbread)',
    hindiName: 'राजगिरा पराठा (उपवास)',
    aliases: ['rajgira paratha', 'amaranth paratha', 'vrat paratha rajgira'],
    category: 'Tubers & Fasting Items',
    source: 'IFCT',
    cookingMethod: 'amaranth flour combined with mashed boiled potato, roasted in pure cow ghee',
    per100g: {
      kcal: 275,
      proteinG: 7.5,
      carbsG: 46.0,
      fatG: 6.8,
      fiberG: 5.2,
      sugarsG: 1.2,
      sodiumMg: 140,
      potassiumMg: 310,
      calciumMg: 120,
      ironMg: 5.2,
      magnesiumMg: 145,
      zincMg: 2.1,
      vitaminA_ug: 15,
      vitaminC_mg: 2.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0,
      folate_ug: 45,
    },
    glycemicIndex: 45,
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
  },

  // 6. Sweets & Desserts
  {
    id: 'sooji-halwa-sheera',
    name: 'Sooji Ka Halwa / Sheera with Desi Ghee',
    hindiName: 'सूजी का हलवा / शीरा',
    marathiName: 'शिरा',
    aliases: ['sooji halwa', 'sheera', 'suji halwa', 'rava kesari'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'semolina slow roasted golden in cow ghee, boiled with sugar, saffron milk & dry fruits',
    per100g: {
      kcal: 340,
      proteinG: 4.2,
      carbsG: 52.0,
      fatG: 12.8,
      fiberG: 1.4,
      sugarsG: 34.0,
      sodiumMg: 25,
      potassiumMg: 95,
      calciumMg: 35,
      ironMg: 1.2,
      magnesiumMg: 24,
      zincMg: 0.6,
      vitaminA_ug: 95,
      vitaminC_mg: 0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.1,
      folate_ug: 18,
    },
    glycemicIndex: 68,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'kaju-katli',
    name: 'Kaju Katli (Silver Leaf Cashew Diamond Fudge)',
    hindiName: 'काजू कतली / काजू बर्फी',
    aliases: ['kaju katli', 'kaju barfi', 'cashew fudge'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'finely ground cashew nut paste cooked with sugar syrup and rolled into thin silvered diamond lozenges',
    per100g: {
      kcal: 440,
      proteinG: 9.5,
      carbsG: 56.0,
      fatG: 20.0,
      fiberG: 1.8,
      sugarsG: 48.0,
      sodiumMg: 15,
      potassiumMg: 320,
      calciumMg: 30,
      ironMg: 3.4,
      magnesiumMg: 140,
      zincMg: 2.8,
      vitaminA_ug: 0,
      vitaminC_mg: 0.2,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 15,
    },
    glycemicIndex: 60,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'rasmalai',
    name: 'Saffron Rasmalai (Chhena Patties in Thickened Milk)',
    hindiName: 'रसमलाई',
    aliases: ['rasmalai', 'ras malai', 'rossomalai'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'flattened cottage cheese discs soaked in clotted saffron-cardamom rabri milk',
    per100g: {
      kcal: 180,
      proteinG: 6.5,
      carbsG: 24.0,
      fatG: 6.5,
      fiberG: 0.2,
      sugarsG: 21.0,
      sodiumMg: 65,
      potassiumMg: 180,
      calciumMg: 210,
      ironMg: 0.5,
      magnesiumMg: 18,
      zincMg: 0.8,
      vitaminA_ug: 48,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.4,
      folate_ug: 8,
    },
    glycemicIndex: 64,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'jalebi-crispy',
    name: 'Crispy Saffron Jalebi in Sugar Syrup',
    hindiName: 'जलेबी',
    aliases: ['jalebi', 'crispy jalebi', 'garam jalebi'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'fermented maida spirals deep fried and plunged immediately into hot saffron sugar syrup',
    per100g: {
      kcal: 380,
      proteinG: 2.2,
      carbsG: 72.0,
      fatG: 9.5,
      fiberG: 0.4,
      sugarsG: 65.0,
      sodiumMg: 45,
      potassiumMg: 55,
      calciumMg: 22,
      ironMg: 0.8,
      magnesiumMg: 12,
      zincMg: 0.3,
      vitaminA_ug: 15,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 12,
    },
    glycemicIndex: 82,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'motichoor-ladoo',
    name: 'Motichoor Ladoo (Tiny Gram Flour Pearls in Ghee)',
    hindiName: 'मोतीचूर का लड्डू',
    aliases: ['motichoor ladoo', 'motichur laddu', 'boondi ladoo'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'microscopic gram flour boondi drops fried in ghee and bound with rose-cardamom sugar syrup',
    per100g: {
      kcal: 390,
      proteinG: 4.2,
      carbsG: 62.0,
      fatG: 14.0,
      fiberG: 1.5,
      sugarsG: 52.0,
      sodiumMg: 35,
      potassiumMg: 110,
      calciumMg: 28,
      ironMg: 1.2,
      magnesiumMg: 22,
      zincMg: 0.6,
      vitaminA_ug: 65,
      vitaminC_mg: 0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0,
      folate_ug: 15,
    },
    glycemicIndex: 75,
    isVegetarian: true,
    isVegan: false,
  },

  // 7. More Beverages
  {
    id: 'green-tea-unsweetened',
    name: 'Brewed Green Tea (Unsweetened)',
    hindiName: 'ग्रीन टी',
    aliases: ['green tea', 'brewed green tea', 'matcha brewed'],
    category: 'Beverages',
    source: 'USDA',
    cookingMethod: 'steeped organic green tea leaves in hot water',
    per100g: {
      kcal: 2,
      proteinG: 0.2,
      carbsG: 0.0,
      fatG: 0.0,
      fiberG: 0.0,
      sugarsG: 0.0,
      sodiumMg: 1,
      potassiumMg: 27,
      calciumMg: 0,
      ironMg: 0.02,
      magnesiumMg: 2,
      zincMg: 0.01,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 5,
    },
    glycemicIndex: 0,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'filter-coffee-milk',
    name: 'South Indian Filter Coffee with Milk & Sugar',
    hindiName: 'फिल्टर कॉफी',
    aliases: ['filter coffee', 'south indian coffee', 'kaapi', 'madras filter coffee'],
    category: 'Beverages',
    source: 'composite',
    cookingMethod: 'fresh chicory-coffee decoction frothed with boiled whole milk and sugar',
    per100g: {
      kcal: 75,
      proteinG: 2.2,
      carbsG: 10.5,
      fatG: 2.5,
      fiberG: 0.0,
      sugarsG: 9.8,
      sodiumMg: 35,
      potassiumMg: 140,
      calciumMg: 82,
      ironMg: 0.1,
      magnesiumMg: 12,
      zincMg: 0.3,
      vitaminA_ug: 24,
      vitaminC_mg: 0.2,
      vitaminD_ug: 0.05,
      vitaminB12_ug: 0.3,
      folate_ug: 5,
    },
    glycemicIndex: 54,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'nimbu-pani-shikanji',
    name: 'Fresh Nimbu Pani / Shikanji with Sugar & Black Salt',
    hindiName: 'नींबू पानी (शिकंजी)',
    aliases: ['nimbu pani', 'lemonade', 'shikanji', 'fresh lime water'],
    category: 'Beverages & Electrolytes',
    source: 'composite',
    cookingMethod: 'fresh squeezed lemon juice mixed with chilled water, sugar, roasted cumin & rock salt',
    per100g: {
      kcal: 42,
      proteinG: 0.2,
      carbsG: 10.0,
      fatG: 0.1,
      fiberG: 0.2,
      sugarsG: 9.5,
      sodiumMg: 120,
      potassiumMg: 45,
      calciumMg: 8,
      ironMg: 0.1,
      magnesiumMg: 4,
      zincMg: 0.05,
      vitaminA_ug: 2,
      vitaminC_mg: 18.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 6,
    },
    glycemicIndex: 45,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
];

// Verify Atwater check for all batch 2 rows
for (const row of batch2Rows) {
  const { kcal, proteinG, carbsG, fatG } = row.per100g;
  const calcAtwater = proteinG * 4 + carbsG * 4 + fatG * 9;
  const diff = Math.abs(kcal - calcAtwater);
  const relErr = diff / Math.max(1, kcal);
  if (kcal > 10 && relErr >= 0.12) {
    throw new Error(`Row ${row.name} failed Atwater: stated ${kcal} vs ${calcAtwater.toFixed(1)} (${(relErr * 100).toFixed(1)}%)`);
  }
}

console.log(`All ${batch2Rows.length} batch 2 rows strictly pass Atwater energy balance!`);

const targetFile = path.join(process.cwd(), 'src/data/nutritionTable.ts');
let content = fs.readFileSync(targetFile, 'utf8');

const lastBracketIndex = content.lastIndexOf('];');
if (lastBracketIndex === -1) {
  throw new Error("Could not find ending '];' in nutritionTable.ts");
}

const formattedAdditional = batch2Rows.map(r => JSON.stringify(r, null, 2)).join(',\n  ');
const newContent = content.slice(0, lastBracketIndex) + ',\n  ' + formattedAdditional + '\n];\n';

fs.writeFileSync(targetFile, newContent, 'utf8');
console.log("Successfully appended Batch 2 rows to nutritionTable.ts!");
