import fs from 'fs';
import path from 'path';

interface RawRow {
  id: string;
  name: string;
  hindiName?: string;
  marathiName?: string;
  aliases: string[];
  category: string;
  source: 'IFCT' | 'USDA' | 'composite';
  cookingMethod?: string;
  per100g: {
    kcal: number;
    proteinG: number;
    carbsG: number;
    fatG: number;
    fiberG: number;
    sugarsG: number | null;
    sodiumMg: number | null;
    potassiumMg: number | null;
    calciumMg: number | null;
    ironMg: number | null;
    magnesiumMg: number | null;
    zincMg: number | null;
    vitaminA_ug: number | null;
    vitaminC_mg: number | null;
    vitaminD_ug: number | null;
    vitaminB12_ug: number | null;
    folate_ug: number | null;
  };
  glycemicIndex?: string | number;
  isVegetarian?: boolean;
  isVegan?: boolean;
  isFastingSafe?: boolean;
}

const additionalRows: RawRow[] = [
  // 1. More Rices & Breads
  {
    id: 'rumali-roti',
    name: 'Rumali Roti (Thin Handkerchief Flatbread)',
    hindiName: 'रूमाली रोटी',
    aliases: ['rumali roti', 'roomali roti'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'tossed paper-thin and baked on inverted wok (kadai)',
    per100g: {
      kcal: 280,
      proteinG: 8.0,
      carbsG: 54.0,
      fatG: 3.5,
      fiberG: 3.2,
      sugarsG: 2.0,
      sodiumMg: 210,
      potassiumMg: 140,
      calciumMg: 35,
      ironMg: 2.1,
      magnesiumMg: 28,
      zincMg: 0.9,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 35,
    },
    glycemicIndex: 68,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'missi-roti',
    name: 'Missi Roti (Gram Flour & Wheat Spiced Flatbread)',
    hindiName: 'मिस्सी रोटी',
    aliases: ['missi roti', 'besan roti'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'roasted tawa flatbread made from wheat flour and chickpea besan with ajwain',
    per100g: {
      kcal: 290,
      proteinG: 13.0,
      carbsG: 45.0,
      fatG: 6.0,
      fiberG: 7.5,
      sugarsG: 2.5,
      sodiumMg: 240,
      potassiumMg: 320,
      calciumMg: 55,
      ironMg: 3.8,
      magnesiumMg: 75,
      zincMg: 1.8,
      vitaminA_ug: 8,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 55,
    },
    glycemicIndex: 45,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'makki-ki-roti',
    name: 'Makki ki Roti (Yellow Cornmeal Flatbread)',
    hindiName: 'मक्के की रोटी',
    aliases: ['makki ki roti', 'corn roti', 'makki roti', 'punjabi makki roti'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'hand-pressed maize flour flatbread tawa roasted with ghee',
    per100g: {
      kcal: 268,
      proteinG: 6.2,
      carbsG: 53.0,
      fatG: 3.5,
      fiberG: 6.5,
      sugarsG: 1.2,
      sodiumMg: 15,
      potassiumMg: 220,
      calciumMg: 20,
      ironMg: 2.4,
      magnesiumMg: 68,
      zincMg: 1.4,
      vitaminA_ug: 35,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 24,
    },
    glycemicIndex: 52,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'puri-wheat',
    name: 'Whole Wheat Puri (Deep Fried Puffed Bread)',
    hindiName: 'पूरी',
    marathiName: 'पुरी',
    aliases: ['puri', 'poori', 'puris', 'fried puri'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'deep fried whole wheat unleavened rounds in vegetable oil',
    per100g: {
      kcal: 355,
      proteinG: 7.2,
      carbsG: 45.0,
      fatG: 16.2,
      fiberG: 5.5,
      sugarsG: 1.5,
      sodiumMg: 160,
      potassiumMg: 190,
      calciumMg: 30,
      ironMg: 2.8,
      magnesiumMg: 52,
      zincMg: 1.3,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 28,
    },
    glycemicIndex: 65,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'bhatura',
    name: 'Punjabi Bhatura (Leavened Fried Bread)',
    hindiName: 'भटूरा',
    aliases: ['bhatura', 'bhature', 'chole bhature bread'],
    category: 'Staples & Flatbreads',
    source: 'IFCT',
    cookingMethod: 'deep fried fermented refined flour puffed bread',
    per100g: {
      kcal: 330,
      proteinG: 7.5,
      carbsG: 48.0,
      fatG: 12.0,
      fiberG: 2.2,
      sugarsG: 2.8,
      sodiumMg: 340,
      potassiumMg: 120,
      calciumMg: 45,
      ironMg: 2.2,
      magnesiumMg: 25,
      zincMg: 0.8,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 45,
    },
    glycemicIndex: 72,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'veg-pulao',
    name: 'Vegetable Pulao (Spiced Fragrant Basmati)',
    hindiName: 'वेज पुलाव',
    aliases: ['veg pulao', 'vegetable pulao', 'pulao', 'pilaf', 'peas pulao'],
    category: 'Staples & Rice',
    source: 'IFCT',
    cookingMethod: 'basmati rice cooked with whole garam spices, peas, carrots & light ghee',
    per100g: {
      kcal: 145,
      proteinG: 3.2,
      carbsG: 26.0,
      fatG: 3.0,
      fiberG: 1.8,
      sugarsG: 1.2,
      sodiumMg: 140,
      potassiumMg: 95,
      calciumMg: 18,
      ironMg: 0.9,
      magnesiumMg: 20,
      zincMg: 0.6,
      vitaminA_ug: 45,
      vitaminC_mg: 3.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 16,
    },
    glycemicIndex: 62,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'chicken-biryani-dum',
    name: 'Hyderabadi Chicken Dum Biryani',
    hindiName: 'चिकन बिरयानी',
    aliases: ['chicken biryani', 'murgh biryani', 'dum biryani', 'hyderabadi biryani'],
    category: 'Staples & Composite',
    source: 'IFCT',
    cookingMethod: 'layered basmati rice and marinated chicken cooked on slow dum with saffron & ghee',
    per100g: {
      kcal: 185,
      proteinG: 11.5,
      carbsG: 23.0,
      fatG: 5.2,
      fiberG: 1.4,
      sugarsG: 1.0,
      sodiumMg: 280,
      potassiumMg: 190,
      calciumMg: 25,
      ironMg: 1.4,
      magnesiumMg: 24,
      zincMg: 1.1,
      vitaminA_ug: 30,
      vitaminC_mg: 2.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.3,
      folate_ug: 18,
    },
    glycemicIndex: 58,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'mutton-biryani',
    name: 'Mutton Dum Biryani',
    hindiName: 'मटन बिरयानी',
    aliases: ['mutton biryani', 'gosht biryani', 'lamb biryani'],
    category: 'Staples & Composite',
    source: 'IFCT',
    cookingMethod: 'fragrant basmati rice layered with spiced tender goat meat on dum',
    per100g: {
      kcal: 215,
      proteinG: 12.0,
      carbsG: 22.0,
      fatG: 8.5,
      fiberG: 1.2,
      sugarsG: 0.9,
      sodiumMg: 310,
      potassiumMg: 210,
      calciumMg: 22,
      ironMg: 1.9,
      magnesiumMg: 26,
      zincMg: 2.1,
      vitaminA_ug: 25,
      vitaminC_mg: 1.5,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 1.2,
      folate_ug: 15,
    },
    glycemicIndex: 55,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'veg-biryani',
    name: 'Vegetable Dum Biryani',
    hindiName: 'वेज बिरयानी',
    aliases: ['veg biryani', 'vegetable biryani'],
    category: 'Staples & Composite',
    source: 'IFCT',
    cookingMethod: 'basmati rice layered with spiced vegetables, paneer & fried onions',
    per100g: {
      kcal: 155,
      proteinG: 3.8,
      carbsG: 26.0,
      fatG: 3.8,
      fiberG: 2.4,
      sugarsG: 1.8,
      sodiumMg: 220,
      potassiumMg: 140,
      calciumMg: 38,
      ironMg: 1.2,
      magnesiumMg: 25,
      zincMg: 0.8,
      vitaminA_ug: 55,
      vitaminC_mg: 4.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.1,
      folate_ug: 22,
    },
    glycemicIndex: 56,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'curd-rice',
    name: 'South Indian Curd Rice (Thayir Sadam / Daddojanam)',
    hindiName: 'दही चावल',
    aliases: ['curd rice', 'thayir sadam', 'daddojanam', 'bagala bath'],
    category: 'Staples & Rice',
    source: 'IFCT',
    cookingMethod: 'soft mashed rice mixed with fresh curd and tempered with mustard seeds, ginger, curry leaves & asafoetida',
    per100g: {
      kcal: 135,
      proteinG: 3.5,
      carbsG: 21.0,
      fatG: 4.1,
      fiberG: 0.6,
      sugarsG: 2.8,
      sodiumMg: 180,
      potassiumMg: 115,
      calciumMg: 95,
      ironMg: 0.5,
      magnesiumMg: 18,
      zincMg: 0.5,
      vitaminA_ug: 20,
      vitaminC_mg: 1.2,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.3,
      folate_ug: 12,
    },
    glycemicIndex: 54,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'lemon-rice',
    name: 'South Indian Lemon Rice (Chitranna)',
    hindiName: 'नींबू चावल',
    aliases: ['lemon rice', 'chitranna', 'elamichai sadam'],
    category: 'Staples & Rice',
    source: 'IFCT',
    cookingMethod: 'steamed rice tossed with lemon juice, turmeric, crunchy peanuts & mustard curry leaves tadka',
    per100g: {
      kcal: 160,
      proteinG: 2.8,
      carbsG: 27.0,
      fatG: 4.5,
      fiberG: 1.1,
      sugarsG: 0.8,
      sodiumMg: 190,
      potassiumMg: 75,
      calciumMg: 16,
      ironMg: 0.9,
      magnesiumMg: 22,
      zincMg: 0.6,
      vitaminA_ug: 15,
      vitaminC_mg: 8.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 14,
    },
    glycemicIndex: 58,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'ven-pongal',
    name: 'South Indian Ven Pongal (Ghee Lentil Rice)',
    hindiName: 'पोंगल (घी दाल पोंगल)',
    aliases: ['pongal', 'ven pongal', 'khara pongal', 'ghee pongal'],
    category: 'Staples & Composite',
    source: 'IFCT',
    cookingMethod: 'rice and yellow moong dal cooked to soft mash, tempered with black peppercorns, cumin, ginger, cashews & pure ghee',
    per100g: {
      kcal: 165,
      proteinG: 4.2,
      carbsG: 25.0,
      fatG: 5.3,
      fiberG: 1.8,
      sugarsG: 0.6,
      sodiumMg: 160,
      potassiumMg: 130,
      calciumMg: 24,
      ironMg: 1.2,
      magnesiumMg: 30,
      zincMg: 0.8,
      vitaminA_ug: 35,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0,
      folate_ug: 26,
    },
    glycemicIndex: 56,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'bisi-bele-bath',
    name: 'Karnataka Bisi Bele Bath (Spiced Lentil Rice)',
    hindiName: 'बिसी बेले भात',
    aliases: ['bisi bele bath', 'bisibelebath', 'bisi bele bhath'],
    category: 'Staples & Composite',
    source: 'IFCT',
    cookingMethod: 'rice and toor dal simmered with tamarind, mixed vegetables, freshly ground spice paste & ghee',
    per100g: {
      kcal: 150,
      proteinG: 4.5,
      carbsG: 24.0,
      fatG: 3.9,
      fiberG: 2.6,
      sugarsG: 2.1,
      sodiumMg: 240,
      potassiumMg: 160,
      calciumMg: 32,
      ironMg: 1.4,
      magnesiumMg: 32,
      zincMg: 0.8,
      vitaminA_ug: 40,
      vitaminC_mg: 4.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 30,
    },
    glycemicIndex: 50,
    isVegetarian: true,
    isVegan: false,
  },

  // 2. More South Indian Crepes & Chutneys
  {
    id: 'rava-dosa',
    name: 'Crispy Rava Dosa (Semolina Crepe)',
    hindiName: 'रवा डोसा',
    aliases: ['rava dosa', 'sooji dosa', 'semolina dosa'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'thin batter of semolina, rice flour and spices poured on very hot tawa with oil',
    per100g: {
      kcal: 210,
      proteinG: 4.5,
      carbsG: 34.0,
      fatG: 6.2,
      fiberG: 2.0,
      sugarsG: 1.2,
      sodiumMg: 230,
      potassiumMg: 90,
      calciumMg: 24,
      ironMg: 1.4,
      magnesiumMg: 26,
      zincMg: 0.7,
      vitaminA_ug: 10,
      vitaminC_mg: 1.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 18,
    },
    glycemicIndex: 65,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'pesarattu',
    name: 'Andhra Pesarattu (Whole Green Moong Dosa)',
    hindiName: 'पेसरट्टू (मूंग दाल चीला / डोसा)',
    aliases: ['pesarattu', 'green moong dosa', 'moong dal dosa', 'mlasarattu'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'soaked whole green gram batter ground with ginger and cumin, cooked crisp on tawa',
    per100g: {
      kcal: 185,
      proteinG: 9.2,
      carbsG: 28.0,
      fatG: 3.9,
      fiberG: 5.2,
      sugarsG: 1.5,
      sodiumMg: 190,
      potassiumMg: 280,
      calciumMg: 42,
      ironMg: 2.5,
      magnesiumMg: 56,
      zincMg: 1.4,
      vitaminA_ug: 20,
      vitaminC_mg: 3.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 65,
    },
    glycemicIndex: 38,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'chutney-coconut',
    name: 'South Indian Coconut Chutney',
    hindiName: 'नारियल की चटनी',
    aliases: ['coconut chutney', 'white chutney', 'nariyal chutney', 'idli chutney'],
    category: 'Condiments',
    source: 'IFCT',
    cookingMethod: 'fresh grated coconut ground with roasted chana dal, green chillies & mustard-curry leaf tadka',
    per100g: {
      kcal: 195,
      proteinG: 2.2,
      carbsG: 8.0,
      fatG: 17.0,
      fiberG: 4.5,
      sugarsG: 3.2,
      sodiumMg: 280,
      potassiumMg: 190,
      calciumMg: 18,
      ironMg: 1.4,
      magnesiumMg: 24,
      zincMg: 0.8,
      vitaminA_ug: 12,
      vitaminC_mg: 3.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 18,
    },
    glycemicIndex: 35,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'chutney-peanut',
    name: 'Andhra Style Peanut Chutney (Palli Chutney)',
    hindiName: 'मूंगफली की चटनी',
    aliases: ['peanut chutney', 'palli chutney', 'groundnut chutney', 'shengdana chutney'],
    category: 'Condiments',
    source: 'IFCT',
    cookingMethod: 'roasted peanuts blended with green chillies, tamarind and garlic tempered in oil',
    per100g: {
      kcal: 265,
      proteinG: 9.5,
      carbsG: 14.0,
      fatG: 19.0,
      fiberG: 3.8,
      sugarsG: 2.5,
      sodiumMg: 310,
      potassiumMg: 340,
      calciumMg: 45,
      ironMg: 2.2,
      magnesiumMg: 82,
      zincMg: 1.6,
      vitaminA_ug: 10,
      vitaminC_mg: 2.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 65,
    },
    glycemicIndex: 22,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'chutney-tomato-onion',
    name: 'Spicy Tomato Onion Chutney (Kara Chutney)',
    hindiName: 'टमाटर प्याज की चटनी',
    aliases: ['tomato chutney', 'kara chutney', 'onion tomato chutney', 'red chutney dosa'],
    category: 'Condiments',
    source: 'IFCT',
    cookingMethod: 'sautéed onions, ripe tomatoes and dried red chillies ground with tamarind and tempered',
    per100g: {
      kcal: 85,
      proteinG: 1.8,
      carbsG: 11.0,
      fatG: 3.8,
      fiberG: 2.2,
      sugarsG: 4.8,
      sodiumMg: 290,
      potassiumMg: 220,
      calciumMg: 24,
      ironMg: 1.1,
      magnesiumMg: 18,
      zincMg: 0.4,
      vitaminA_ug: 65,
      vitaminC_mg: 16.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 24,
    },
    glycemicIndex: 25,
    isVegetarian: true,
    isVegan: true,
  },

  // 3. Regional Snacks & Crepes
  {
    id: 'misal-curry',
    name: 'Kolhapuri Misal Curry (Sprouted Matki Stew)',
    hindiName: 'मिसल करी (कट / रस्सा)',
    marathiName: 'मिसळ रस्सा',
    aliases: ['misal', 'kolhapuri misal', 'puneri misal', 'misal rassa', 'misal tarri'],
    category: 'Street Food & Snacks',
    source: 'IFCT',
    cookingMethod: 'sprouted moth beans cooked in fiery onion-garlic-coconut gravy with red oil layer',
    per100g: {
      kcal: 195,
      proteinG: 7.2,
      carbsG: 24.0,
      fatG: 7.8,
      fiberG: 5.4,
      sugarsG: 2.2,
      sodiumMg: 380,
      potassiumMg: 310,
      calciumMg: 48,
      ironMg: 3.2,
      magnesiumMg: 52,
      zincMg: 1.5,
      vitaminA_ug: 40,
      vitaminC_mg: 8.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 55,
    },
    glycemicIndex: 40,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'matki-usal',
    name: 'Sprouted Matki Usal (Moth Bean Curry)',
    hindiName: 'मटकी उसल',
    marathiName: 'मटकीची उसळ',
    aliases: ['usal', 'matki usal', 'sprouted usal', 'moth bean usal'],
    category: 'Dals & Legumes',
    source: 'IFCT',
    cookingMethod: 'sprouted moth beans sautéed with onions, mustard seeds, turmeric & grated coconut',
    per100g: {
      kcal: 125,
      proteinG: 7.5,
      carbsG: 18.0,
      fatG: 2.6,
      fiberG: 6.2,
      sugarsG: 1.8,
      sodiumMg: 210,
      potassiumMg: 380,
      calciumMg: 56,
      ironMg: 3.6,
      magnesiumMg: 64,
      zincMg: 1.6,
      vitaminA_ug: 25,
      vitaminC_mg: 12.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 70,
    },
    glycemicIndex: 32,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'kothimbir-vadi',
    name: 'Maharashtrian Kothimbir Vadi',
    hindiName: 'कोथिंबीर वड़ी',
    marathiName: 'कोथिंबीर वडी',
    aliases: ['kothimbir vadi', 'coriander cake', 'kothambir vadi'],
    category: 'Street Food & Snacks',
    source: 'IFCT',
    cookingMethod: 'fresh coriander leaves mixed with gram flour batter, steamed and shallow fried',
    per100g: {
      kcal: 210,
      proteinG: 7.2,
      carbsG: 26.0,
      fatG: 8.4,
      fiberG: 4.8,
      sugarsG: 2.0,
      sodiumMg: 290,
      potassiumMg: 260,
      calciumMg: 95,
      ironMg: 3.4,
      magnesiumMg: 55,
      zincMg: 1.4,
      vitaminA_ug: 240,
      vitaminC_mg: 28.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 65,
    },
    glycemicIndex: 42,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'sabudana-vada',
    name: 'Sabudana Vada (Deep Fried Tapioca Peanut Patty)',
    hindiName: 'साबूदाना वड़ा',
    marathiName: 'साबुदाणा वडा',
    aliases: ['sabudana vada', 'sago vada', 'sabudana wada'],
    category: 'Street Food & Snacks',
    source: 'IFCT',
    cookingMethod: 'soaked sago and mashed potatoes with crushed peanuts deep fried until crisp',
    per100g: {
      kcal: 310,
      proteinG: 4.5,
      carbsG: 42.0,
      fatG: 13.8,
      fiberG: 2.8,
      sugarsG: 1.5,
      sodiumMg: 260,
      potassiumMg: 240,
      calciumMg: 42,
      ironMg: 1.8,
      magnesiumMg: 52,
      zincMg: 1.0,
      vitaminA_ug: 12,
      vitaminC_mg: 5.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 25,
    },
    glycemicIndex: 70,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'dhokla-khaman',
    name: 'Gujarati Khaman Dhokla (Steamed Gram Flour Cake)',
    hindiName: 'खमन ढोकला',
    aliases: ['dhokla', 'khaman', 'khaman dhokla', 'steamed dhokla'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'fermented chickpea flour batter steamed spongy and tempered with mustard, green chillies & sesame',
    per100g: {
      kcal: 160,
      proteinG: 6.5,
      carbsG: 24.0,
      fatG: 4.2,
      fiberG: 3.2,
      sugarsG: 4.5,
      sodiumMg: 380,
      potassiumMg: 160,
      calciumMg: 35,
      ironMg: 1.8,
      magnesiumMg: 40,
      zincMg: 1.1,
      vitaminA_ug: 10,
      vitaminC_mg: 3.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 38,
    },
    glycemicIndex: 45,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'khandvi',
    name: 'Gujarati Khandvi (Steamed Besan & Buttermilk Rolls)',
    hindiName: 'खांडवी',
    aliases: ['khandvi', 'gujarati khandvi', 'patuli'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'cooked besan-buttermilk paste spread thin, rolled into tight cylinders and tempered with sesame seeds',
    per100g: {
      kcal: 155,
      proteinG: 6.0,
      carbsG: 18.0,
      fatG: 6.5,
      fiberG: 2.8,
      sugarsG: 2.5,
      sodiumMg: 280,
      potassiumMg: 180,
      calciumMg: 75,
      ironMg: 1.6,
      magnesiumMg: 38,
      zincMg: 1.0,
      vitaminA_ug: 25,
      vitaminC_mg: 2.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.2,
      folate_ug: 32,
    },
    glycemicIndex: 40,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'besan-chilla',
    name: 'Besan Chilla (Savory Gram Flour Crepe)',
    hindiName: 'बेसन का चीला',
    aliases: ['besan chilla', 'besan cheela', 'gram flour pancake', 'besan puda'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'spiced chickpea flour batter pan-roasted on tawa with onions, tomatoes & coriander',
    per100g: {
      kcal: 190,
      proteinG: 9.8,
      carbsG: 24.0,
      fatG: 5.9,
      fiberG: 4.8,
      sugarsG: 2.2,
      sodiumMg: 260,
      potassiumMg: 290,
      calciumMg: 45,
      ironMg: 2.9,
      magnesiumMg: 60,
      zincMg: 1.5,
      vitaminA_ug: 20,
      vitaminC_mg: 6.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 58,
    },
    glycemicIndex: 35,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'moong-dal-chilla',
    name: 'Moong Dal Chilla (Yellow Lentil Crepe)',
    hindiName: 'मूंग दाल चीला',
    aliases: ['moong dal chilla', 'moong dal cheela', 'moonglet'],
    category: 'Breakfast & Snacks',
    source: 'IFCT',
    cookingMethod: 'soaked ground yellow moong dal cooked with light oil on tawa',
    per100g: {
      kcal: 180,
      proteinG: 11.2,
      carbsG: 23.0,
      fatG: 4.8,
      fiberG: 4.5,
      sugarsG: 1.8,
      sodiumMg: 220,
      potassiumMg: 310,
      calciumMg: 38,
      ironMg: 2.8,
      magnesiumMg: 65,
      zincMg: 1.6,
      vitaminA_ug: 18,
      vitaminC_mg: 4.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 68,
    },
    glycemicIndex: 30,
    isVegetarian: true,
    isVegan: true,
  },

  // 4. Sabzis & Curries
  {
    id: 'aloo-matar',
    name: 'Aloo Matar (Potato & Green Peas Curry)',
    hindiName: 'आलू मटर',
    aliases: ['aloo matar', 'alu matar', 'potato peas curry', 'aloo mutter'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'cubed potatoes and green peas simmered in onion-tomato-ginger gravy',
    per100g: {
      kcal: 95,
      proteinG: 2.8,
      carbsG: 15.0,
      fatG: 2.6,
      fiberG: 3.2,
      sugarsG: 3.0,
      sodiumMg: 220,
      potassiumMg: 290,
      calciumMg: 24,
      ironMg: 1.2,
      magnesiumMg: 26,
      zincMg: 0.6,
      vitaminA_ug: 35,
      vitaminC_mg: 14.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 35,
    },
    glycemicIndex: 48,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'aloo-methi',
    name: 'Aloo Methi (Potato with Fresh Fenugreek Leaves)',
    hindiName: 'आलू मेथी',
    aliases: ['aloo methi', 'alu methi', 'potato fenugreek'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'boiled diced potatoes stir-fried with fresh chopped fenugreek greens in mustard oil',
    per100g: {
      kcal: 105,
      proteinG: 2.5,
      carbsG: 14.0,
      fatG: 4.3,
      fiberG: 3.6,
      sugarsG: 1.5,
      sodiumMg: 190,
      potassiumMg: 340,
      calciumMg: 65,
      ironMg: 2.4,
      magnesiumMg: 38,
      zincMg: 0.8,
      vitaminA_ug: 95,
      vitaminC_mg: 18.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 45,
    },
    glycemicIndex: 42,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'lauki-sabzi',
    name: 'Lauki Ki Sabzi (Bottle Gourd Curry with Cumin)',
    hindiName: 'लौकी की सब्जी (घिया)',
    marathiName: 'दुधी भोपळ्याची भाजी',
    aliases: ['lauki', 'lauki sabzi', 'ghiya', 'doodhi', 'bottle gourd curry'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'cubed bottle gourd pressure cooked with cumin, turmeric & green chillies in minimal oil',
    per100g: {
      kcal: 45,
      proteinG: 1.2,
      carbsG: 5.5,
      fatG: 2.0,
      fiberG: 2.0,
      sugarsG: 2.5,
      sodiumMg: 140,
      potassiumMg: 190,
      calciumMg: 22,
      ironMg: 0.6,
      magnesiumMg: 16,
      zincMg: 0.3,
      vitaminA_ug: 12,
      vitaminC_mg: 8.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 18,
    },
    glycemicIndex: 20,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'torai-sabzi',
    name: 'Torai Ki Sabzi (Ridge Gourd Masala)',
    hindiName: 'तोरई की सब्जी (तुरई)',
    aliases: ['torai', 'turai', 'ridge gourd', 'tori sabzi'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'peeled ridge gourd simmered with cumin and crushed coriander seeds',
    per100g: {
      kcal: 42,
      proteinG: 1.1,
      carbsG: 5.0,
      fatG: 1.9,
      fiberG: 1.8,
      sugarsG: 2.2,
      sodiumMg: 130,
      potassiumMg: 170,
      calciumMg: 18,
      ironMg: 0.5,
      magnesiumMg: 14,
      zincMg: 0.3,
      vitaminA_ug: 20,
      vitaminC_mg: 6.5,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 16,
    },
    glycemicIndex: 18,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'karela-sabzi',
    name: 'Karela Pyaz Sabzi (Stir-Fried Bitter Gourd with Onions)',
    hindiName: 'करेले की सब्जी',
    aliases: ['karela', 'karela sabzi', 'bitter gourd', 'karele ki sabzi'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'sliced bitter gourd sautéed slowly with onions, amchur, fennel and mustard oil',
    per100g: {
      kcal: 78,
      proteinG: 2.0,
      carbsG: 8.5,
      fatG: 4.0,
      fiberG: 3.5,
      sugarsG: 2.8,
      sodiumMg: 160,
      potassiumMg: 280,
      calciumMg: 35,
      ironMg: 1.4,
      magnesiumMg: 28,
      zincMg: 0.5,
      vitaminA_ug: 45,
      vitaminC_mg: 38.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 35,
    },
    glycemicIndex: 15,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'kaddu-sabzi',
    name: 'Kaddu Ki Sabzi (Sweet & Sour Yellow Pumpkin)',
    hindiName: 'कद्दू की सब्जी (सीताफल / पेठा)',
    aliases: ['kaddu', 'kaddu sabzi', 'pumpkin sabzi', 'sitaphal sabzi'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'yellow pumpkin cooked with fenugreek seeds (methi dana), amchur & jaggery in mustard oil',
    per100g: {
      kcal: 68,
      proteinG: 1.2,
      carbsG: 11.0,
      fatG: 2.1,
      fiberG: 2.2,
      sugarsG: 5.5,
      sodiumMg: 150,
      potassiumMg: 260,
      calciumMg: 26,
      ironMg: 0.9,
      magnesiumMg: 19,
      zincMg: 0.4,
      vitaminA_ug: 380,
      vitaminC_mg: 12.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 22,
    },
    glycemicIndex: 40,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'cabbage-sabzi',
    name: 'Patta Gobhi Sabzi (Cabbage & Peas Stir Fry)',
    hindiName: 'पत्ता गोभी की सब्जी',
    aliases: ['cabbage sabzi', 'patta gobhi', 'band gobhi', 'cabbage peas'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'shredded cabbage and green peas tempered with cumin, green chillies & turmeric',
    per100g: {
      kcal: 65,
      proteinG: 1.8,
      carbsG: 7.2,
      fatG: 3.2,
      fiberG: 2.8,
      sugarsG: 3.2,
      sodiumMg: 140,
      potassiumMg: 210,
      calciumMg: 38,
      ironMg: 0.8,
      magnesiumMg: 18,
      zincMg: 0.4,
      vitaminA_ug: 15,
      vitaminC_mg: 26.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 32,
    },
    glycemicIndex: 20,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'sarson-ka-saag',
    name: 'Punjabi Sarson Ka Saag (Mustard Greens with White Butter)',
    hindiName: 'सरसों का साग',
    aliases: ['sarson ka saag', 'sarson saag', 'mustard greens curry'],
    category: 'Vegetables & Greens',
    source: 'IFCT',
    cookingMethod: 'mustard greens slow simmered with bathua, spinach & maize flour, tempered with garlic & desi ghee',
    per100g: {
      kcal: 115,
      proteinG: 3.5,
      carbsG: 8.5,
      fatG: 7.3,
      fiberG: 4.2,
      sugarsG: 1.8,
      sodiumMg: 220,
      potassiumMg: 340,
      calciumMg: 140,
      ironMg: 3.8,
      magnesiumMg: 45,
      zincMg: 1.1,
      vitaminA_ug: 480,
      vitaminC_mg: 35.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0,
      folate_ug: 85,
    },
    glycemicIndex: 22,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'kadai-paneer',
    name: 'Kadai Paneer (Bell Peppers & Cottage Cheese)',
    hindiName: 'कढ़ाई पनीर',
    aliases: ['kadai paneer', 'karahi paneer'],
    category: 'Dairy & Sabzi',
    source: 'IFCT',
    cookingMethod: 'paneer cubes tossed with chunky capsicum, onions and freshly pounded coriander-red chilli kadai masala',
    per100g: {
      kcal: 195,
      proteinG: 11.5,
      carbsG: 7.5,
      fatG: 13.0,
      fiberG: 2.2,
      sugarsG: 3.2,
      sodiumMg: 310,
      potassiumMg: 210,
      calciumMg: 260,
      ironMg: 1.4,
      magnesiumMg: 34,
      zincMg: 1.3,
      vitaminA_ug: 140,
      vitaminC_mg: 24.0,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 0.6,
      folate_ug: 28,
    },
    glycemicIndex: 22,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'paneer-tikka-grilled',
    name: 'Tandoori Paneer Tikka (Grilled Cottage Cheese Skewers)',
    hindiName: 'पनीर टिक्का',
    aliases: ['paneer tikka', 'tandoori paneer tikka', 'grilled paneer'],
    category: 'Dairy & High-Protein',
    source: 'IFCT',
    cookingMethod: 'hung curd and ajwain marinated paneer blocks roasted in clay oven with bell peppers & onions',
    per100g: {
      kcal: 210,
      proteinG: 14.5,
      carbsG: 5.8,
      fatG: 14.2,
      fiberG: 1.5,
      sugarsG: 2.5,
      sodiumMg: 340,
      potassiumMg: 180,
      calciumMg: 340,
      ironMg: 1.2,
      magnesiumMg: 32,
      zincMg: 1.5,
      vitaminA_ug: 110,
      vitaminC_mg: 8.0,
      vitaminD_ug: 0.3,
      vitaminB12_ug: 0.7,
      folate_ug: 22,
    },
    glycemicIndex: 15,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'mushroom-matar',
    name: 'Mushroom Matar Masala',
    hindiName: 'मशरूम मटर मसाला',
    aliases: ['mushroom matar', 'matar mushroom', 'mushroom curry'],
    category: 'Vegetables & Sabzis',
    source: 'IFCT',
    cookingMethod: 'fresh button mushrooms and tender green peas in spicy onion-tomato gravy',
    per100g: {
      kcal: 82,
      proteinG: 4.2,
      carbsG: 8.5,
      fatG: 3.4,
      fiberG: 2.8,
      sugarsG: 2.9,
      sodiumMg: 210,
      potassiumMg: 310,
      calciumMg: 28,
      ironMg: 1.5,
      magnesiumMg: 22,
      zincMg: 0.8,
      vitaminA_ug: 25,
      vitaminC_mg: 9.0,
      vitaminD_ug: 0.5,
      vitaminB12_ug: 0.1,
      folate_ug: 42,
    },
    glycemicIndex: 25,
    isVegetarian: true,
    isVegan: true,
  },
  {
    id: 'soya-chaap-curry',
    name: 'Soya Chaap Masala Gravy',
    hindiName: 'सोया चाप मसाला',
    aliases: ['soya chaap', 'soya chaap curry', 'soya chap'],
    category: 'Plant Protein',
    source: 'composite',
    cookingMethod: 'soy flour and gluten protein skewers simmered in rich spiced tomato-onion-cashew gravy',
    per100g: {
      kcal: 165,
      proteinG: 12.5,
      carbsG: 14.0,
      fatG: 6.5,
      fiberG: 3.8,
      sugarsG: 2.4,
      sodiumMg: 320,
      potassiumMg: 260,
      calciumMg: 85,
      ironMg: 2.8,
      magnesiumMg: 42,
      zincMg: 1.4,
      vitaminA_ug: 30,
      vitaminC_mg: 4.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 30,
    },
    glycemicIndex: 28,
    isVegetarian: true,
    isVegan: true,
  },

  // 5. Non-Vegetarian Curries & Poultry
  {
    id: 'butter-chicken',
    name: 'Murgh Makhani (Butter Chicken)',
    hindiName: 'बटर चिकन (मुर्ग मखनी)',
    aliases: ['butter chicken', 'murgh makhani'],
    category: 'Poultry & Meat',
    source: 'IFCT',
    cookingMethod: 'tandoori chicken pieces simmered in silky tomato puree with butter, cream, cashew paste & kasoori methi',
    per100g: {
      kcal: 215,
      proteinG: 15.0,
      carbsG: 7.5,
      fatG: 13.8,
      fiberG: 1.2,
      sugarsG: 3.8,
      sodiumMg: 360,
      potassiumMg: 230,
      calciumMg: 45,
      ironMg: 1.3,
      magnesiumMg: 24,
      zincMg: 1.2,
      vitaminA_ug: 95,
      vitaminC_mg: 3.5,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 0.4,
      folate_ug: 16,
    },
    glycemicIndex: 25,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'chicken-korma',
    name: 'Shahi Chicken Korma (Nut Gravy)',
    hindiName: 'चिकन कोरमा',
    aliases: ['chicken korma', 'shahi korma', 'murgh korma'],
    category: 'Poultry & Meat',
    source: 'IFCT',
    cookingMethod: 'braised chicken simmered in yogurt, brown onion and almond-poppy seed paste',
    per100g: {
      kcal: 230,
      proteinG: 16.0,
      carbsG: 6.0,
      fatG: 15.8,
      fiberG: 1.0,
      sugarsG: 2.2,
      sodiumMg: 330,
      potassiumMg: 250,
      calciumMg: 52,
      ironMg: 1.4,
      magnesiumMg: 28,
      zincMg: 1.4,
      vitaminA_ug: 40,
      vitaminC_mg: 2.0,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 0.4,
      folate_ug: 14,
    },
    glycemicIndex: 20,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'chicken-saagwala',
    name: 'Chicken Saagwala (Chicken Cooked in Spinach Puree)',
    hindiName: 'चिकन सागवाला (पालक चिकन)',
    aliases: ['chicken saag', 'chicken saagwala', 'palak chicken', 'saag chicken'],
    category: 'Poultry & Meat',
    source: 'IFCT',
    cookingMethod: 'chicken chunks cooked with spiced blanched spinach puree',
    per100g: {
      kcal: 155,
      proteinG: 18.0,
      carbsG: 4.0,
      fatG: 7.3,
      fiberG: 2.1,
      sugarsG: 1.5,
      sodiumMg: 290,
      potassiumMg: 360,
      calciumMg: 95,
      ironMg: 2.8,
      magnesiumMg: 45,
      zincMg: 1.3,
      vitaminA_ug: 320,
      vitaminC_mg: 14.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.4,
      folate_ug: 55,
    },
    glycemicIndex: 15,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'chicken-keema',
    name: 'Chicken Keema Matar (Minced Chicken with Peas)',
    hindiName: 'चिकन कीमा मटर',
    aliases: ['chicken keema', 'murgh keema', 'minced chicken'],
    category: 'Poultry & Meat',
    source: 'IFCT',
    cookingMethod: 'minced chicken breast cooked dry-style with onions, green peas, whole garam masala & mint',
    per100g: {
      kcal: 175,
      proteinG: 19.0,
      carbsG: 3.5,
      fatG: 9.3,
      fiberG: 1.4,
      sugarsG: 1.5,
      sodiumMg: 280,
      potassiumMg: 290,
      calciumMg: 28,
      ironMg: 1.6,
      magnesiumMg: 28,
      zincMg: 1.5,
      vitaminA_ug: 25,
      vitaminC_mg: 4.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.4,
      folate_ug: 16,
    },
    glycemicIndex: 12,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'mutton-rogan-josh',
    name: 'Kashmiri Mutton Rogan Josh',
    hindiName: 'रोगन जोश',
    aliases: ['rogan josh', 'mutton rogan josh', 'kashmiri rogan josh'],
    category: 'Poultry & Meat',
    source: 'IFCT',
    cookingMethod: 'braised lamb cooked in yogurt, Kashmiri red chillies, fennel and dried ginger',
    per100g: {
      kcal: 225,
      proteinG: 17.0,
      carbsG: 4.0,
      fatG: 15.5,
      fiberG: 1.1,
      sugarsG: 1.8,
      sodiumMg: 340,
      potassiumMg: 270,
      calciumMg: 32,
      ironMg: 2.8,
      magnesiumMg: 26,
      zincMg: 3.6,
      vitaminA_ug: 35,
      vitaminC_mg: 2.0,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 2.1,
      folate_ug: 10,
    },
    glycemicIndex: 10,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'egg-curry-dhaba',
    name: 'Dhaba Style Boiled Egg Curry',
    hindiName: 'अंडा करी',
    aliases: ['egg curry', 'anda curry', 'boiled egg curry'],
    category: 'Eggs & Complete Protein',
    source: 'IFCT',
    cookingMethod: 'hard boiled eggs pan-fried until golden, simmered in spicy onion-tomato masala gravy',
    per100g: {
      kcal: 145,
      proteinG: 9.5,
      carbsG: 4.5,
      fatG: 9.8,
      fiberG: 1.2,
      sugarsG: 1.8,
      sodiumMg: 310,
      potassiumMg: 190,
      calciumMg: 52,
      ironMg: 1.6,
      magnesiumMg: 18,
      zincMg: 1.1,
      vitaminA_ug: 110,
      vitaminC_mg: 3.5,
      vitaminD_ug: 1.4,
      vitaminB12_ug: 0.8,
      folate_ug: 32,
    },
    glycemicIndex: 8,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'egg-omelette',
    name: 'Indian Masala Omelette',
    hindiName: 'मसाला आमलेट',
    aliases: ['omelette', 'masala omelette', 'omelet', 'egg omelette'],
    category: 'Eggs & Complete Protein',
    source: 'IFCT',
    cookingMethod: 'beaten whole eggs whisked with chopped onions, green chillies & tomatoes, cooked in oil on tawa',
    per100g: {
      kcal: 185,
      proteinG: 11.0,
      carbsG: 2.8,
      fatG: 14.2,
      fiberG: 0.6,
      sugarsG: 1.2,
      sodiumMg: 280,
      potassiumMg: 170,
      calciumMg: 62,
      ironMg: 1.8,
      magnesiumMg: 15,
      zincMg: 1.2,
      vitaminA_ug: 140,
      vitaminC_mg: 3.5,
      vitaminD_ug: 1.6,
      vitaminB12_ug: 0.9,
      folate_ug: 35,
    },
    glycemicIndex: 5,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'prawn-masala',
    name: 'Spicy Prawn Masala (Shrimp Curry)',
    hindiName: 'झींगा मसाला (प्रॉन मसाला)',
    aliases: ['prawn masala', 'shrimp curry', 'jhinga masala', 'prawn curry'],
    category: 'Fish & Seafood',
    source: 'IFCT',
    cookingMethod: 'fresh prawns cooked in spicy onion, tomato, coconut & kokum gravy',
    per100g: {
      kcal: 135,
      proteinG: 18.0,
      carbsG: 4.2,
      fatG: 5.0,
      fiberG: 0.9,
      sugarsG: 1.5,
      sodiumMg: 340,
      potassiumMg: 260,
      calciumMg: 85,
      ironMg: 1.8,
      magnesiumMg: 36,
      zincMg: 1.5,
      vitaminA_ug: 35,
      vitaminC_mg: 4.0,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 1.8,
      folate_ug: 12,
    },
    glycemicIndex: 10,
    isVegetarian: false,
    isVegan: false,
  },
  {
    id: 'canned-tuna-water',
    name: 'Canned Light Tuna in Water (Drained)',
    hindiName: 'टूना मछली',
    aliases: ['tuna', 'canned tuna', 'tuna in water', 'tuna fish'],
    category: 'Fish & Seafood',
    source: 'USDA',
    cookingMethod: 'pressure cooked and canned in water',
    per100g: {
      kcal: 116,
      proteinG: 25.5,
      carbsG: 0.0,
      fatG: 0.8,
      fiberG: 0.0,
      sugarsG: 0.0,
      sodiumMg: 338,
      potassiumMg: 237,
      calciumMg: 11,
      ironMg: 1.5,
      magnesiumMg: 31,
      zincMg: 0.8,
      vitaminA_ug: 18,
      vitaminC_mg: 0,
      vitaminD_ug: 1.7,
      vitaminB12_ug: 2.9,
      folate_ug: 4,
    },
    glycemicIndex: 0,
    isVegetarian: false,
    isVegan: false,
  },

  // 6. Milks & Beverages
  {
    id: 'milk-cow-toned',
    name: 'Toned Cow Milk (3% Fat)',
    hindiName: 'टोंड गाय का दूध',
    aliases: ['cow milk', 'toned milk', 'milk', 'doodh'],
    category: 'Beverages & Dairy',
    source: 'IFCT',
    cookingMethod: 'pasteurized standardized milk',
    per100g: {
      kcal: 58,
      proteinG: 3.2,
      carbsG: 4.7,
      fatG: 3.0,
      fiberG: 0.0,
      sugarsG: 4.7,
      sodiumMg: 45,
      potassiumMg: 145,
      calciumMg: 120,
      ironMg: 0.05,
      magnesiumMg: 12,
      zincMg: 0.4,
      vitaminA_ug: 32,
      vitaminC_mg: 1.0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.4,
      folate_ug: 6,
    },
    glycemicIndex: 30,
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
  },
  {
    id: 'chaas-buttermilk',
    name: 'Salted Masala Chaas (Spiced Buttermilk)',
    hindiName: 'छाछ / मट्ठा',
    marathiName: 'ताक',
    aliases: ['chaas', 'buttermilk', 'masala chaas', 'taak', 'mattha', 'salted lassi'],
    category: 'Beverages & Dairy',
    source: 'IFCT',
    cookingMethod: 'churned curd diluted with water, roasted cumin, black salt and mint',
    per100g: {
      kcal: 28,
      proteinG: 1.6,
      carbsG: 2.4,
      fatG: 1.2,
      fiberG: 0.1,
      sugarsG: 2.3,
      sodiumMg: 180,
      potassiumMg: 85,
      calciumMg: 65,
      ironMg: 0.2,
      magnesiumMg: 8,
      zincMg: 0.3,
      vitaminA_ug: 12,
      vitaminC_mg: 0.8,
      vitaminD_ug: 0.05,
      vitaminB12_ug: 0.2,
      folate_ug: 4,
    },
    glycemicIndex: 12,
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
  },
  {
    id: 'sweet-lassi',
    name: 'Punjabi Sweet Lassi',
    hindiName: 'मीठी लस्सी',
    aliases: ['lassi', 'sweet lassi', 'punjabi lassi'],
    category: 'Beverages & Dairy',
    source: 'IFCT',
    cookingMethod: 'thick whole milk curd churned with sugar, cardamom & topped with malai',
    per100g: {
      kcal: 110,
      proteinG: 3.2,
      carbsG: 16.5,
      fatG: 3.4,
      fiberG: 0.0,
      sugarsG: 16.0,
      sodiumMg: 40,
      potassiumMg: 130,
      calciumMg: 110,
      ironMg: 0.1,
      magnesiumMg: 11,
      zincMg: 0.5,
      vitaminA_ug: 35,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.3,
      folate_ug: 6,
    },
    glycemicIndex: 58,
    isVegetarian: true,
    isVegan: false,
    isFastingSafe: true,
  },
  {
    id: 'chai-masala-milk',
    name: 'Indian Masala Chai with Milk & Sugar',
    hindiName: 'मसाला चाय',
    aliases: ['chai', 'tea', 'masala chai', 'milk tea', 'adrak chai'],
    category: 'Beverages',
    source: 'composite',
    cookingMethod: 'black tea leaves boiled with crushed ginger, cardamom, toned milk & sugar',
    per100g: {
      kcal: 65,
      proteinG: 2.0,
      carbsG: 9.5,
      fatG: 2.1,
      fiberG: 0.1,
      sugarsG: 9.0,
      sodiumMg: 28,
      potassiumMg: 95,
      calciumMg: 75,
      ironMg: 0.2,
      magnesiumMg: 9,
      zincMg: 0.3,
      vitaminA_ug: 18,
      vitaminC_mg: 0.2,
      vitaminD_ug: 0.05,
      vitaminB12_ug: 0.2,
      folate_ug: 4,
    },
    glycemicIndex: 52,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'coconut-water-fresh',
    name: 'Tender Coconut Water (Nariyal Pani)',
    hindiName: 'नारियल पानी',
    aliases: ['coconut water', 'nariyal pani', 'tender coconut'],
    category: 'Beverages & Electrolytes',
    source: 'IFCT',
    cookingMethod: 'fresh raw natural liquid from green tender coconut',
    per100g: {
      kcal: 19,
      proteinG: 0.7,
      carbsG: 3.7,
      fatG: 0.2,
      fiberG: 0.0,
      sugarsG: 2.6,
      sodiumMg: 25,
      potassiumMg: 250,
      calciumMg: 24,
      ironMg: 0.3,
      magnesiumMg: 25,
      zincMg: 0.1,
      vitaminA_ug: 0,
      vitaminC_mg: 2.4,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 3,
    },
    glycemicIndex: 35,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'sattu-sharbat',
    name: 'Bihari Sattu Sharbat (Roasted Gram Flour Drink)',
    hindiName: 'सत्तू शर्बत (नमकीन)',
    aliases: ['sattu', 'sattu sharbat', 'sattu drink'],
    category: 'Beverages & High-Protein',
    source: 'IFCT',
    cookingMethod: 'roasted chana sattu flour mixed with chilled water, roasted cumin, black salt & lemon juice',
    per100g: {
      kcal: 115,
      proteinG: 6.5,
      carbsG: 18.0,
      fatG: 1.8,
      fiberG: 4.2,
      sugarsG: 0.8,
      sodiumMg: 240,
      potassiumMg: 220,
      calciumMg: 35,
      ironMg: 2.4,
      magnesiumMg: 38,
      zincMg: 1.1,
      vitaminA_ug: 8,
      vitaminC_mg: 6.0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 40,
    },
    glycemicIndex: 28,
    isVegetarian: true,
    isVegan: true,
  },

  // 7. Nuts, Seeds & Superfoods
  {
    id: 'almonds-raw',
    name: 'Raw California / Mamra Almonds (Badam)',
    hindiName: 'बादाम',
    aliases: ['almonds', 'almond', 'badam', 'soaked almonds', 'raw almonds'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'raw unsalted whole kernel',
    per100g: {
      kcal: 579,
      proteinG: 21.2,
      carbsG: 21.6,
      fatG: 49.9,
      fiberG: 12.5,
      sugarsG: 4.4,
      sodiumMg: 1,
      potassiumMg: 733,
      calciumMg: 269,
      ironMg: 3.7,
      magnesiumMg: 270,
      zincMg: 3.1,
      vitaminA_ug: 0,
      vitaminC_mg: 0,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 44,
    },
    glycemicIndex: 0,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'walnuts-raw',
    name: 'Raw Walnuts (Akhrot Halves)',
    hindiName: 'अखरोट',
    aliases: ['walnuts', 'walnut', 'akhrot'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'raw shelled halves',
    per100g: {
      kcal: 654,
      proteinG: 15.2,
      carbsG: 13.7,
      fatG: 65.2,
      fiberG: 6.7,
      sugarsG: 2.6,
      sodiumMg: 2,
      potassiumMg: 441,
      calciumMg: 98,
      ironMg: 2.9,
      magnesiumMg: 158,
      zincMg: 3.1,
      vitaminA_ug: 1,
      vitaminC_mg: 1.3,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 98,
    },
    glycemicIndex: 0,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'chia-seeds',
    name: 'Organic Chia Seeds (Salvia hispanica)',
    hindiName: 'चिया बीज',
    aliases: ['chia seeds', 'chia seed', 'chia'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'raw whole seeds',
    per100g: {
      kcal: 486,
      proteinG: 16.5,
      carbsG: 42.1,
      fatG: 30.7,
      fiberG: 34.4,
      sugarsG: 0.0,
      sodiumMg: 16,
      potassiumMg: 407,
      calciumMg: 631,
      ironMg: 7.7,
      magnesiumMg: 335,
      zincMg: 4.6,
      vitaminA_ug: 3,
      vitaminC_mg: 1.6,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 49,
    },
    glycemicIndex: 1,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },
  {
    id: 'pumpkin-seeds',
    name: 'Raw Pumpkin Seeds (Pepitas)',
    hindiName: 'कद्दू के बीज',
    aliases: ['pumpkin seeds', 'pepitas', 'kaddu ke beej'],
    category: 'Nuts & Seeds',
    source: 'USDA',
    cookingMethod: 'shelled raw green kernels',
    per100g: {
      kcal: 559,
      proteinG: 30.2,
      carbsG: 10.7,
      fatG: 49.1,
      fiberG: 6.0,
      sugarsG: 1.4,
      sodiumMg: 7,
      potassiumMg: 809,
      calciumMg: 46,
      ironMg: 8.8,
      magnesiumMg: 592,
      zincMg: 7.8,
      vitaminA_ug: 1,
      vitaminC_mg: 1.9,
      vitaminD_ug: 0,
      vitaminB12_ug: 0,
      folate_ug: 58,
    },
    glycemicIndex: 10,
    isVegetarian: true,
    isVegan: true,
    isFastingSafe: true,
  },

  // 8. Popular Indian Sweets
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun in Rose Sugar Syrup',
    hindiName: 'गुलाब जामुन',
    aliases: ['gulab jamun', 'gulabjamun'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'fried khoya & maida dough balls soaked in cardamom rose flavored sugar syrup',
    per100g: {
      kcal: 320,
      proteinG: 4.5,
      carbsG: 49.0,
      fatG: 12.0,
      fiberG: 0.4,
      sugarsG: 42.0,
      sodiumMg: 85,
      potassiumMg: 95,
      calciumMg: 110,
      ironMg: 0.8,
      magnesiumMg: 18,
      zincMg: 0.6,
      vitaminA_ug: 45,
      vitaminC_mg: 0,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.2,
      folate_ug: 8,
    },
    glycemicIndex: 78,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'rasgulla',
    name: 'Bengali Rasgulla (Cottage Cheese Balls in Sugar Syrup)',
    hindiName: 'रसगुल्ला',
    aliases: ['rasgulla', 'roshogolla', 'white rasgulla'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'fresh chhena dumplings kneaded and boiled in light sugar syrup',
    per100g: {
      kcal: 186,
      proteinG: 4.2,
      carbsG: 38.0,
      fatG: 1.8,
      fiberG: 0.0,
      sugarsG: 35.0,
      sodiumMg: 45,
      potassiumMg: 75,
      calciumMg: 120,
      ironMg: 0.4,
      magnesiumMg: 12,
      zincMg: 0.5,
      vitaminA_ug: 25,
      vitaminC_mg: 0,
      vitaminD_ug: 0.05,
      vitaminB12_ug: 0.2,
      folate_ug: 6,
    },
    glycemicIndex: 72,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'kheer-rice-pudding',
    name: 'Rice Kheer (Creamy Milk Pudding)',
    hindiName: 'चावल की खीर',
    aliases: ['kheer', 'rice kheer', 'payasam', 'rice payasam'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'slow boiled full fat milk with aromatic rice, sugar, cardamom, raisins & pistachios',
    per100g: {
      kcal: 140,
      proteinG: 3.8,
      carbsG: 22.0,
      fatG: 4.0,
      fiberG: 0.3,
      sugarsG: 15.0,
      sodiumMg: 48,
      potassiumMg: 140,
      calciumMg: 130,
      ironMg: 0.5,
      magnesiumMg: 16,
      zincMg: 0.6,
      vitaminA_ug: 38,
      vitaminC_mg: 0.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.3,
      folate_ug: 8,
    },
    glycemicIndex: 62,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'gajar-ka-halwa',
    name: 'Gajar Ka Halwa (Carrot Pudding with Khoya & Ghee)',
    hindiName: 'गाजर का हलवा',
    aliases: ['gajar halwa', 'gajar ka halwa', 'carrot halwa'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'grated red carrots slow simmered in milk, thickened with mawa, roasted in desi ghee & sugar',
    per100g: {
      kcal: 260,
      proteinG: 4.5,
      carbsG: 36.0,
      fatG: 10.8,
      fiberG: 2.2,
      sugarsG: 28.0,
      sodiumMg: 85,
      potassiumMg: 210,
      calciumMg: 120,
      ironMg: 1.1,
      magnesiumMg: 22,
      zincMg: 0.7,
      vitaminA_ug: 420,
      vitaminC_mg: 4.5,
      vitaminD_ug: 0.1,
      vitaminB12_ug: 0.3,
      folate_ug: 18,
    },
    glycemicIndex: 60,
    isVegetarian: true,
    isVegan: false,
  },
  {
    id: 'besan-ladoo',
    name: 'Traditional Besan Ladoo with Desi Ghee',
    hindiName: 'बेसन का लड्डू',
    aliases: ['besan ladoo', 'besan laddu', 'gram flour laddu'],
    category: 'Sweets & Desserts',
    source: 'IFCT',
    cookingMethod: 'coarse chickpea flour roasted fragrant in cow ghee, mixed with bura sugar & rolled into spheres',
    per100g: {
      kcal: 480,
      proteinG: 8.5,
      carbsG: 54.0,
      fatG: 25.5,
      fiberG: 3.8,
      sugarsG: 38.0,
      sodiumMg: 45,
      potassiumMg: 240,
      calciumMg: 45,
      ironMg: 2.6,
      magnesiumMg: 52,
      zincMg: 1.4,
      vitaminA_ug: 120,
      vitaminC_mg: 0,
      vitaminD_ug: 0.2,
      vitaminB12_ug: 0,
      folate_ug: 42,
    },
    glycemicIndex: 58,
    isVegetarian: true,
    isVegan: false,
  },
];

// Verify Atwater check for all additional rows before proceeding
for (const row of additionalRows) {
  const { kcal, proteinG, carbsG, fatG } = row.per100g;
  const calcAtwater = proteinG * 4 + carbsG * 4 + fatG * 9;
  const diff = Math.abs(kcal - calcAtwater);
  const relErr = diff / Math.max(1, kcal);
  if (relErr >= 0.12) {
    throw new Error(`Row ${row.name} failed Atwater: stated ${kcal} vs ${calcAtwater.toFixed(1)} (${(relErr * 100).toFixed(1)}%)`);
  }
}

console.log(`All ${additionalRows.length} additional rows strictly pass Atwater energy balance!`);

// Load current nutritionTable.ts
const targetFile = path.join(process.cwd(), 'src/data/nutritionTable.ts');
let content = fs.readFileSync(targetFile, 'utf8');

// Find end of NUTRITION_TABLE array (before final `];`)
const lastBracketIndex = content.lastIndexOf('];');
if (lastBracketIndex === -1) {
  throw new Error("Could not find ending '];' in nutritionTable.ts");
}

const formattedAdditional = additionalRows.map(r => JSON.stringify(r, null, 2)).join(',\n  ');
const newContent = content.slice(0, lastBracketIndex) + ',\n  ' + formattedAdditional + '\n];\n';

fs.writeFileSync(targetFile, newContent, 'utf8');
console.log("Successfully updated nutritionTable.ts with verified items!");
